### ISSUE TITLE
Make release automation

### ISSUE THREAD

**Issue by timothysc** [heptio/sonobuoy#100]
The way a release is tag'd and push images needs some cleanliness.  This is a placeholder for that work.  Although I would like to do it for 0.9.0 it's probably more prudent to wait and make sure it's complete.

**Comment by timothysc** [comment]
punting out due to other priorities.

**Comment by timothysc** [comment]
@nrb - where do we stand on our new build-jiggery?  I'd like to fixup Sonobuoy and have a single multi-staged dockerfile

**Comment by nrb** [comment]
The new instances aren't quite ready, but multi-staged builds will be supported.

We're aiming to support builds with a [Jenkinsfile](https://jenkins.io/doc/book/pipeline/syntax/), but definitely advise being able to do your builds via Makefile and use Jenkins to tie stages (like testing) together.

**Comment by timothysc** [comment]
Auto rotate the buildInfo version as part of the make release process.

**Comment by timothysc** [comment]
The requirements are: 

make release VERSION=foo 

1. Without VERSION fail 
2. Take version and update defaults in the version file and propagate those defaults to be used throughout gen & run 
3. Create an annotated tag with the same comment name 

There will still need to be PR+merge for the version bump and a git push --tags after that.  

But that should be the only manual steps and we can comment that in the make release artifact.  

Most of this work is plumbing const-overrides through the default builds.  

It's entirely possible we may get clever simplicity in the make<> build goo.

**Comment by timothysc** [comment]
Last change is to hook in docker push w/go-releaser if possible.

**Comment by timothysc** [comment]
Per conversation there will be two steps for any release. 
1.) Make a PR that updates the default buildInfo.Version b/c that value will be used by `go get` 
2.) git tag -a "vX.Y.Z" and push said tag to kick the automation for artifacts. 

/cc @liztio @chuckha

**Comment by liztio** [comment]
`docker push` and `goreleaser` are hooked up and working. Do we need any more artifacts here, or can we call this done?

**Comment by timothysc** [comment]
We need to write an internal facing doc, but that can be done async. 

Thx @liztio 

Done!
