### ISSUE TITLE
Change Log, Release Notes, Other Cleaning.

### ISSUE THREAD

**Issue by timothysc** [heptio/sonobuoy#104]
Need to walk through and create a release notes and change-log for 0.9.0 prior to release.

**Comment by abiogenesis-now** [comment]
I can work on this in a bit!

**Comment by abiogenesis-now** [comment]
Draft: https://github.com/heptio/sonobuoy/releases/tag/untagged-5dc58755aa2301fa7f14
We'll need to update this to point at the commit that we *actually* want to tag with `v0.9.0`, for now I've just set it to the most recent one.

**Comment by timothysc** [comment]
Thanks @abiogenesis-now I'll add any minor updates before we release.

**Comment by timothysc** [comment]
@abiogenesis-now gah! I get a 404 now on that link

**Comment by timothysc** [comment]
Closing this now and will publish the draft that is there on release.

**Comment by timothysc** [comment]
released, closing
