### ISSUE TITLE
Document plugin done-file semantics.

### ISSUE THREAD

**Issue by chuckha** [heptio/sonobuoy#110]
Plugins can be run in an order based on done files. If a volume gets shared between containers in a pod, each pod can wait for a particular file to appear before running. We are using this idea in the examples for both e2e and systemd log plugins.

This would be a good thing to document.

**Comment by abiogenesis-now** [comment]
Putting this off for a day or so since it's non-blocking for 0.9.0, it's on my TODOs though

**Comment by chuckha** [comment]
I think this is already well covered in [the docs](https://github.com/heptio/sonobuoy/blob/master/docs/plugins.md#under-the-hood). Missed it first go-round.
