### ISSUE TITLE
Public Travis Builds

### ISSUE THREAD

**Issue by timothysc** [heptio/sonobuoy#123]
We'd like to setup public facing builds, possibly with travis. 

/cc @davecheney

**Comment by ncdc** [comment]
I've enabled travis for sonobuoy, as long as there is a `.travis.yml` file in the repo root.

**Comment by liztio** [comment]
The travis builds are set up and working. All that's left to close this out is move the "required" marker from Jenkins to Travis and (optionally) remove the old Jenkins build
