### ISSUE TITLE
quickstart.yaml for release-0.9 pulls from sonobuoy:master 

### ISSUE THREAD

**Issue by sanchoooo** [heptio/sonobuoy#146]
Line 264 in quickstart.yaml for release 0.9 pulls it's image from:
    `image: gcr.io/heptio-images/sonobuoy:master`

where  the conformance test pulls it's image from:
   ` image: gcr.io/heptio-images/sonobuoy:v0.9.0`

Shouldn't quickstart pull the same image as conformance?
I believe this is is possibly the reason for these errors:
```
time="2017-11-14T05:47:20Z" level=info msg="Scanning plugins in ./plugins.d (pwd: /)"
time="2017-11-14T05:47:20Z" level=info msg="unknown template type" filename=..119811_14_11_00_47_18.644356665
time="2017-11-14T05:47:20Z" level=info msg="unknown template type" filename=..data
time="2017-11-14T05:47:20Z" level=info msg="unknown template type" filename=e2e.yaml
time="2017-11-14T05:47:20Z" level=info msg="unknown template type" filename=systemdlogs.yaml
time="2017-11-14T05:47:20Z" level=info msg="Scanning plugins in /etc/sonobuoy/plugins.d (pwd: /)"
time="2017-11-14T05:47:20Z" level=info msg="Directory (/etc/sonobuoy/plugins.d) does not exist"
time="2017-11-14T05:47:20Z" level=info msg="Scanning plugins in ~/sonobuoy/plugins.d (pwd: /)"
time="2017-11-14T05:47:20Z" level=info msg="Directory (~/sonobuoy/plugins.d) does not exist"
time="2017-11-14T05:47:20Z" level=error msg="error loading sonobuoy configuration: Configured plugin systemd_logs does not exist"
```

**Comment by timothysc** [comment]
@sanchoooo - the tag'd releases have pin'd versions, see https://github.com/heptio/sonobuoy/blob/release-0.9/examples/conformance.yaml  

The master branch is undergoing a lot of change now, so it doesn't surprise me that there may be some hiccups prior to the 0.10.0 release.

**Comment by timothysc** [comment]
closing per comment.  
PSA - We're tagging releases and the .yaml is tag'd.  Master will float.
