### ISSUE TITLE
0.10.0 - Release Notes.

### ISSUE THREAD

**Issue by timothysc** [heptio/sonobuoy#147]
@abiogenesis-now - You did such a gr8 job last time I'll tag you again ;-)

**Comment by abiogenesis-now** [comment]
haha thanks! draft is here: https://github.com/heptio/sonobuoy/releases/tag/untagged-a02cf0a8d3ac2b1df8a3

Let me know if I should make any edits (e.g. if I misinterpreted a PR)

Also, just like last time, we'll need to:
* create a release tag
* attach binaries (?)

**Comment by timothysc** [comment]
No need to attach binaries we publish containers.

**Comment by abiogenesis-now** [comment]
Ok! then I think this is pretty much good to go, unless you have any edits you'd like me to make

**Comment by timothysc** [comment]
I'll just leave it open and publish once we tag the release. 

thx @abiogenesis-now !

**Comment by timothysc** [comment]
It's live.
