### ISSUE TITLE
Azure does not allow permissive service account creation but sonobuoy still works

### ISSUE THREAD

**Issue by chuckha** [heptio/sonobuoy#156]
When using the quickstart rbac stuff on Azure `acs` I get this response from `kubectl apply -f az_scanner.yaml`

```
Error from server (Forbidden): error when creating "az_scanner.yaml": clusterroles.rbac.authorization.k8s.io "sonobuoy-serviceaccount" is forbidden: attempt to grant extra privileges: [PolicyRule{Resources:["*"], APIGroups:["*"], Verbs:["*"]}] user=&{kubeconfig  [system:authenticated] map[]} ownerrules=[] ruleResolutionErrors=[]
```

The whole run works, but this account fails to create. Perhaps this doesn't need to exist at all?

**Comment by timothysc** [comment]
It definitely does, b/c without it we won't work on our clusters.

**Comment by timothysc** [comment]
This is b/c on 1.7 they default to AllowAll ...
