### ISSUE TITLE
Collect Audit Logs

### ISSUE THREAD

**Issue by timothysc** [heptio/sonobuoy#163]
This needs to be jig'd through default deployment. 

I don't believe we've settled on a well-defined location /cc @luxas

**Comment by bgeesaman** [comment]
Kube audit logs or audit.d system logs?

**Comment by timothysc** [comment]
Kube audit logs.

**Comment by luxas** [comment]
@timothysc We don't set any audit-specific flags in kubeadm, so I guess it isn't enabled there at all :thinking:. It'd be great to set some sane defaults here, but that requires a broader discussion with the community

**Comment by timothysc** [comment]
@chuckha This one will dovetail with upstream defaults, so you'll have to PR upstream 1st.

**Comment by chuckha** [comment]
https://github.com/kubernetes/kubernetes/pull/59067

**Comment by chuckha** [comment]
kubeadm can now enable audit logging when a feature gate is enabled.

**Comment by timothysc** [comment]
@chuckha I'm thinking this will be a plugin ...

**Comment by chuckha** [comment]
that sounds reasonable. Let's chat about it tomorrow during sync.

**Comment by timothysc** [comment]
I'm going to punt this out of the 0.11.0 milestone b/c it's pending on upstream 1.10 release as well as changes to wardroom, quickstart, etc. 

/cc @detiber

**Comment by timothysc** [comment]
Given the plan is to add a dynamic web-hook.  I'm of the opinion that from a core-sonobuoy perspective this could live as a separate plugin and it not important to the core. 

closing
