### ISSUE TITLE
Easier test selection tool

### ISSUE THREAD

**Issue by rbankston** [heptio/sonobuoy#166]
Would be great to have a command line tool that spit out a quickstart.yaml with the specific tests you wanted run. This would help folks have a faster way to get the tests they want run locally configured.

**Comment by rbankston** [comment]
definitely makes sense, was more thinking something akin to running without RBAC and setting an environment variable for the test to then update the E2E_Focus variable.

**Comment by timothysc** [comment]
We're looking at both ;-)

**Comment by timothysc** [comment]
we should channel this through `sonobuoy run` command.  xref: #27

**Comment by rbankston** [comment]
That seems like a very good place for this for ease of use.

**Comment by timothysc** [comment]
We have gen now, but I'll need to fixup some of the arg stuff on focus and skip.

**Comment by timothysc** [comment]
Fixing in #268 which links to the specific details, closing this one.
