### ISSUE TITLE
A way to tweak E2E performance

### ISSUE THREAD

**Issue by ivanilves** [heptio/sonobuoy#168]
Hi,

First, thank you for sonobuoy! :heart: It rocks!

Second, could we have some mechanism to tweak sonobuoy's performance (e.g. how many E2E tests we could run in parallel, so we could take advantage of having big cluster)? **Anything existing I've missed?** :pray: 

Curretly we need to wait pretty long, >30min, for the E2E test suite to finish. 

I humbly hope there is a way to make it faster. :wink: 

If it's not possible directly, I would be happy to receive any advice how to contribute to make it happen.

Thanks!

**Comment by timothysc** [comment]
Absolutely, this is on the radar https://github.com/heptio/sonobuoy/issues/76 , we've had several comments about having a parallel or lite continuos set of tests.

**Comment by timothysc** [comment]
I've cross-linked the issues and we're going to submit a draft proposal soon-ish, once that is up we will solicit feedback.  

Closing in preference of the existing issue.

**Comment by ivanilves** [comment]
Great. Got it. Thank you!
