### ISSUE TITLE
Rationalize some tests issues upstream.

### ISSUE THREAD

**Issue by timothysc** [heptio/sonobuoy#17]
The Kubectl tests were purposefully disabled for a number of reasons and we should move to rationalize this with upstream.  

1. I don't actually consider them conformance tests, but more aggregated behavioral tests 
2. They require passing in kubeconfig vs. leveraging in-cluster config 
... 

Also there are other tests, including the scheduler tests that I think need to be cherry-picked back to a 1.7 release.

**Comment by timothysc** [comment]
We should also target 0.9.0 against 1.8-kube-release

**Comment by timothysc** [comment]
@chuckha Here is the list of items that would need to get done in order to version match. 

- Setup a 1.8 build of the conformance container (https://github.com/heptio/kube-conformance)  and validate against a 1.7 cluster.  You might want to also run through https://github.com/kubernetes/features/blob/master/release-1.8/release_notes_draft.md and check to see if the new feature e2es have version checking flags.  (https://github.com/kubernetes/kubernetes/blob/master/test/e2e/apimachinery/custom_resource_definition.go#L38) 

- Most of the flakey [Serial] tests have been fixed in 1.8 but we should check with data that @rosskukulinski might have as well.

**Comment by timothysc** [comment]
I'm working on this now along with other 1.8 closeout work.

**Comment by jlamillan** [comment]
Is there a way to pass in the kubeconfig so that these tests can be run?

**Comment by timothysc** [comment]
@jlamillan I'm working to try and remove that requirement and leverage the in-cluster config.  

The only tests that seem to leverage it heavily are the kubectl tests that I'm aware of.

**Comment by jlamillan** [comment]
@timothysc Ok, thanks. So, as of now, it is not possible to successfully run the kubectl tests in containerized Sonobuoy?

**Comment by timothysc** [comment]
You "can" but it's very ugly, and requires a container mod.

**Comment by timothysc** [comment]
Hmm I got ping's on another channel about KUBECONFIG, I'll start cleaning up the plumbing for back-support of 1.6 versions.

**Comment by jlamillan** [comment]
Thanks... very nice work here BTW.

**Comment by rbankston** [comment]
Seems that the [networking test](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/network/networking.go#L48) for kubernetes conformance isn't very robust we might want to not run that test or have it made to work without icmp upstream

**Comment by timothysc** [comment]
Flakes from 1.7 were addressed and comments from feedback were also addressed I'll open an tracking issue re: the network test
