### ISSUE TITLE
ARM versions available ?

### ISSUE THREAD

**Issue by nlamirault** [heptio/sonobuoy#181]
Do you know if ARM images exist ?
I try that but it fails : 
```
$ docker pull gcr.io/heptio-images/sonobuoy-arm:v0.10.0
Error response from daemon: manifest for gcr.io/heptio-images/sonobuoy-arm:v0.10.0 not found
```

**Comment by chuckha** [comment]
Ah, we do not support ARM at this time.

**Comment by vielmetti** [comment]
@chuckha @nlamirault - or anyone who wants to make a go at this - if you need Arm gear for a build/test cycle, Packet and Arm run a "Works on Arm" cluster at http://worksonarm.com/cluster . Submit a proposal at http://github.com/worksonarm/cluster/issues for access.

**Comment by vielmetti** [comment]
I suspect that the right path once there's Arm support is to offer up a "fat manifest" with multiplatform support. Pinging @tianon who has always had good suggestions for build changes that would make this happen.

**Comment by luxas** [comment]
@liztio These are already cross-built and working on multiple platforms... The only thing needed is to make the images on your side cross-built and manifest lists, which should be an ok-sized task to do.

LMK if you need guidance how to do so :)

**Comment by timothysc** [comment]
I'd like us to sort out how we plan to publish new artifacts 1st.

**Comment by timothysc** [comment]
@nrb let me know if/when our new tooling can do some of this and I will enable this.

**Comment by nrb** [comment]
@timothysc Sorry, I think I'm missing something - which part? Publishing artifacts?

**Comment by hh** [comment]
@luxas @timothysc have we come up with a consensus on how to publish artifacts?
I'd know there is interested see if we quickly we can get our first Certified Kubernetes on ARM provider.
What are we missing at this point?

**Comment by timothysc** [comment]
@hh the biggest issue is getting all the upstream test containers pushed for every arch.  

that + pull-images option.
