### ISSUE TITLE
[Feature Request] Ability to re-run single tests

### ISSUE THREAD

**Issue by rdodev** [heptio/sonobuoy#182]
While with a customer, after running the suite and seeing some errors (and trying to fix them) the customer wanted to re-run those tests to see if they passed; however, presently the runs are all-or-nothing so they user needs to run the whole suite once again (~1hr) to see if whatever modification they made fixed the errors.

**Comment by timothysc** [comment]
This is pending on the interface library and other CLI bits.

**Comment by chuckha** [comment]
An idea for the UX: it would be pretty neat to say `sonobuoy rerun-failed path/to/archive.tar.gz` and have sonobuoy figure out which tests to run.

There might also be a use case for trying to re-run one known test without the archive though, perhaps something like this will be covered in the `run` command, like: sonobuoy run -focus "some regex"

**Comment by chuckha** [comment]
but would like to know if that's useful for @rdodev ^

**Comment by rdodev** [comment]
`sb run --failed <archive.tgz>` is a good idea.

For the other one could do something similar to what I proposed for ark,
namely:

`sb run --pattern "*storage*"`

**Comment by timothysc** [comment]
`sb run`  will have `focus` and `skip` pass through params.  I debate if we want to 1st class `fail` or provide a simple utility command that gives you the failed list to pass to focus.  

Thoughts?  @liztio too re: UX.

**Comment by chuckha** [comment]
I'm leaning towards a utility that prints failed tests. That is useful on its own and as a way to generate a regex to rerun just those tests.

**Comment by chuckha** [comment]
`sonobuoy run --focus $(sonobuoy results --failed path/to/archive.tar.gz)`

**Comment by timothysc** [comment]
We need to build that plumbing through from Tarball Client --> CLI/Interface library .  

/cc @fabioy

**Comment by rdodev** [comment]
Wouldn't this add a layer of complexity that wasn't there?

`sb run --failed file.tar.gz` would likely involve the client opening the
tarball, parsing `junit1.xml` gather failures and then somewhat magically*
run those in the cluster again.

Generally speaking when it comes to UX you want to avoid compound
statements i.e. avoid f(g(x))

* Or through 7-dan judo

On Feb 12, 2018 7:52 PM, "Chuck Ha" <notifications@github.com> wrote:

sonobuoy run --focus $(sonobuoy results --failed path/to/archive.tar.gz)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/heptio/sonobuoy/issues/182#issuecomment-365041725>, or mute
the thread

**Comment by timothysc** [comment]
This will be a combination of e2e command and focus param changes that I am making.

**Comment by timothysc** [comment]
We're going to bundle this into #248 

So I'll close this one.  

Feedback is solicited on the UX - https://github.com/heptio/sonobuoy/pull/262
