### ISSUE TITLE
[Feature Request] Better Documentation On Tests

### ISSUE THREAD

**Issue by rdodev** [heptio/sonobuoy#183]
While with a customer after running the tests, customer became curious about what each test actually does, what does it mean when it fails, possible causes of failure and recommended steps to make the tests pass.

Presently there's a firehose of logs and other information, but no way for a customer to make sense of it.

**Comment by timothysc** [comment]
There is a start on upstream documentation, but we haven't figures out how we plan to link it all together.

**Comment by timothysc** [comment]
This is actually going to happen upstream.  In the 1.10/1.11 cycle the entire conformance list will have a separate URL.  

/cc @Bradamant3 @dhanmm
