### ISSUE TITLE
Add documentation describing how to analyze test results

### ISSUE THREAD

**Issue by carsonoid** [heptio/sonobuoy#19]
Right now there is very little in the way of describing what the results look like and how to analyze them.

I was able to dig around and found that the meat of the results is in the tarball under: `resources/ns/heptio-sonobuoy/pods/sonobuoy-e2e-job-*/logs/e2e.tx`

I was able to get a fairly good summary with:

```
grep -A3 • resources/ns/heptio-sonobuoy/pods/sonobuoy-e2e-job-*/logs/e2e.tx
```

But perhaps there should be a docs page describing how to read the results.

**Comment by timothysc** [comment]
We have some PRs and docs coming soon to do just that.

**Comment by timothysc** [comment]
Scanner mostly resolves this now, so closing this item.
