### ISSUE TITLE
Implement status subcommand

### ISSUE THREAD

**Issue by timothysc** [heptio/sonobuoy#209]

**Comment by timothysc** [comment]
From feedback from the field we may want to have a set of simple diagnostics that checks the basics, and could also be called before we run, and can also be surfaced through status.  

One such check is verifying DNS is even there...

**Comment by liztio** [comment]
Major pieces of this feature are:
* pointer from local machine to sonobuoy aggregator
* authentication from local machine to sonobuoy controller
* sonobuoy keeps track of progress in meaningful way
* endpoint for retrieving said status

**Comment by liztio** [comment]
Proposal for Pointer / Authentication:

`sonobuoy run` generates a new CA and a server key/pair. That key pair and CA cert are sent as secrets/env variables to the Sonobuoy aggregator by `sonobuoy run`. `sonobuoy run` will record this information, along with the URL to the cluster, in a file located in `/tmp/sonobuoy_run.json`, along with an expiration timestamp. `sonobuoy status` will look for this json file, connect to the server, and retrieve the results.

**Comment by liztio** [comment]
the endpoint for retrieving status should be separate from the endpoint workers use to report their results. This is for two reasons: 1) the status endpoint needs to use a different TLS certificate (this could be resolved using SNI, but that adds complexity) and 2) this endpoint will likely need to be on a separate network.

**Comment by liztio** [comment]
Should close #51

**Comment by timothysc** [comment]
@liztio I was debating if we just have a simple protocol on health or liveness keep it as simple as possible.

**Comment by liztio** [comment]
@timothysc what would "health" look like? Just checking if the aggregator is still working isn't that helpful...
