### ISSUE TITLE
systemd-logs pods in CrashLoopBackoff because they can't connect to sonobuoy-master

### ISSUE THREAD

**Issue by ceridwen** [heptio/sonobuoy#225]
This is on a Kubernetes cluster with a custom CNI plugin, so it's entirely possible the problem is with the CNI plugin and not sonobuoy.

The logs from the sonobuoy-worker container in the system-logs pods look like:

```
time="2018-02-01T19:04:28Z" level=info msg="Waiting on: (/tmp/results/done)"
time="2018-02-01T19:04:28Z" level=info msg="Detected done file, transmitting: (/tmp/results/systemd_logs)"
time="2018-02-01T19:06:00Z" level=error msg="error dialing master at http://sonobuoy-master:8080/api/v1/results/by-node/vk8-1-u-25-1/systemd_logs: Put http://sonobuoy-master:8080/api/v1/results/by-node/vk8-1-u-25-1/systemd_logs: dial tcp: i/o timeout"
```

I'm asking to find out how the systemd-logs pod is supposed to resolve this DNS entry.  It doesn't look like one of the standard DNS records for a Kubernetes pod, which have a leading IP address, and I couldn't find any pods with the `hostname` field set in the `heptio-sonobuoy` namespace, which is the standard method, AFAIK, of overriding the default DNS entry for a pod.

**Comment by timothysc** [comment]
@ceridwen is kubedns deployed in your environment?

**Comment by ceridwen** [comment]
Yes, the kubedns pods are running on each node, have IPs, and don't have any obvious errors in their logs.

**Comment by timothysc** [comment]
We have been planning to add a set of retries, b/c we've seen issues in name resolution.  

/cc @fabioy

**Comment by ceridwen** [comment]
Just out of curiosity, why do the systemd pods use host networking rather than pod networking?

**Comment by timothysc** [comment]
@liztio did you add retry logic in your plugin refactoring?

**Comment by liztio** [comment]
@timothysc I didn't add it, it was always there. [we use Pester for this](https://github.com/heptio/sonobuoy/blob/v0.10.0/pkg/worker/request.go#L68)

**Comment by timothysc** [comment]
We've so heavily refactored 0.11.0 I'm going to close this and during our qualifications if we run into it we'll reopen.  Otherwise there is not enough details for us to investigate further given the divergence from 0.10.0.

**Comment by chuckha** [comment]
https://kubernetes.slack.com/archives/C6L3G051C/p1531323088000355
