### ISSUE TITLE
There should be an "all-in-one" YAML file

### ISSUE THREAD

**Issue by luxas** [heptio/sonobuoy#23]
It might just be me, but I do like being able to `kubectl apply -f` only one file instead of three :)
Makes remote installation (not cloning the repo easier)

**Comment by timothysc** [comment]
Hmm we explicitly broke them down so that it was easier for folks to understand what was happening.  We thought 1 thunk would be difficult for folks to grok out of the gate.

**Comment by rimusz** [comment]
totally agree with @timothysc on this one

**Comment by timothysc** [comment]
I'm open to suggestions, and I realize it would make some workflows easier.  E.g. you stood up a cluster run this thing from github to qualify your cluster.

**Comment by luxas** [comment]
Why not autogenerate an all-in-one when we have jsonnet for easier installation? Don't want to clone the repo on every install really...

I'm not asking for both, not either-or

**Comment by abiogenesis-now** [comment]
Done with https://github.com/heptio/sonobuoy/pull/58
