### ISSUE TITLE
[Docs Scrub] Broken doc link (Generating your own YAML manifests)

### ISSUE THREAD

**Issue by lblackstone** [heptio/sonobuoy#230]
The `Generating your own YAML manifests` [link](https://github.com/heptio/sonobuoy/blob/master/docs/README.md#next-steps) is broken. It appears that this file was removed in 393fd43d0164549d374e45f75ce04e86edcb4082

**Comment by timothysc** [comment]
We're in the midst of refactoring both the code and the docs, so our apologies re: master atm.
