### ISSUE TITLE
Idea: Let sonobuoy serve results via an HTTP server instead of using `kubectl cp`

### ISSUE THREAD

**Issue by luxas** [heptio/sonobuoy#24]
Would be cool and possibly easier to integrate with other system.
Hard thing is authz (but that might be delegatable to the API server)

**Comment by timothysc** [comment]
So we have other tooling that allows it to toss to any other location, e.g. s3.  

Once we open source that we'll create an example.  

/cc @chuckha

**Comment by timothysc** [comment]
Please take a look at this comment https://github.com/heptio/sonobuoy/pull/20#issuecomment-320690072 .  

With that change you should be able to slap on any front-end service.

**Comment by luxas** [comment]
Thanks!
