### ISSUE TITLE
CI check that `dep ensure` has been run

### ISSUE THREAD

**Issue by liztio** [heptio/sonobuoy#244]
Right now you can submit a pull request that removes a dependency but without removing the vendored packages. This will pass CI, but the next person to run `dep ensure` will get a very large delta by surprise. We should check during CI that `dep ensure` doesn't produce any changes (possibly using `-dry-run`)

**Comment by johnSchnake** [comment]
So the dry-run option is available but unfortunately it doesnt output a status code we can easily check.

It does seem to just print changes to stdout though so maybe we can just ensure that it produces 0 output (note the warning wouldnt/shouldnt fail our dep check, just the output on stdout):

```
 dep ensure --dry-run > output.tmp
Warning: the following project(s) have [[constraint]] stanzas in Gopkg.toml:

  ✗  k8s.io/apiextensions-apiserver

However, these projects are not direct dependencies of the current project:
they are not imported in any .go files, nor are they in the 'required' list in
Gopkg.toml. Dep only applies [[constraint]] rules to direct dependencies, so
these rules will have no effect.

Either import/require packages from these projects so that they become direct
dependencies, or convert each [[constraint]] to an [[override]] to enforce rules
on these projects, if they happen to be transitive dependencies.

➜  sonobuoy git:(depEnsureCI) ✗ cat output.tmp
Would have written Gopkg.lock.
Would have updated the following projects in the vendor directory:

(0/1) Would have written golang.org/x/text@v0.3.0: packages changed (1 added)
```

@zubron seem sane to you?
