### ISSUE TITLE
Creation of an e2e sub-command and tarball interface layer

### ISSUE THREAD

**Issue by timothysc** [heptio/sonobuoy#248]
## Problem statement 

We need an interface library above the tarball interface that provides some base level aggregate functions for getting summary information from e2e style runs, across multiple e2e-style-plugins.  

The abstraction layer should provide very basic rolled up data at 1st and we can refine the requirements over time.  

For example, a common case would be to roll up passing and failing, with a single boolean variable.  If the boolean is false a list of the failed tests are provided for automation.  

A string list that can be `regex or'd |` together and could be passed back into run via a focus varible to execute just those failed tests.   

I'd argue that this is a degenerative use case and should generally be discouraged, but hey "stuff happens" and this is hard. 

Prior to beginning this work, we should create a SEP that outlines some of these details and references this issue. 

/cc @fabioy @k8k

**Comment by chuckha** [comment]
Prerequisite work:

1) refactor Run command to accept manifest bytes. The cmd should be generating the manifest and sending it to the ops function. This will improve the flexibility to run custom manifests (required for the rerun portion of this task)
2) refactor Mode / GenManifest to be able to generate manifest based on a custom templateVar struct. Right now it is assumed all values in the template are static for the specific modes. That is no longer the case when generating a rerun manifest.
