### ISSUE TITLE
"systemd_logs to not exist"

### ISSUE THREAD

**Issue by soggiest** [heptio/sonobuoy#251]
Following the instructions found in the `release-o.10` branch the following error is returned from the sonobuoy pod:

```
heptio-sonobuoy sonobuoy kube-sonobuoy time="2018-02-08T23:48:53Z" level=info msg="Scanning plugins in ./plugins.d (pwd: /)"
heptio-sonobuoy sonobuoy kube-sonobuoy time="2018-02-08T23:48:53Z" level=info msg="Scanning plugins in /etc/sonobuoy/plugins.d (pwd: /)"
heptio-sonobuoy sonobuoy kube-sonobuoy time="2018-02-08T23:48:53Z" level=info msg="Directory (/etc/sonobuoy/plugins.d) does not exist"
heptio-sonobuoy sonobuoy kube-sonobuoy time="2018-02-08T23:48:53Z" level=info msg="Scanning plugins in ~/sonobuoy/plugins.d (pwd: /)"
heptio-sonobuoy sonobuoy kube-sonobuoy time="2018-02-08T23:48:53Z" level=info msg="Directory (~/sonobuoy/plugins.d) does not exist"
heptio-sonobuoy sonobuoy kube-sonobuoy time="2018-02-08T23:48:53Z" level=error msg="error loading sonobuoy configuration: Configured plugin systemd_logs does not exist"```

**Comment by timothysc** [comment]
@soggiest - You had an issue when running the repo(s) conformance.yaml file from v0.10.0 ?- https://github.com/heptio/sonobuoy/blob/release-0.10/examples/conformance.yaml ?

**Comment by soggiest** [comment]
We were following the instructions located at:
https://github.com/heptio/sonobuoy/tree/release-0.10#2-run

**Comment by timothysc** [comment]
try - `kubectl apply -f https://raw.githubusercontent.com/heptio/sonobuoy/release-0.10/examples/conformance.yaml`

The generation for a branch didn't tag the container images, we are removing all of that in v0.11.0 to simplify and cleanup the UX.
