### ISSUE TITLE
Use a more clever daemonset driver

### ISSUE THREAD

**Issue by chuckha** [heptio/sonobuoy#255]
The k8s DaemonSet [requires the pod spec to have a restartPolicy of always][daemonset]. When a daemonset plugin is finished we have to make it sleep forever or else the daemonset will simply rerun it over and over until the aggregator shuts down the daemonset.

A few approaches we could consider:

After a pod finishes, we could create a taint on the node and evict the pod (but this requires existing pod eviction which is an alpha feature as of 1.9)

We could work around the alpha feature requirement by making a taint and deleting the pod manually.

Alternatively we could launch a Pod directly onto each node and then our Daemonset driver would be a for loop around our Job driver.

I'm sure there are many other approaches as well.

[daemonset]: https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/#pod-template

**Comment by liztio** [comment]
I think my vote is for launching pods directly. Sonobuoy should use a minimum number of features so the tests can run partially in very obscure environments

**Comment by timothysc** [comment]
> The k8s DaemonSet requires the pod spec to have a restartPolicy of always. When a daemonset plugin is finished we have to make it sleep forever or else the daemonset will simply rerun it over and over until the aggregator shuts down the daemonset.

I'm ok with this, as the aggregator cleans it up, and delete will also clean it up. 

> After a pod finishes, we could create a taint on the node and evict the pod  

Yeah I don't think we should be doing this and it could raise some red flags.

**Comment by surajssd** [comment]
Is there a plan to write a custom resource and a controller to implement this?

**Comment by timothysc** [comment]
@surajssd not really, b/c sonobuoy is 1-shot, or ephemeral.  

I consider it a full-body-CT scan, not something you'd be doing continuously, so CRD+controller would be pretty overkill.

**Comment by surajssd** [comment]
@timothysc yeah makes sense. Also I was reading if the DameonSetJob was implemented but then it never went anywhere it seems so, this has to be hand written it seems.

**Comment by johnSchnake** [comment]
Just for anyone else looking, there are a few issues upstream talking about this and they never really went anywhere as mentioned. The best workaround I've seen is what we are already doing; just sleeping after the work is done and waiting to be destroyed.

I don't anticipate this changing any time soon (if ever). Going to mark as closed as a result.
