### ISSUE TITLE
Provide information about how to run the full Conformance Suite

### ISSUE THREAD

**Issue by luxas** [heptio/sonobuoy#26]
I see that it's controlled by [this line](https://github.com/heptio/sonobuoy/blob/master/examples/quickstart/10-configmaps.yaml#L187), but please document somewhere visible so it's easier to find for others.

**Comment by luxas** [comment]
Gah, totally missed that doc in my morning run of this. LGTM
Of course this can be kept as "document various things better" as that is always possible, but you did have what I was looking for.

**Comment by abiogenesis-now** [comment]
I'll modify the main README to surface this info more visibly

**Comment by luxas** [comment]
Thank you @abiogenesis-now!

**Comment by timothysc** [comment]
Should be updated now.
