### ISSUE TITLE
Provide a CLI tool for running sonobuoy

### ISSUE THREAD

**Issue by luxas** [heptio/sonobuoy#27]
We all know that our lovely Kubernetes YAML definitions can be a little overwhelming sometimes...
If the user wants to add/remove functionality right now, they would have to go and mess with those.

In order to get more users of the tool; a CLI tool could be made to simplify that experience

(Feel free to disregard; these are just ideas coming from me on my first sonobuoy run :wink: )

**Comment by timothysc** [comment]
Totally not crazy, and @kensimon has suggested it as well.  

Assigning it to him.

**Comment by timothysc** [comment]
Right now we have a web asset which makes it alot easier, we may get to a CLI... but it's lower on the priority list unless someone wants to help out here.

**Comment by timothysc** [comment]
decided to close in preference to automation with ksonnet and scanner.

**Comment by timothysc** [comment]
Nope nope nope... ksonneting from the inside out is a failed experiment, wrapping the behavior with a cli for different modes is far easier, and provides a cleaner UX.   Given the flexibility of cobra the single binary can behave in multiple ways.  We should make the `go get` experience clean.

**Comment by timothysc** [comment]
subcommands should be: 

- run (auto check cluster and then generate submission) 
- logs 
- status
- copy/results 
- destroy/cleanup

@chuckha @liztio feel free to take anything but run whilst I'm out.

**Comment by timothysc** [comment]
I'll close this main one once we break down the different subcommands and issues and link here.

**Comment by timothysc** [comment]
Stubs are merged and subcommand issues are open, moving work there now.

**Comment by timothysc** [comment]
I'm closing this as we have issues open for the other pieces and are in flight on everything else.
