### ISSUE TITLE
Refactor cp -> retrieve and factor out functions for UX cleanliness. 

### ISSUE THREAD

**Issue by timothysc** [heptio/sonobuoy#274]
On code walk-through on Thursday there were some issues on UX 

// TODO (timothysc) change the name to retrieve

// TODO (timothysc) abstract copy details into a lower level function.

**Comment by chuckha** [comment]
> // TODO (timothysc) abstract copy details into a lower level function.

Please clarify this TODO, I don't understand which details you'd like abstracted. (this stuff? https://github.com/heptio/sonobuoy/blob/master/pkg/client/cp.go#L43)
