### ISSUE TITLE
Release Docs

### ISSUE THREAD

**Issue by timothysc** [heptio/sonobuoy#275]
Need to create the release documentation.

**Comment by timothysc** [comment]
@liztio - the build status link needs a refresh to get state from a travis URL

**Comment by liztio** [comment]
@timothysc this is done

**Comment by timothysc** [comment]
Only remaining items now are:
- finish copy editing other docs
- create the v0.11.0 releases draft

**Comment by Bradamant3** [comment]
See PR #371 for first item ^
Will create the draft v0.11.0 release page 3/15
