### ISSUE TITLE
[Broken Link] In Conformance Testing Docs

### ISSUE THREAD

**Issue by christopherhein** [heptio/sonobuoy#276]
> To customize the set of tests that will be run as part of the report, the following environmental variables can be set in the `plugin-specific YAML config`:

The `plugin-specific YAML config` link returns a 404 for https://github.com/heptio/sonobuoy/blob/master/plugins.d/e2e.tmpl I'm guessing it's suppose to point to https://github.com/heptio/sonobuoy/blob/master/examples/plugins.d/e2e.yaml, right?

**Comment by timothysc** [comment]
@christopherhein this is being completely refactored in v0.11.0, so master branch right now is a WIP.

**Comment by christopherhein** [comment]
Thanks @timothysc

**Comment by timothysc** [comment]
Fixed
