### ISSUE TITLE
Implement sonobuoy delete subcommand

### ISSUE THREAD

**Issue by timothysc** [heptio/sonobuoy#277]
This seems to have fallen off the radar amidst all the other work.  

It should try to do the namespace, or label based deletion.  

The weird part here is making sure the other namespaces `e2e etc` are all cleaned up if there was a botched run.

**Comment by liztio** [comment]
Unfortunately the namespaces for all the other e2e tests are randomly generated per-test, so getting rid of them is tricky

**Comment by timothysc** [comment]
They should be prefix'd `e2e-` 

The things that aren't are bugz imo.

**Comment by liztio** [comment]
Done by #295
