### ISSUE TITLE
Why is ./plugins/e2e/results.tar.gz tarred twice?

### ISSUE THREAD

**Issue by luxas** [heptio/sonobuoy#28]
I'd expect sonobuoy to produce the tar file for me to untar once and not have multiple layers of tarred files.
I guess this is just the output from the plugin, but could sonobuoy handle untarring possible .tar.gz files produced by plugins (like e2e)?

**Comment by timothysc** [comment]
So the plugins allow for one file to be transferred and it was simple.  I suppose we could modify aggregation to explode transferred file.

**Comment by kensimon** [comment]
This is fixed in v0.8.2
