### ISSUE TITLE
Higher-level aggregation of the kubelet logs in scope?

### ISSUE THREAD

**Issue by luxas** [heptio/sonobuoy#29]
I saw that `journalctl -o json ...` was used for creating the logs file, but how do I actually read that I may wonder as an user...
I quickly searched Google for how to parse journalctl JSON output to something slightly more readable (default journalctl output for example), but couldn't find anything quickly at least.
It would be nice with at least some words on how you can parse/aggregate that json.

**Comment by timothysc** [comment]
So the output of sonobuoy really isn't meant to be read by most humans, but by other tooling which is why the json logs are there.

**Comment by luxas** [comment]
I meant that would you be able to document _how_ I can interpret that data with some kind of tool.
I don't know how I can parse that output, even with other tooling.

**Comment by timothysc** [comment]
We are planning on building an interface library to handle this, closing in favor of: #97
