### ISSUE TITLE
Run should not exit if it cannot create an object

### ISSUE THREAD

**Issue by chuckha** [heptio/sonobuoy#291]
When run creates objects from the manifest it should not exit if it fails to create the service account just because the service account already exists.

Reproduce: do a sonobuoy run, delete the heptio-sonobuoy namespace, try to `sonobuoy run --mode=quick --preflight` and you get 

```
ERRO[0002] error attempting to run sonobuoy: failed to create object: failed to create API resource sonobuoy-serviceaccount: clusterrolebindings.rbac.authorization.k8s.io "sonobuoy-serviceaccount" already exists 
```

which isn't really an error state

**Comment by chuckha** [comment]
(same for cluster role binding and cluster role)

**Comment by chuckha** [comment]
with kubectl apply i get this behavior:

```
namespace "heptio-sonobuoy" created
serviceaccount "sonobuoy-serviceaccount" created
clusterrolebinding "sonobuoy-serviceaccount" configured
clusterrole "sonobuoy-serviceaccount" configured
configmap "sonobuoy-config-cm" created
configmap "sonobuoy-plugins-cm" created
pod "sonobuoy" created
service "sonobuoy-master" created
```

**Comment by liztio** [comment]
Could we allow duplicates for anything without a namespace? Does that make sense?

**Comment by liztio** [comment]
I don't want to do the full "merge" logic because it's really complicated and kubectl doesn't export any of it

**Comment by chuckha** [comment]
Yeah that seems reasonable.
