### ISSUE TITLE
const all the defaults.

### ISSUE THREAD

**Issue by timothysc** [heptio/sonobuoy#293]
Right now we have default f(n) that should be referencing consts.  

/cc @chuckha

**Comment by johnSchnake** [comment]
Some of those default functions are not getting used or are just _wrong_. Will review and update to make more clean/understandable

**Comment by johnSchnake** [comment]
Considering this closed; clearly we will always have the intent to make clean code that references constants rather than magic strings/values but no point in keeping this vague ticket open any longer.
