### ISSUE TITLE
Configured plugin systemd_logs does not exist

### ISSUE THREAD

**Issue by evaldasou** [heptio/sonobuoy#30]
Hey Heptio Team.

When  I check logs of my just deployed pod it exists with this error: 

```
root:heptio# kubectl logs -f sonobuoy --namespace=heptio-sonobuoy
I0807 13:53:51.548619       1 loader.go:46] Scanning plugins in ./plugins.d (pwd: /)
I0807 13:53:51.548852       1 loader.go:46] Scanning plugins in /etc/sonobuoy/plugins.d (pwd: /)
I0807 13:53:51.548880       1 loader.go:46] Scanning plugins in ~/sonobuoy/plugins.d (pwd: /)
E0807 13:53:51.548907       1 master.go:49] Configured plugin systemd_logs does not exist
```

Any ideas , something is missing on the cluster itself?

**Comment by kensimon** [comment]
I think this is a race condition with how the resources in `examples/quickstart` are created... we create 2 configmaps, one with `/etc/sonobuoy/config.json`, and one with `/etc/sonobuoy/plugins.d/*`... it's possible the pod launched after the config.json was available but before the plugins.d files were.

If you do `kubectl -n heptio-sonobuoy delete pod sonobuoy` and re-run the `kubectl apply -f ./examples/quickstart`, does it work for you then?

**Comment by evaldasou** [comment]
thanks a lot @kensimon ! it worked this time after I have deleted pod!

**Comment by jamesbuckett** [comment]
I am still getting this issue : `Configured plugin systemd_logs does not exist`

I tried the work around as described above but no joy after two attempts.

Environment is : 
```
heptio-sonobuoy Pods
No resources found, use --show-all to see completed objects.

heptio-sonobuoy Services
NAME              CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
sonobuoy-master   10.31.243.189   <none>        8080/TCP   57m

Nodes
NAME                                             STATUS    AGE       VERSION   EXTERNAL-IP      OS-IMAGE                             KERNEL-VERSION
gke-heptio-sonobuoy-default-pool-d1297397-7ztn   Ready     1h        v1.6.7    35.198.193.241   Container-Optimized OS from Google   4.4.52+
gke-heptio-sonobuoy-default-pool-d1297397-cwkf   Ready     1h        v1.6.7    35.198.210.119   Container-Optimized OS from Google   4.4.52+
gke-heptio-sonobuoy-default-pool-d1297397-k001   Ready     1h        v1.6.7    35.198.215.38    Container-Optimized OS from Google   4.4.52+
```

Error is :
```
 jamesb@Surface:~/sonobuoy$ kubectl logs -f sonobuoy --namespace=heptio-sonobuoy
I0818 08:09:05.243769       1 loader.go:47] Scanning plugins in ./plugins.d (pwd: /)
I0818 08:09:05.243991       1 loader.go:47] Scanning plugins in /etc/sonobuoy/plugins.d (pwd: /)
I0818 08:09:05.244059       1 loader.go:47] Scanning plugins in ~/sonobuoy/plugins.d (pwd: /)
E0818 08:09:05.244103       1 master.go:50] Configured plugin systemd_logs does not exist
```

**Comment by timothysc** [comment]
reopening, @kensimon could you please verify.

**Comment by chuckha** [comment]
I've seen this when I have an invalid configuration in my plugin. @jamesbuckett If you provide your plugin we can at least rule that out.

**Comment by gamename** [comment]
I'm seeing this issue as well.  It happens about every third time I start a test.

**Comment by timothysc** [comment]
Thx for reporting, I'll start investigating early this week.

**Comment by timothysc** [comment]
So I'll add more verbose logging to try and help diagnose, but I wonder if there was a config map mount race that exists in 1.6?

**Comment by timothysc** [comment]
So I'm traipsing through the control flow and nothing stands out atm.  I'll have a PR to add more logging so we should get better visibility when the condition occurs, but I'm still leaning that this is a race condition on config map mounting.

**Comment by timothysc** [comment]
I'm going to untag this release and wait on feedback from testing.  I've added more logging so if the issue occurs again we should have a better bead on whether it's a race condition or not.
