### ISSUE TITLE
Cleanup and reduce sonobuoy.interface to not pass config/interface all over.

### ISSUE THREAD

**Issue by timothysc** [heptio/sonobuoy#300]
We should modify the sonobuoy client to only use the kuberenetes.iterface as that is the normal mode of operation, if we need lower level structs there are mutation functions we should use.  

This makes it much more consistent with other tools, and a requirement for integration.

**Comment by liztio** [comment]
This, sadly, turns out not to be possible.

You can easily obtain a rest.Client from a kubernetes.Client. However, both DynamicClient and SPDY RoundTripper require a rest.Config, and creating a rest.Client does not preserve this config.

**Comment by timothysc** [comment]
reduxing under, func NewSonobuoyClient(restConfig *rest.Config)
