### ISSUE TITLE
sonobuoy logs behavior

### ISSUE THREAD

**Issue by timothysc** [heptio/sonobuoy#301]
Sonobuoy logs are great, but there are a couple of behavioral changes I think need to be there. 

1. We should add an optional selection argument that enables the user to get just the data they want or perhaps even default the plugin to e2e... --plugin=e2e 

2. -f should tail the whole output of all pods, or defer to the --plugin= behavior.

**Comment by chuckha** [comment]
Moving this to 0.12 for the --plugin behavior

**Comment by johnSchnake** [comment]
One of my biggest frustrations with the logs is if you start tailing too soon the e2e pod wont have started yet so you dont get any of those logs. Even when following logs, the list of pods to follow is already set and you wont ever get those logs. When you stop the command and rerun you will then start to get the new pod logs.

It would be nice as pods come up we also get their logs without having to renew the command. This is especially important if you have a short test (like the running in `--mode quick`) where the e2e pod isn't around for long.

**Comment by johnSchnake** [comment]
Created issues detailing the 2 remaining issues from this ticket; closing this one.
