### ISSUE TITLE
Generalize plugin results reporting

### ISSUE THREAD

**Issue by chuckha** [heptio/sonobuoy#306]
The first pass of e2e is only solving for the common case of conformance e2e tests.

We would ideally like to reuse this command to fit any e2e-esque set of tests (such as heptio's extended e2e tests).

**Comment by johnSchnake** [comment]
I think the answer is to generalize and rebrand the command in general.

I'm going to be writing up a design doc for this but it seems like a really good place for improvement this cycle.

Right now my thinking is along the lines of wanting to get out status codes and 1-2 different types of results parsing (e.g. junit). This would probably be done via some extra data the plugin can drop to help sonobuoy know where a certain piece of information is. TBD.
