### ISSUE TITLE
Consistency on commands, caps, --flags and defaults.

### ISSUE THREAD

**Issue by timothysc** [heptio/sonobuoy#309]
The look and feel for the commands needs some TLC 

for example mode [conformance] 
e2e-focus [Conformance] 
... 

/cc @chuckha @liztio

**Comment by liztio** [comment]
I don't think there's a good way to resolve that particular issue. It makes sense for modes to be lowercase, because that sort of argument usually is, but e2e-focus has to be capitalised because that's how Ginko works.

**Comment by liztio** [comment]
Prior art for capitalisation: 

`  -o, --output='': Output format. One of:
json|yaml|wide|name|custom-columns=...|custom-columns-file=...|go-template=...|go-template-file=...|jsonpath=...|jsonpath-file=...
See custom columns [http://kubernetes.io/docs/user-guide/kubectl-overview/#custom-columns], golang template
[http://golang.org/pkg/text/template/#pkg-overview] and jsonpath template
[http://kubernetes.io/docs/user-guide/jsonpath].`

Counter examples:
`--session-affinity='': If non-empty, set the session affinity for the service to this; legal values: 'None',
'ClientIP'`

**Comment by timothysc** [comment]
the defaults presented could be Cammel Cased but internally everything is tolower'd.
