### ISSUE TITLE
Duplication of code across commands (run, e2e, gen, (others?))

### ISSUE THREAD

**Issue by chuckha** [heptio/sonobuoy#312]
There might be a better way to share code than copy and paste. Consider DRYing this up a bit if there is a good abstraction

**Comment by johnSchnake** [comment]
Lack of clear objectives/measurable goal I am going to close this. We would obviously love to de-dup some code but I dont think it warrants an issue itself. As we come up with measurable goals we will open smaller, targeted tickets.
