### ISSUE TITLE
Default template for conformance-lite for kubeadm clusters.

### ISSUE THREAD

**Issue by timothysc** [heptio/sonobuoy#32]
Per discussion on sig-cluster-lifecycle:  Standard conformance runs can take quite a while and for a number of kubeadm deploys we would like a quick validation that all is running well.  

/cc @luxas @roberthbailey

**Comment by luxas** [comment]
I'd personally be happy to reference this in the same way we do for Network Plugins (one tab per solution), where Weave's Sock Shop is one of them (has been there from the beginning), and this is an other way to verify (one `kubectl apply` command only)

**Comment by timothysc** [comment]
@luxas definitely agree, I think the broader question is what are the set of tests folks think makes the most sense for a quick smoke test.

**Comment by roberthbailey** [comment]
@williamdenniss who's involved in conformance testing

**Comment by timothysc** [comment]
Closing in favor of #76
