### ISSUE TITLE
Return code for unknown command is incorrect

### ISSUE THREAD

**Issue by guillaumerose** [heptio/sonobuoy#327]
`sonobuoy cp .` returns now an error since the command is replaced by `retrieve` but the code returned is 0 (should be 1 or something else).

```
$ go get -u github.com/heptio/sonobuoy
$ sonobuoy cp .
Error: unknown command "cp" for "sonobuoy"
Run 'sonobuoy --help' for usage.
$ echo $?
0
```

Thanks

**Comment by timothysc** [comment]
That's a bug, thank you for reporting.  

I'll try to get that fixed soon.
