### ISSUE TITLE
Document structure of results tarball

### ISSUE THREAD

**Issue by chuckha** [heptio/sonobuoy#33]
We should have strict rules about how data in a results tarball is arranged, so that ingesting sonobuoy results can be done in an automated way without lots of if statements and special casing.

We can start with simple documentation, outlining the paths within the tarball and what should be contained in them, etc.

**Comment by abiogenesis-now** [comment]
This is pretty much addressed by https://github.com/heptio/sonobuoy/pull/43 (note that some sections are still proposals, but it's a decent overview)
