### ISSUE TITLE
Be consistent about what we pass into the Interface methods

### ISSUE THREAD

**Issue by chuckha** [heptio/sonobuoy#337]
GetStatus takes a namespace but it should take a StatusConfig

**Comment by chuckha** [comment]
Looks like this got fixed.

**Comment by liztio** [comment]
https://github.com/heptio/sonobuoy/blob/master/pkg/client/interfaces.go#L131 @chuckha doesn't look like it to me?

**Comment by chuckha** [comment]
ahhh yeah, whoops, good call
