### ISSUE TITLE
v0.11.0 - Testing punchlist 

### ISSUE THREAD

**Issue by timothysc** [heptio/sonobuoy#341]
- [x] Bare Metal Tests 
    - [x] Ubunut 16.04 
    - [x] CentOS 7.4 
- [x] Cloud Provider Hosted Services 
   - [x] AKS 
   - [x] GKE 
- [x] Cloud provider tests
  - [x] aws quickstart 
  - [x] gcp kubeadm 
  - [x] azure kubeadm 
- [ ] kubespray - community 
- [ ] kops - community

/cc @chuckha @rbankston @liztio

**Comment by chuckha** [comment]
I'd also add managed kubernetes in azure (in addition to a kubeadm one)

**Comment by chuckha** [comment]
We don't need to run conformance on everything, not until 1.10 i think, this is a test to make sure the sonobuoy command line can talk to each of these clusters types, is that right?

**Comment by krisdock** [comment]
Ran from my MacBook Pro against a bare metal CentOS 7.4 cluster. Everything seems to work except the `retrieve` command:

```
kris-mbp:~ kris$ sonobuoy status
PLUGIN		STATUS		COUNT
e2e		complete	1
systemd_logs	complete	3

Sonobuoy has completed. Use `sonobuoy retrieve` to get results.
```
```
kris-mbp:~ kris$ sonobuoy retrieve .
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xd8 pc=0x1bdc65b]

goroutine 1 [running]:
github.com/heptio/sonobuoy/pkg/client.(*SonobuoyClient).RetrieveResults(0xc42053dcf0, 0xc42053dcd0, 0x0, 0x0, 0xc42053dd18, 0x1be8cf3)
	/Users/kris/Workspace/Go/src/github.com/heptio/sonobuoy/pkg/client/retrieve.go:38 +0x3b
github.com/heptio/sonobuoy/cmd/sonobuoy/app.retrieveResults(0xc4202138c0, 0xc420117c10, 0x1, 0x1)
	/Users/kris/Workspace/Go/src/github.com/heptio/sonobuoy/cmd/sonobuoy/app/retrieve.go:74 +0x1d0
github.com/heptio/sonobuoy/vendor/github.com/spf13/cobra.(*Command).execute(0xc4202138c0, 0xc420117be0, 0x1, 0x1, 0xc4202138c0, 0xc420117be0)
	/Users/kris/Workspace/Go/src/github.com/heptio/sonobuoy/vendor/github.com/spf13/cobra/command.go:702 +0x2bd
github.com/heptio/sonobuoy/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x266b220, 0x1c, 0x0, 0x0)
	/Users/kris/Workspace/Go/src/github.com/heptio/sonobuoy/vendor/github.com/spf13/cobra/command.go:783 +0x349
github.com/heptio/sonobuoy/vendor/github.com/spf13/cobra.(*Command).Execute(0x266b220, 0xc4200001a0, 0xc4200001a0)
	/Users/kris/Workspace/Go/src/github.com/heptio/sonobuoy/vendor/github.com/spf13/cobra/command.go:736 +0x2b
main.main()
	/Users/kris/Workspace/Go/src/github.com/heptio/sonobuoy/main.go:27 +0x2d
```

**Comment by chuckha** [comment]
@krisdock thanks for the report, we just fixed that in master! Please pull. So sorry about that!

**Comment by rbankston** [comment]
Ran on a 16.04 cluster. Minus having to upgrade GO to 1.8 everything worked as expected.

```
user@banksto11:~/go/src/github.com/heptio/sonobuoy$ ./main status
PLUGIN		NODE				STATUS
e2e						running
systemd_logs	banksto11.mylabserver.com	complete
systemd_logs	banksto12.mylabserver.com	complete
systemd_logs	banksto13.mylabserver.com	running

Sonobuoy is still running. Runs can take up to 60 minutes.
```

This is the second run after verifying that sonobuoy delete worked as expected.

**Comment by chuckha** [comment]
everything's good on AKS!

**Comment by chuckha** [comment]
EKS only supports v1.7.10 so let's cross that off this list.

**Comment by chuckha** [comment]
quickstart is all good. Spun up a fresh cluster off master:

Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T11:55:20Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

**Comment by liztio** [comment]
```
 $ sonobuoy e2e 201803091831_sonobuoy_cdb80ea4-853a-4280-8f4a-a88f6d72b7ca.tar.gz
failed tests
```

GKE looks good!

**Comment by liztio** [comment]
GCP + Kubeadm tested too. sonobuoy run, status, logs, retrieve, e2e, delete.

**Comment by liztio** [comment]
Azure + Kubeadm: sonobuoy run, status, logs, retrieve, e2e, delete
