### ISSUE TITLE
Refactor Error Handling

### ISSUE THREAD

**Issue by chuckha** [heptio/sonobuoy#35]
Original error handling was made around gathering the details and continuing on.  The problem is they are spewed at the end of the run which make it more difficult to debug.  

I no longer think we need to propagate errors back to the root, but simply indicate pass fail and log at the location of the error.  

I do not think we need to fix this for the OSS release, but can do it afterwards.

**Comment by chuckha** [comment]
@kensimon did #50 close this?

**Comment by timothysc** [comment]
Let's leave it open for now to eval the behavior.

**Comment by kensimon** [comment]
I think we can re-open (or open new issues) if there's any issues with the new behavior... for now we've accomplished the stated goals for this issue
