### ISSUE TITLE
 GCP needs admin permissions before running

### ISSUE THREAD

**Issue by liztio** [heptio/sonobuoy#351]
If I try to run Sonobuoy on a new GKE cluster, it fails with the following error:

```
Error from server (Forbidden): error when creating "/dev/fd/11": clusterroles.rbac.authorization.k8s.io "sonobuoy-serviceaccount" is forbidden: attempt to grant extra privileges: [PolicyRule{Resources:["*"], APIGroups:["*"], Verbs:["*"]}] user=&{liz@heptio.com  [system:authenticated] map[authenticator:[GKE]]} ownerrules=[PolicyRule{Resources:["selfsubjectaccessreviews"], APIGroups:["authorization.k8s.io"], Verbs:["create"]} PolicyRule{NonResourceURLs:["/api" "/api/*" "/apis" "/apis/*" "/healthz" "/swagger-2.0.0.pb-v1" "/swagger.json" "/swaggerapi" "/swaggerapi/*" "/version"], Verbs:["get"]}] ruleResolutionErrors=[]
zsh: exit 1     kubectl apply -f
```

The solution is to create an admin role for the user:

`kubectl create clusterrolebinding your-user-cluster-admin-binding --clusterrole=cluster-admin --user=your.google.cloud.email@example.org` 

We should document this, or add a preflight check, or otherwise expose it to the user

**Comment by Bradamant3** [comment]
@liz do you think adding this issue to the readme is sufficient?

**Comment by liztio** [comment]
For now I think that should be good!
