### ISSUE TITLE
Allow plugin configuration to be set from sonobuoy config

### ISSUE THREAD

**Issue by chuckha** [heptio/sonobuoy#37]
Currently the E2E tests (like which tests to run, etc) are driven by environment variables, and in order to change them you  have to change the plugin *definition* (./plugins.d/e2e.yaml).

It'd be nice to let the e2e.yaml plugin definition remain constant, and for plugin behavior to be configurable from the main sonobuoy.conf file, since it's specific from run-to-run.

This was mostly the idea from the beginning, but it doesn't currently work.

Example sonobuoy config:

```
{
  ...
  "plugins": {
    {
      "name": "e2e",
      "config": {
        "focus": "foo",
        "more": "config",
        ...
      }
  }
}
```

And the `plugins[...].config` section would be available in "/etc/sonobuoy/plugin-config.json" or similar on the worker side.

**Comment by timothysc** [comment]
This is nice to have, but not important atm.

**Comment by timothysc** [comment]
closing in preference of ksonnet-i-fying the configs.
