### ISSUE TITLE
Drop the concept of "Expected Results", have each plugin block to completion

### ISSUE THREAD

**Issue by chuckha** [heptio/sonobuoy#38]
Plugins' "ExpectedResults" model needs a bit of an overhaul, we should just have the Monitor() function of each plugin signal when the results have all come in.

For that matter, if we want to go that far we can drop Monitor() altogether and just have the Run() function return when the plugin is done.

One thing to consider here is for DaemonSets: since they get continually relaunched (restartPolicy must be "Always"), it's difficult to know a DaemonSet has finished without asking the aggregator if the result has been seen. So we should rely on any given DaemonSet plugin to use readiness probes to indicate that it is finished.  (And the plugin driver would just wait for all pods to be "ready", then finish.)

**Comment by chuckha** [comment]
migrated

**Comment by timothysc** [comment]
Enqueue to eval, may punt out of this release.

**Comment by timothysc** [comment]
@chuckha Does this even exist anymore.  I know ken had removed "the expected results".

**Comment by timothysc** [comment]
closing in preference for grpc master worker protocol.
