### ISSUE TITLE
BUG: sonobuoy retrieve (tar output) 

### ISSUE THREAD

**Issue by timothysc** [heptio/sonobuoy#382]
**This a BUG REPORT**:
When sonobuoy successfully retrieves a tarball it emits a tar message that can be confusing to the user.

**What happened**:
Successful retrieve emits: `\tar: removing leading '/' from member names`

**What you expected to happen**:
`wrote 201803152108_sonobuoy_848f5c42-d3a4-4db7-ae79-e3ce84b2dee4.tar.gz`
or normal exit

**How to reproduce it (as minimally and precisely as possible)**:
```
$ sonobuoy run -m Quick
$ sonobuoy status
... wait for completion ... 
$ sonobuoy retrieve .
```

**Environment**:
sonobuoy-v0.11.0-rc.1

**Comment by chuckha** [comment]
for later reference https://github.com/kubernetes/kubernetes/issues/58692

**Comment by chuckha** [comment]
also https://stackoverflow.com/questions/25929315/tar-removing-leading-from-member-names

**Comment by johnSchnake** [comment]
I think this was fixed by https://github.com/heptio/sonobuoy/commit/3d46d239f3d8fa2ebe8af17d75c0fb131f9c8017#diff-4c7b4efff320a6867615334e6db12341R61 ; stderr isn't wired up there and just the error is returned as necessary.

Unable to repro now; closing.
