### ISSUE TITLE
Rename Job and Daemonset to Scope: Node or Cluster

### ISSUE THREAD

**Issue by liztio** [heptio/sonobuoy#388]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Feature Request

**What happened**:

Currently Sonobuoy plugins describe themselves as `DaemonSet` or `Job`. This unnecessarily exposes implementation details to users, while also obscuring the actual function of that 

**What you expected to happen**:

Instead of specifying a Driver like we do now, it would make more sense for the use to declare where they want their tests to run. We're looking at replacing the underlying Daemonset implementation already ( #255 ), so this would make that less confusing.

**How to reproduce it (as minimally and precisely as possible)**:

I propose 
`Scope: Node` or `Scope: Cluster` for jobs that want to run on every node (systemd logs) or just once per cluster (e2e). Future scopes could include `Namespace` or by taint or something.

**Comment by chuckha** [comment]
💯

**Comment by johnSchnake** [comment]
For now I think we are going to leave this naming as-is. I don't think this exposes an implementation detail that is unclear or secret in any way; the user is wanting to test a k8s cluster and we are just using k8s nomenclature (which presents a clear world-view to the user and they can predict what will happen when they run a job/daemonset plugin)
