### ISSUE TITLE
Errors in `sonobuoy logs -f`

### ISSUE THREAD

**Issue by chuckha** [heptio/sonobuoy#393]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Bug report
**What happened**:
I ran `sonobuoy logs -f` and there were a bunch of RPC errors when containers shut down
**What you expected to happen**:
I didn't expect to see RPC errors
**How to reproduce it (as minimally and precisely as possible)**:
As far as I can tell, run just the systemd_logs plugin and then run `sonobuoy logs -f` after it starts and wait for it to finish.
**Anything else we need to know?**:
It might be a network thing as I discovered this on airplane wifi?

**Environment**:
ran off code from pr #392 

- Sonobuoy tarball (which contains * below)

- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):

**Comment by johnSchnake** [comment]
@chuckha I'm not sure if you still see this or not; I havent come across them. If you see them let me know and reopen this. Closing due to age otherwise.
