### ISSUE TITLE
more information link does not work

### ISSUE THREAD

**Issue by caarlos0** [heptio/sonobuoy#400]
**Is this a BUG REPORT or FEATURE REQUEST?**:

bug on docs (?)

**What happened**:

The readme states:

> More information
> [The documentation](https://heptio.github.io/sonobuoy/) provides detailed information about the conformance tests, > plugins, and snapshots.

But the URL https://heptio.github.io/sonobuoy/ is a 404.

**What you expected to happen**:

Open a valid page.

**How to reproduce it (as minimally and precisely as possible)**:

Open the README and click on the link.

**Comment by timothysc** [comment]
this is fixed... closing.
