### ISSUE TITLE
RFE: Automatically publish docs site on tag annotation.

### ISSUE THREAD

**Issue by timothysc** [heptio/sonobuoy#406]
**Is this a FEATURE REQUEST**:
Automatically publish the new doc site update as part of the release process. 

**What happened**:
Doc site was not updated and lag'd the release.

**What you expected to happen**:
https://github.com/heptio/sonobuoy/blob/master/docs/release.md should trigger automation to update the docs.  

**How to reproduce it (as minimally and precisely as possible)**:
Follow the release process with docs changes and they will not be up to date.  The process is asynchronous and manual.  

**Anything else we need to know?**:
As a temporary work around we can update the release process, but I would ideally like to make it turnkey such that the site is automatically generated.  

/cc @kstewart

**Comment by timothysc** [comment]
@Bradamant3 Could you please PR the temporary workflow update to the release process doc so any of the developers can publish on a release. 

/cc @chuckha

**Comment by stevesloka** [comment]
@rosskukulinski are we going to maintain a separate "docs" site going forward?

**Comment by rosskukulinski** [comment]
@stevesloka we have budget to create a sonobuoy project site (e.g. via sonobuoy.io) and it can include docs-as-code.  Funding would likely include creation of the site & theme, wiring up docs-as-code, and migrating existing docs over.  On-going maintenance of the docs would be done by the sonobuoy development team

**Comment by stevesloka** [comment]
Thanks for the clarification @rosskukulinski! I'm going to close this, for now, we'll build this functionality into the new site.
