### ISSUE TITLE
Make 'sonobuoy retrieve' cli command aware if tarball is available or not

### ISSUE THREAD

**Issue by mwieczorek** [heptio/sonobuoy#407]
**Is this a BUG REPORT or FEATURE REQUEST?**:
FEATURE REQUEST

**What happened**:
I prepared script to run sonobuoy and gather results. Basically script has steps:
1. `sonobuoy run`
2. in a loop wait for all plugins to complete 
3. `sonobuoy retrieve`
4. `tar xzf *.tar.gz`

Last step failed because there is no tarball after retrieve, just a folder (with UID as name). Sonobuoy returned 0 exit code.

**What you expected to happen**:
It would be better UX if sonobuoy cli retrieve would return some errorCodes, f.e.:
0 - ok, tarball downloaded
1 - error, cannot retrieve the tarball, not recoverable error
2 (or other number) - tarball not ready, you can try again later

I think it would make scripting easier (now I can just check if there's a tarball in specified folder)

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Sonobuoy tarball (which contains * below)
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):

**Comment by johnSchnake** [comment]
I currently have a very similar problem; I'm thinking the cause is that I'm trying to get the tarball just slightly before its ready (sonobuoy status says it is done with tests) but sometimes I get the tarball and sometimes I get the directory. Frustrating behavior, even if not technically a bug.

**Comment by mwieczorek** [comment]
@johnSchnake I was in the same situation - that's why I created this issue.
In the meantime if I want to automate sonobuoy scan I just loop and check if I got tar of not.
