### ISSUE TITLE
Update Release Punchlist with additional steps

### ISSUE THREAD

**Issue by liztio** [heptio/sonobuoy#409]
Based on our Retrospective, we should add the following:

* Add an item to confirm all needed parties (engineers, docs writer) are present before releases. This means no Saturday releases, no releases while blocking parties are on PTO
* Add a verification step to release. Check that docs work, Sonobuoy release actually can test a cluster, and anything
* Add a note to the punchlist that it is okay to miss a deadline if all parties or components aren't in place.
* Document all steps involved to push a new release

**Comment by timothysc** [comment]
xref #406
