### ISSUE TITLE
Scanner Results Link to systemd.yaml Broken

### ISSUE THREAD

**Issue by nreisbeck** [heptio/sonobuoy#418]
**Is this a BUG REPORT or FEATURE REQUEST?**: Bug Report

**What happened**: Results page link to the `systemd.yaml` file no longer leads to the the correct repo folder on GitHub.

**What you expected to happen**: A non-404 page.

**How to reproduce it (as minimally and precisely as possible)**: Run Sonobuoy test, once complete the click the link to the `systemd.yaml` file at the top.

**Anything else we need to know?**:

![screen shot 2018-04-20 at 3 39 49 pm](https://user-images.githubusercontent.com/10735102/39076698-d0f41e00-44b1-11e8-8f39-e5030876712d.png)

#252 moved `systemd.yaml` to `examples/plugins.d/systemd_logs.yaml`.

**Environment**:
- Sonobuoy tarball (which contains * below)
- Kubernetes version (use `kubectl version`): n/a
- Cloud provider or hardware configuration: n/a
- OS (e.g. from /etc/os-release): n/a
- Kernel (e.g. `uname -a`): n/a

**Comment by johnSchnake** [comment]
Closing; the Scanner is no longer supported at this time. Thank you for your interest in that project. If you have other Sonobuoy questions or issues please feel free to reach out.
