### ISSUE TITLE
Problem when using sonobuoy in non-default namespace

### ISSUE THREAD

**Issue by ghost** [heptio/sonobuoy#420]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT

**What happened**:
Multiple errors running tests; logs contain references to different namespace than expected.

**What you expected to happen**:
Run to work in namespace X just as well as in heptio-sonobuoy (default).

**How to reproduce it (as minimally and precisely as possible)**:
sonobuoy run --e2e-focus foo -n nondefault
watch sonobuoy status

**Anything else we need to know?**:
I made my own images to add some extra debug lines:
```
./sonobuoy run --e2e-focus bad -n foo --sonobuoy-image docker.io/schnake/sonobuoy

// Below you can see the CLI setting the namespace to foo
cfg for run: &{{0xc42029e3c0 0xc420100000 docker.io/schnake/sonobuoy foo true Always gcr.io/heptio-images/kube-conformance:latest}}
...
// These plugins (a base object and an updater) both have their namespace set as the default still.
secretname?:  sonobuoy-plugin-e2e-fb531a326073467a
tls plugin ns: heptio-sonobuoy
time="2018-04-26T18:19:32Z" level=error msg="error running plugins: error running plugin e2e: couldn't create TLS secret for job plugin e2e: namespaces \"heptio-sonobuoy\" not found"
...
time="2018-04-26T18:19:52Z" level=info msg="couldn't annotate sonobuoy pod" error="couldn't patch pod annotation (pod: sonobuoy namespace: heptio-sonobuoy): pods \"sonobuoy\" not found"
time="2018-04-26T18:20:02Z" level=info msg="couldn't annotate sonobuoy pod" error="couldn't patch pod annotation (pod: sonobuoy namespace: heptio-sonobuoy): pods \"sonobuoy\" not found"
time="2018-04-26T18:20:07Z" level=info msg="couldn't annotate sonobuoy pod" error="couldn't patch pod annotation (pod: sonobuoy namespace: heptio-sonobuoy): pods \"sonobuoy\" not found"
...
```

If I just try to run status I also get errors because of the inability of sonobuoy to annotate the aggregation pod:
```
ERRO[0000] error attempting to run sonobuoy: missing status annotation "sonobuoy.hept.io/status"
```

**Environment**:
- Sonobuoy tarball (which contains * below)
From master at 857d1fbb3b94a6e37110ee17d548b83724d21bc4 with a few debug lines added by me after seeing the problem.

- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.6", GitCommit:"4bc5e7f9a6c25dc4c03d4d656f2cefd21540e28c", GitTreeState:"clean", BuildDate:"2017-09-15T08:51:21Z", GoVersion:"go1.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"", Minor:"", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"", BuildDate:"2018-03-28T08:48:47Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
VSphere
- OS (e.g. from /etc/os-release):
```
NAME=Fedora
VERSION="24 (Twenty Four)"
ID=fedora
VERSION_ID=24
PRETTY_NAME="Fedora 24 (Twenty Four)"
```
- Kernel (e.g. `uname -a`):
```
Linux nfs-provisioner-5dc4f88cc4-g7cg2 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by jeffb4** [comment]
I ran a `sonobuoy gen -n testns` and it looks like `data/config.json` in `ConfigMap/sonobuoy-config-cm` specifies a namespace of `heptio-sonobuoy` (that is, it is not properly overridden based on the command line option).

We're launching directly from the resource YAML, and have a use-case to test with a difference namespace, I'll try to update this issue based on it.
