### ISSUE TITLE
Allow passing a context to sonobuoy subcommands

### ISSUE THREAD

**Issue by ceridwen** [heptio/sonobuoy#421]
**Is this a BUG REPORT or FEATURE REQUEST?**:

Feature request

**What happened**:

I'm executing sonobuoy from a Jenkins server with a kubeconfig set up as Jenkins credentials to avoid committing all the authentication information to a repository.  This setup runs against multiple clusters, and with previous version of sonobuoy I've been passing a context to kubectl to access the different clusters:

```
kubectl --kubeconfig="$KUBECONFIG" --context="$CONTEXT" examples/conformance.yaml
```
sonobuoy now has its own command line interface but only accepts a kubeconfig argument, making my previous setup not work, and workarounds involving multiple kubeconfig files are painful.  If `sonobuoy run` and similar commands accepted a context option, I could use them instead of kubectl.

**Comment by johnSchnake** [comment]
This has been around for a while without much conversation and so I just wanted to try and start the discussion. It seems like the two main options are either:
 1) Setting the context at the start of your CI run (seems on the surface that that is all you would have to do)
 2) Using `kubectl config --kubeconfig=<cfg> view --minify` to "generate" a small kubeconfig you can use which _only_ has the one context.

What are the current problems with those that makes the workarounds painful? I'm not personally familiar with some of the nuances of that flow perhaps.

**Comment by johnSchnake** [comment]
ping @ceridwen

**Comment by ceridwen** [comment]
I don't think I understand how `--minify` would help, it only operates on the *current* context, so if you have a kubeconfig with a context set that will always generate the same output.  Do you mean `--minify` with `--use-context`?  I don't know how those flags interact.  (If `--minify` even existed when I posted this issue, I wasn't aware of it.)  Even then, it's a question of writing a script that uses kubectl to write a new config file to disk for every run, which then ought to be logged to keep track of the actual settings the tests were run under.  This is more complicated than simply passing a context argument, and more vulnerable to changes in the kubectl API.

**Comment by johnSchnake** [comment]
Breadcrumb for implementation: https://github.com/kubernetes/client-go/issues/192
