### ISSUE TITLE
Allow 'plugin' specifications to reference 'imagePullSecrets'.

### ISSUE THREAD

**Issue by templecloud** [heptio/sonobuoy#424]
**FEATURE REQUEST**: 

Allow 'plugin' specifications to reference 'imagePullSecrets' to allow test container to be pulled from secured repositories.

**What happened**: 

We were using the sonobuoy plugin mechanism to run our own test images alongside the E2E tests against our K8s clusters. The host registry had to be made private, so, now requires docker credentials in order to pull down the image.

**What you expected to happen**:

We should be able to specify 'imagePullSecrets' in our test plugin. If the required secret is available in the cluster, then it should be able to use them to pull down the test container image.

**How to reproduce it (as minimally and precisely as possible)**:

Take any plugin test image and store it in a repository that requires credentials to pull it. The test pod will report an image pull error when trying to run the tests.

**Anything else we need to know?**:

**Environment**:
- Sonobuoy tarball (which contains * below)
v0.11.1
- Kubernetes version (use `kubectl version`):
```
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.5", GitCommit:"f01a2bf98249a4db383560443a59bed0c13575df", GitTreeState:"clean", BuildDate:"2018-03-19T15:50:45Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
n/a
- OS (e.g. from /etc/os-release):
n/a
- Kernel (e.g. `uname -a`):
n/a

**Comment by rajibmitra** [comment]
can I work on this ?

**Comment by chuckha** [comment]
@rajibmitra sure, please assign PRs to me
