### ISSUE TITLE
Improve docs for CNCF conformance submission

### ISSUE THREAD

**Issue by chuckha** [heptio/sonobuoy#435]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Feature Request

It would be pretty handy to have a command to submit a cncf pull request or at least get one far along in [the process](https://github.com/cncf/k8s-conformance/blob/master/instructions.md).

This would end up being part of the post-release process for heptios aws-quickstart.

Even something that took results and bundled up the right stuff for the pull request could be handy

**Comment by openstacker** [comment]
@chuckha As we discussed on slack, I would like to see an API endpoint exposed by the sonobuoy service/pod, so that as a user, I can just call the API like "curl http://192.168.100.100:8080/get_test_result" to get the e2e test result instead of calling "kubectl cp" command.

**Comment by johnSchnake** [comment]
The above mention of the API endpoint seems outdated since we have the `sonobuoy retrieve` command now which simplifies pulling the tarball.

**Comment by johnSchnake** [comment]
Having just done this IMO this seems a bit overkill. I'd be tempted to add a section in the docs for it, but I feel like it is just rehashing what should be upstream. If the upstream docs for cncf conformance are not sufficient we could try and put a PR up that would clarify/script around how to do it.

It isnt hard; get the repo, run sonobuoy, grab a few files from the tar, then add your own documentation and put up a PR.

**Comment by johnSchnake** [comment]
@emuetzel what did you think of this?

**Comment by emuetzel** [comment]
Without being deep yet in the user experience, this seems like a reasonable approach. Perhaps try to get this in upstream docs, and in the meantime add a section to the Sonobuoy docs

**Comment by johnSchnake** [comment]
Opened https://github.com/cncf/k8s-conformance/pull/555 upstream; adjusted a few of the sonobuoy commands and also scripted the steps reviewed in that doc.

**Comment by johnSchnake** [comment]
Merged the upstream PR mentioned. Going to close this as done.
