### ISSUE TITLE
Allow configuring which busybox image to pull

### ISSUE THREAD

**Issue by tuminoid** [heptio/sonobuoy#439]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Feature request.

**What happened**:
e2e tests fail as Docker cannot pull `docker.io/library/busybox`, since we have `docker.io` blocked in Docker. We're using RHEL's Docker.

**What you expected to happen**:
I can tell Sonobuoy where the `busybox` image is at via some configuration value.

Using RHEL's Docker's default registry feature won't work, as Kubernetes autocompletes `busybox` -> `docker.io/library/busybox:latest` automatically, instead of leaving the pulling to Docker daemon, which would know where to pull it from.

**How to reproduce it (as minimally and precisely as possible)**:
Block `docker.io` from Docker and try run conformance tests, and fail miserably.

**Anything else we need to know?**:
Nope.

**Environment**:
- Sonobuoy tarball (which contains * below)
- Kubernetes version (use `kubectl version`): 1.9.6
- Cloud provider or hardware configuration: anywhere
- OS (e.g. from /etc/os-release): RHEL 7.5 Maipo
- Kernel (e.g. `uname -a`): 3.10.0-862.2.3

**Comment by johnSchnake** [comment]
This is actually solved by #160 as well. Note that this requires clusters with version >= 1.13 because of the Kubernetes test framework logic required.
