### ISSUE TITLE
RFE: Autodetect kubernetes version and set kube-conformance image accordingly

### ISSUE THREAD

**Issue by jhamilton1** [heptio/sonobuoy#444]
**Is this a BUG REPORT or FEATURE REQUEST?**:
FEATURE REQUEST

**What happened**:
I run Sonobuoy Scanner tool and Sonobuoy CLI on a k8s v1.8.5, and v1.8.13 cluster. The scans all result in the same failed e2e conformance tests verified by viewing the e2e.log contained inside the tarball.

**What you expected to happen**:
All of the e2e conformance tests to pass if the cluster is v1.8+   Would like for the Sonobuoy scanner to auto-detect what version of kube-conformance container that it needs to run.

**How to reproduce it (as minimally and precisely as possible)**:
NAME=test-cluster.k8s.local
kops create cluster \
    --node-count 3 \
    --zones us-east-1a,us-east-1b,us-east-1c \
    --master-zones us-east-1a,us-east-1b,us-east-1c \
    --node-size t2.medium \
    --master-size t2.medium \
    --networking weave \
    --image 383156758163/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-05-27 \
    --kubernetes-version 1.8.5 \
    ${NAME}

Run the Sonobuoy Scanner tool (browser-based) and save logs.
Run the Sonobuoy CLI (./sonobuoy run) and save logs.

**Anything else we need to know?**:
The Problem persisted when upgrading from k8s v.1.8.5 to 1.8.13 patch. However, after upgrading to k8s v1.9.6, the e2e conformance tests all succeed.
The customer stated that the scans did not fail in the past.

**Impact on the customer**:
The customer was not sure if there was an actual problem in the cluster.  

**ZenDesk ticket ID**:  ticket 203

**ZenDesk ticket priority/urgency**: Normal

**Environment**:
- Sonobuoy tarball (which contains * below)
- Kubernetes version (use `kubectl version`): 1.8.5
- Cloud provider or hardware configuration: AWS
- OS (e.g. from /etc/os-release): Debian GNU/Linux 8 (jessie)
- Kernel (e.g. `uname -a`): 4.4.133-k8s
[201806181429_sonobuoy_14d33a51-d436-4e5c-a9e7-96aeba55354f.tar.gz](https://github.com/heptio/sonobuoy/files/2115621/201806181429_sonobuoy_14d33a51-d436-4e5c-a9e7-96aeba55354f.tar.gz)

**Comment by timothysc** [comment]
@jhamilton1  - do you have tarballs of the other runs that show the same tests failing?

**Comment by jhamilton1** [comment]
I have another tarball as well as the e2e.logs from a couple of runs.
[e2e-1.8.6.log](https://github.com/heptio/sonobuoy/files/2116848/e2e-1.8.6.log)
[e2e-1.8.13.log](https://github.com/heptio/sonobuoy/files/2116849/e2e-1.8.13.log)
[201806181722_sonobuoy_67813e65-14e8-4266-96ae-d990c9dc5c14.tar.gz](https://github.com/heptio/sonobuoy/files/2116846/201806181722_sonobuoy_67813e65-14e8-4266-96ae-d990c9dc5c14.tar.gz)

**Comment by timothysc** [comment]
@jhamilton1 - So I see the likely culprit.  It is API Version skew and the tests in 1.10 are not properly gated for, backwards compatibility with that version.  If you were to run the kube_conformance container for 1.8, it should pass.  

So this problem will rectify itself, but we should make certain our version test matrix is clean.  Which I thought it was from this comment - https://github.com/heptio/sonobuoy/issues/341#issuecomment-371618312 , but I don't see how the v1.10 tests will pass on 1.8 without pinning the suite to a version which supports the api-versioning scheme. 

So workaround is, use a older version of the kube_conformance container.

**Comment by timothysc** [comment]
We could use this issue as an RFE for auto-detection and setting the version of the conformance container.

**Comment by jhamilton1** [comment]
@timothysc I completely agree. That would be easier for the end user, especially as they start upgrading away from 1.8 

I will get that together.

**Comment by jhamilton1** [comment]
@timothysc I will be converting this issue to an RFE. I will adjust the applicable fields to reflect this. I am going to notate that it was initially a bug report.
