### ISSUE TITLE
DNS test fails to bind on port 80

### ISSUE THREAD

**Issue by caruccio** [heptio/sonobuoy#446]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Bug report

**What happened**:

Using instructions from cncf's k8s-conformance, it will fail on openshift v3.9 (k8s v1.9.1)

```
[centos@master-1 results]$ oc logs -n e2e-tests-dns-dd7q2   dns-test-a0ddb023-78d1-11e8-b524-0a580a80006f -c webserver
2018/06/25 23:47:10 listen tcp :80: bind: permission denied
```

**What you expected to happen**:

Avoid to use a privileged port when possible. As an workaround one needs to give privileged scc to default systemaccount  from the namespace.

**How to reproduce it (as minimally and precisely as possible)**:

Run sonobuoy on an openshift v3.9 cluster

**Anything else we need to know?**:

**Environment**:

- Sonobuoy tarball (which contains * below)
- Kubernetes version (use `kubectl version`):
```
$ kubectl version
Client Version: version.Info{Major:"", Minor:"", GitVersion:"v1.9.1+a0ce1bc657", GitCommit:"a0ce1bc", GitTreeState:"clean", BuildDate:"2018-04-11T20:47:54Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"", Minor:"", GitVersion:"v1.9.1+a0ce1bc657", GitCommit:"a0ce1bc", GitTreeState:"clean", BuildDate:"2018-04-11T20:47:54Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

$ oc version
oc v3.9.0+ba7faec-1
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://api.rankmycluster.com
openshift v3.9.0+ba7faec-1
kubernetes v1.9.1+a0ce1bc657
```

- Cloud provider or hardware configuration:

AWS

- OS (e.g. from /etc/os-release):

```
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
- Kernel (e.g. `uname -a`):

```
$ uname -a
Linux master-1 3.10.0-862.3.2.el7.x86_64 #1 SMP Mon May 21 23:36:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by caruccio** [comment]
Same for container-probe tests:

```
$ oc logs  -n e2e-tests-container-probe-x92xd   test-webserver-afcc9674-78d5-11e8-b524-0a580a80006f
2018/06/26 00:14:34 listen tcp :80: bind: permission denied
```

**Comment by timothysc** [comment]
This is a permissions issue with openshift, not a sonobuoy issue.  

All of the configurations can be customized into sonobuoy, and if folks want to make openshift a supported default platform, then we'd happily accept patches.

**Comment by caruccio** [comment]
I see. Thanks for clarification.
