### ISSUE TITLE
v1.11.x refresh test plan 

### ISSUE THREAD

**Issue by timothysc** [heptio/sonobuoy#451]
- [ ] Bare Metal Tests v1.9, v1.10, v1.11 
    - [ ] Ubunut 16.04 
    - [x] CentOS 7.4 (Tim)
- [ ] Cloud Provider Hosted Services 
   - [ ] AKS 
   - [ ] GKE 
   - [ ] EKS
- [ ] Cloud provider tests
  - [x] aws quickstart 
  - [ ] gcp kubeadm 
  - [ ] azure kubeadm 

We desperately need a means of automating this. 
/cc @chuckha @liztio @rdodev @timh

**Comment by chuckha** [comment]
integration test for `sonobuoy run` (and probably all commands) on 

1. fresh cluster
2. pre-exising sonobuoy resources in a cluster

**Comment by chuckha** [comment]
I'm punting this out of the milestone, other things are higher priority

**Comment by timothysc** [comment]
I tested CentOS 7.4.

**Comment by krisdock** [comment]
Testing on AWS Quickstart cluster.

**Comment by krisdock** [comment]
AWS Quickstart PASS

K8s version: v1.10.3

```
Ran 139 of 890 Specs in 3264.312 seconds
SUCCESS! -- 139 Passed | 0 Failed | 0 Pending | 751 Skipped PASS
```

**Comment by timothysc** [comment]
thx @krisdock !

**Comment by krisdock** [comment]
Testing on EKS cluster.

**Comment by timothysc** [comment]
@krisdock just a PSA that we have seen some weirdness on GKE on latest revision.

**Comment by krisdock** [comment]
EKS cluster
K8s version: v1.10.3
Results:
```
Summarizing 3 Failures:

[Fail] [sig-network] Proxy version v1 [It] should proxy through a service and a pod  [Conformance]
/workspace/anago-v1.10.5-beta.0.53+32ac1c9073b132/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/proxy.go:275

[Fail] [sig-network] DNS [It] should provide DNS for the cluster  [Conformance]
/workspace/anago-v1.10.5-beta.0.53+32ac1c9073b132/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/dns_common.go:439

[Fail] [sig-network] DNS [It] should provide DNS for services  [Conformance]
/workspace/anago-v1.10.5-beta.0.53+32ac1c9073b132/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/dns_common.go:439

Ran 139 of 890 Specs in 6670.270 seconds
FAIL! -- 136 Passed | 3 Failed | 0 Pending | 751 Skipped --- FAIL: TestE2E (6670.36s)
```

**Comment by timothysc** [comment]
Closing.. @rdodev - FYI.

**Comment by iuriaranda** [comment]
@krisdock any idea why those specific tests are failing on EKS? We get the same failed tests on EKS running k8s version 1.12
