### ISSUE TITLE
Namespaces are stuck at Terminating

### ISSUE THREAD

**Issue by kiranmudemela** [heptio/sonobuoy#457]
Hi Team, 
We see e2e namespaces are in Terminating status for longer period 

e2e-tests-downward-api-v6sqw   Terminating   25m
e2e-tests-emptydir-9htcg       Terminating   4m
e2e-tests-events-k66sz         Terminating   46m
e2e-tests-pods-8frsj           Terminating   15m
e2e-tests-secrets-xvqg7        Terminating   57m
e2e-tests-services-7m7mr       Terminating   36m
**Environment:**

- Sonobuoy version: v0.11.3
- Kubernetes version: (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T15:22:13Z", GoVersion:"go1.9.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.7-2+ff9181f92914d6", GitCommit:"ff9181f92914d638c93511c5163ac1e5dcbdf492", GitTreeState:"clean", BuildDate:"2018-04-24T22:19:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration: Oracle Cloud 

- OS (e.g. from `/etc/os-release`): Oracle clinux

**Comment by timothysc** [comment]
This isn't actually a sonobuoy problem, but and upstream issue on NS deletion.  

There are a number of ways NS-deletion can be blocked: 
- policy enforcement 
- Other pending resource termination (can be stuck for a number of reasons) 
- cluster misconfiguration...

**Comment by timothysc** [comment]
Might want to adjust this api-server arg in your env too. 

--delete-collection-workers int                           Number of workers spawned for DeleteCollection call. These are used to speed up namespace cleanup. (default 1)
