### ISSUE TITLE
How to know that RUN's are completed 

### ISSUE THREAD

**Issue by kiranmudemela** [heptio/sonobuoy#458]
How do we come to know that Runs are completed and ready for review . 
----------
sonobuoy status
PLUGIN		STATUS		COUNT
e2e		running		1
systemd_logs	complete	9

Sonobuoy is still running. Runs can take up to 60 minutes.
----------
as of now i m running sonobuoy logs -f

**Comment by chuckha** [comment]
There is a hardstop timeout at 5400 seconds after the run starts (by default), otherwise, keep running status every now and again to see if it says complete.

**Comment by timothysc** [comment]
Closing this issue, as the status is denotes 'completed' and there is a log as well.
