### ISSUE TITLE
quickstart needs explanation

### ISSUE THREAD

**Issue by jayunit100** [heptio/sonobuoy#46]
*Issue*

Looks like the examples/quickstart is meant (i think) to setup the knobs necessary to deploy sonobuoy on a secure initial kube cluster, like the one heptio deploys - which needs special RBACs.  

*Solution* 

Usage of the rbac.yaml + pod.yaml files should probably be explained in a file inside of `exampels/quickstart` i.e. `examples/quickstart/README` or whatever.  Not all clusters will need the special RBACs (although many will / should) and so some folks can probably just create the pod.yaml.

**Comment by timothysc** [comment]
+1, and ideally I'd like to autogenerate according to params + templates. 

/cc @chuckha @abiogenesis-now

**Comment by abiogenesis-now** [comment]
Both the explanation and the autogeneration should be addressed by https://github.com/heptio/sonobuoy/pull/58.

Feel free to reopen/comment this issue if you don't think that PR is sufficient, but I'm closing this for now.
