### ISSUE TITLE
how to restrict the sonobuoy i.e not to expose recorded data/conformance test result to outside(heptio).

### ISSUE THREAD

**Issue by bond007007** [heptio/sonobuoy#461]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
I retrieved the data with command (sonobuoy retrieve .) and in result directory I got the test results.
And also by using sonobuoy scanner tool (kubectl apply -f https://scanner.heptio.com/bbebb13c3e14839c8df3c60a4640dd90/yaml/) I got the conformance test.

**What did you expect to happen:**
The data/test-result which I got that must also be recorded by (heptio-sonobuoy). But I don't want my test-results to be expose outside(heptio-sonobuoy).
So how to restrict it i.e how not to let expose my application (say my) conformance test result outside(i.e public / heptio-sonobuoy).
  

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
I want my test-result / information not to expose outside(heptio-sonobuoy). i.e I want my test result (conformance test) to be private. So how can I achive it. Any help will be appreciated thanks.

**Environment:**
linux
- Sonobuoy version: latest
- Kubernetes version: (use `kubectl version`):1.9.6
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`): centos
- Sonobuoy tarball (which contains * below)

**Comment by chuckha** [comment]
Do you mean outside of the `heptio-sonobuoy` namespace? Or is this a question regarding privacy policy & scanner? I don't understand what you mean by private.

**Comment by bond007007** [comment]
ya I mean regarding privacy policy and scanner. I want to know that is heptio stores the scanned results in its db, if it is so then our application or say platform data is no longer have privacy bcoz it scans whole cluster info.
So, is there any way to provide privacy to some extend.

**Comment by timothysc** [comment]
When using scanner, we minimize the amount of data we maintain and we remove all the data after a period of time.  This is spelled out in the "terms of service" on the site.  

If you want the data private then I'd suggest using the open source tool itself and not scanner SaaS tool.

**Comment by bond007007** [comment]
thanks for the help:)
