### ISSUE TITLE
Restructure cmd package

### ISSUE THREAD

**Issue by chuckha** [heptio/sonobuoy#462]
**Describe the solution you'd like**
The command package uses init a lot. Every command requires an init function to register itself.

This makes testing hard as we have no way to mock anything. We run the test, the init runs and the command is built.

I propose we follow a pattern that is a variation on upstream. We start with a [root command](https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/kubeadm.go) and from the root we import our sonobuoy [top level command](https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/cmd/cmd.go#L32) and call Execute. It will look a lot like [this file](https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/kubeadm.go#L31).

## What this would enable

* proper dependency injection
* a single spot that clearly defines all available subcommands
* a clear place to parse flags, i suspect we are doing it slightly wrong because of glog
* ability to run a higher level test
* better package structure

Globals are the norm in sonobuoy CLI and they should not be.

**Comment by ekj1711** [comment]
I am interested to work on this. Can i pick it up?

**Comment by johnSchnake** [comment]
@ekj1711 Absolutely! I think there is enough in the description to get you started. Let me know if you need any direction though. 👍
