### ISSUE TITLE
Sonobuoy needs a context in order to analyze results

### ISSUE THREAD

**Issue by scottslowe** [heptio/sonobuoy#469]
**What steps did you take and what happened:**
I ran `sonobuoy e2e <archive>` to analyze the results of a Sonobuoy scan against a Kubernetes cluster. Sonobuoy reported the following error:

```
ERRO[0000] couldn't get REST client: invalid configuration: no configuration has been provided
```

I guessed this meant that Sonobuoy needed a `kubectl` context set (there was no context set on this system). I set the context using `kubectl config set current-context <context-name>` and ran the command again. It succeeded.

**What did you expect to happen:**
I expected either a) Sonobuoy to analyze the results; or b) Sonobuoy to provide a clearer error message about needing a context set for `kubectl`.

**Anything else you would like to add:**
No

**Environment:**

- Sonobuoy version: 0.11.2
- Kubernetes version: (use `kubectl version`): 1.10.2
- Kubernetes installer & version: 1.10.4 (installed via Ansible + `kubeadm`)
- Cloud provider or hardware configuration: N/A (no connectivity to cluster; offline analysis of Sonobuoy results)
- OS (e.g. from `/etc/os-release`): Fedora 27 on the system running `sonobuoy` for offline anlaysis of Sonobuoy results

**Comment by chuckha** [comment]
This is fixed on the master branch.

https://github.com/heptio/sonobuoy/commit/9039d3ac953fe641ca35a4fa6e9156c4038c6d1e#diff-f6f1cbdfc63048c2340177ccd708d6b6
