### ISSUE TITLE
Handle PodPresets better

### ISSUE THREAD

**Issue by chuckha** [heptio/sonobuoy#473]
PodPresets are an optional api group that are not enabled by default on a kubeadm cluster.

https://kubernetes.io/docs/concepts/workloads/pods/podpreset/#enable-pod-preset

We have two choices. Remove PodPresets as a resource we harvest or don't print an error if the APIServer doesn't support the resource.

**Comment by timothysc** [comment]
Yeah I'll remove both PodPresets + Secrets  

PodPresets are a weird beast, I'll start working on it.
