### ISSUE TITLE
PodLogs do not work on master branch

### ISSUE THREAD

**Issue by chuckha** [heptio/sonobuoy#475]
**What steps did you take and what happened:**
I started seeing

```time="2018-07-11T02:45:22Z" level=error msg="the server rejected our request due to an error in our request (get pods sonobuoy)"```

in my sonobuoy logs.

This failure can be traced back to the ValidatePodLogOptions in the kube-apiserver: https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/core/v1/validation/validation.go#L125

I have not yet been able to trace the commit to kubernetes where we are now affected by this, but it passes on sonobuoy v0.11.3 which is pinned to k8s 1.9 and fails on master which is pinned to k8s version v1.11.

I have a fix in place and will continue digging so I can find the exact cause of this error.

This caused me to read through the PodLog limits code and I think it needs to be revisited, but that's out of scope for this ticket.

**What did you expect to happen:**
I expected PodLogs to be gathered like normal.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Sonobuoy version: 
- Kubernetes version: (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`): 
- Sonobuoy tarball (which contains * below)

**Comment by timothysc** [comment]
It's likely a change in the client tooling, options, etc.

**Comment by timothysc** [comment]
@chuckha - did you accidentally push to master here?

**Comment by chuckha** [comment]
I did at some point accidentally push to scanner master, but not sonobuoy. This was closed https://github.com/heptio/sonobuoy/pull/467

**Comment by timothysc** [comment]
Ahh it was on the commit message it auto-closed.
