### ISSUE TITLE
Sonobuoy run fails immediately when using Extended mode

### ISSUE THREAD

**Issue by scottslowe** [heptio/sonobuoy#480]
**What steps did you take and what happened:**
I downloaded Sonobuoy 0.11.3 and initiated a run against a cluster using `sonobuoy run -m Extended`. After a couple of minutes, I checked using `sonobuoy status` and Sonobuoy reported that the pod was listed as Failed. Using `kubectl describe` and `kubectl logs`, I found that the Sonobuoy pod had exited with this error message:
```
time="2018-07-11T17:59:43Z" level=error msg="error loading sonobuoy configuration: Configured plugin heptio-e2e does not exist"
```

**What did you expect to happen:**
I expected the Sonobuoy run to start.

**Anything else you would like to add:**
No

**Environment:**

- Sonobuoy version: 0.11.3
- Kubernetes version: (use `kubectl version`): 1.9.3
- Kubernetes installer & version: kubeadm 1.9.3
- Cloud provider or hardware configuration: AWS (configured via Terraform)
- OS (e.g. from `/etc/os-release`): CentOS 7

**Comment by timothysc** [comment]
@scottslowe - we explicitly removed the extended tests until we decide on an open source plan.  It was causing user confusion.

**Comment by timothysc** [comment]
This behavior is removed in the next version, so closing for now.
