### ISSUE TITLE
[idea] brainstorm how to communicate PASS / FAIL data...

### ISSUE THREAD

**Issue by jayunit100** [heptio/sonobuoy#49]
*This might be out of scope, just an idea, feel free to close if interpretting/displaying collection results is out of scope* 

*GOAL* 

Many buouys will have a discreet result, i.e. cluster is healthy (pass) or not (fail).  Some might not have such results, but since many will, it would be nice if they could share this info with the collector somehow.

*EXAMPLE*

As a E2E test user, I'd like to:

1. Run, or automate the run, of the sonobouy E2E tests via `kube apply` as with a --summary= , where the summary value is a command that exits 1 or 0 (i.e. `--summary='grep -q 0 FAILURES'`).
2. See something like this in a sidecar, without having to collect data.

```
Sonobuoy Results
=============
{
{"date":"Aug 15, 2013, 1:35 PM","exec-pod":"E2E", "result":"PASSED",link:"results15-2013-135.gz"},
{"date":"Aug 15, 2013, 2:40 PM","exec-pod":"E2E", "result":"FAILED", link:"results14-2013-240.tar.gz"}
}
```
 
Note that (1) and (2) are independent.    We can have (2) without having (1).  Possibly the sonobuouy test pod can run (1) and output it as its final log before exiting, without (2) and then you can `kubectl logs -f xyz | tail -1` to get the end result of your pass/fail.  But ideally (1) and (2) would work together for an 'at-a-glance' of your buouys. 

*USE CASE*
 - vendors could ship their products with sonobuoy instructions for setting up alerts.  i.e. I could have a sonobuoy plugin which ran smoke tests, and then, I don't have to write my own reports, because sonobuoy is broadcasting those reports for me in a sidecar.
- this makes the need to access tarballs or volumes for test results unnecessary for superficial inspection and only needed for forensics, deep diving into problems/ archival..

Best analogy is to the simple prometheus UI that ships on the prometheus master - gives you a global way to play w/ the data before putting it in a more sophisticated dashboard.  Im thinking SB could ship w/ something similar for users.

**Comment by timothysc** [comment]
Doesn't the .jmx file give you most of that data?  It should auto-explode when we get our image builder back up.

**Comment by jayunit100** [comment]
Let me play some more w the e2e runs and see if it already is solved for me with what's there...

**Comment by timothysc** [comment]
Closing in favor of #51.
