### ISSUE TITLE
Sonobuoy rejected kubernetes binary version containing metadata

### ISSUE THREAD

**Issue by waynr** [heptio/sonobuoy#497]
**What steps did you take and what happened:**
I have installed sonobuoy `v0.11.4` and ran the following command:

```
wayne@7c4588613ad2:/k8s-installer$ sonobuoy run -m Quick --kubeconfig clusters/kubernetes-wwarren-test/generated/auth/kubeconfig                                                                                                                                                 
ERRO[0000] could not retrieve E2E config: version "v1.10.5+rackspace.0" is invalid: version cannot have prelease or metadata, please use a stable version
```

Sonobuoy appears to be rejecting the patch version naming scheme we use (we are currently carrying a patch for https://github.com/kubernetes/kubernetes/pull/64930)

**What did you expect to happen:**
I don't know, I've never run sonobuoy myself but I didn't expect it to reject the version string for our kubernetes binary. I am attempting to automate some portion of the sonobuoy test suite in our CI system and becoming familiar with installation and running locally.

**Anything else you would like to add:**
Nope.

**Environment:**

- Sonobuoy version: `v0.11.4`
- Kubernetes version: (use `kubectl version`): `v1.10.5`
- Kubernetes installer & version: custom installer
- Cloud provider or hardware configuration: Openstack
- OS (e.g. from `/etc/os-release`): 
```
zsh/3 8830 [130]  (git)-[k8s-1332]-% kubectl get nodes  -o wide                                     
NAME                               STATUS    ROLES     AGE       VERSION               EXTERNAL-IP     OS-IMAGE                                        KERNEL-VERSION   CONTAINER-RUNTIME
kubernetes-wwarren-test-master-0   Ready     master    1h        v1.10.5+rackspace.0   172.99.77.178   Container Linux by CoreOS 1688.5.3 (Rhyolite)   4.14.32-coreos   docker://17.12.1-ce
kubernetes-wwarren-test-master-1   Ready     master    1h        v1.10.5+rackspace.0   172.99.77.163   Container Linux by CoreOS 1688.5.3 (Rhyolite)   4.14.32-coreos   docker://17.12.1-ce
kubernetes-wwarren-test-master-2   Ready     master    1h        v1.10.5+rackspace.0   172.99.77.172   Container Linux by CoreOS 1688.5.3 (Rhyolite)   4.14.32-coreos   docker://17.12.1-ce
kubernetes-wwarren-test-worker-0   Ready     node      1h        v1.10.5+rackspace.0   <none>          Container Linux by CoreOS 1688.5.3 (Rhyolite)   4.14.32-coreos   docker://17.12.1-ce
kubernetes-wwarren-test-worker-1   Ready     node      1h        v1.10.5+rackspace.0   <none>          Container Linux by CoreOS 1688.5.3 (Rhyolite)   4.14.32-coreos   docker://17.12.1-ce
kubernetes-wwarren-test-worker-2   Ready     node      1h        v1.10.5+rackspace.0   <none>          Container Linux by CoreOS 1688.5.3 (Rhyolite)   4.14.32-coreos   docker://17.12.1-ce
```
- Sonobuoy tarball (which contains * below)

**Comment by timothysc** [comment]
/assign @liztio  

error stack -
-> https://github.com/heptio/sonobuoy/blob/master/cmd/sonobuoy/app/imageversion.go#L100   
-> https://github.com/heptio/sonobuoy/blob/master/cmd/sonobuoy/app/run.go#L78 . 

through the hashi version checker, b/c it's not happy with the naming.  I'd need to dig into proper-semver

**Comment by timothysc** [comment]
@waynr - as a workaround you can bypass via gen and pass a specific image version tag `v1.10`

**Comment by waynr** [comment]
Thanks @timothysc! I'd also be happy to help out with a PR if you have any pointers for how version strings like this should be handled.

**Comment by waynr** [comment]
For what it's worth if any future people find this issue the workaround for me ended up being:

```
sonobuoy run --mode Quick --kubeconfig <pathtokubeconfig> --kube-conformance-image-version v1.10
```

So I didn't need to run `sonobuoy gen` since `sonobuoy run` also supports the `--kube-conformance-image-version`.

**Comment by timothysc** [comment]
@liztio - I don't think https://github.com/heptio/sonobuoy/blob/master/cmd/sonobuoy/app/imageversion.go#L94 is required.  e.g. - we can warn and not error.

**Comment by timothysc** [comment]
@waynr we can get a quick patch shortly.  

We will likely not cut a release in a couple of days, but once the patch is merged you should be able to run `go get -u -v github.com/heptio/sonobuoy` and pickup the changes.

**Comment by timothysc** [comment]
@waynr merged.   

To pick up the latest changes run: `go get -u -v github.com/heptio/sonobuoy` everything else should just work.
