### ISSUE TITLE
Add a major.minor tag to the image build

### ISSUE THREAD

**Issue by chuckha** [heptio/sonobuoy#499]
**Describe the solution you'd like**
I would like to have a mutating v${MAJOR}.${MINOR} image tag on sonobuoy  that always points to the latest release patch.

example: gcr.io/heptio-images/sonobuoy:v0.11 as of the time of making this issue should point to gcr.io/heptio-images/sonobuoy:v0.11.4

**Anything else you would like to add:**

I want this feature to reduce the amount I have to touch scanner.heptio.com. I will only need to bump it for minor/major changes instead of patch versions as well.

**Comment by liztio** [comment]
We thought we fixed this, but the v0.11 image doesn't seem to be getting pushed
