### ISSUE TITLE
Packaging problem with sonobuoy container image

### ISSUE THREAD

**Issue by mauilion** [heptio/sonobuoy#517]
**What steps did you take and what happened:**
I am seeing a different sonobuoy binary packaged in the container located at:
gcr.io/heptio-images/sonobuoy:v0.11.5 

than at the binary download:
https://github.com/heptio/sonobuoy/releases/download/v0.11.5/sonobuoy_0.11.5_linux_amd64.tar.gz

I have verified this with the following steps.

Download the binary above and run:
`strings sonobuoy | grep -A80 kind..DaemonSet`
you should see: https://gist.github.com/mauilion/4dd405b2ed615330583720130f1ced5e#file-binary-yaml

When you run the same command against the sonobuoy binary packaged in the container you see:
https://gist.github.com/mauilion/4dd405b2ed615330583720130f1ced5e#file-container-yaml

The difference is in the tolerations. 

**What did you expect to happen:**
I expect the binary that ships in the container at a specific tag to be a match for the binary that i can download at that version.

**Anything else you would like to add:**
I think we need a step that validates the checksums between the binary for release and the binary in the container. If they don't match something is up. This may mean altering the release process to make the artifact as part of a prerelease step then running tests against binary from that prerelease step. Then publishing both the artifact and the container with that artifact as part of the promotion of the prerelease to the new tagged version. 

**Environment:**

- Sonobuoy version: v0.11.5
- Kubernetes version: (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`): 
- Sonobuoy tarball (which contains * below)

**Comment by timothysc** [comment]
@liztio  This is super weird.

**Comment by timothysc** [comment]
./sonobuoy version
v0.11.3-35-gfb55de6 

^ This is from the container pushed to our registry.  

What in the (@*#&$

**Comment by liztio** [comment]
This should be fixed in v0.11.6

**Comment by mauilion** [comment]
Hey why don't we push the git sha tag?

**Comment by timothysc** [comment]
Closing now in favor of https://github.com/heptio/sonobuoy/issues/518
