### ISSUE TITLE
TLS errors cause sonobuoy not to terminate until it hits the timeout

### ISSUE THREAD

**Issue by ceridwen** [heptio/sonobuoy#519]
**What steps did you take and what happened:**
While running a single test, I noticed TLS errors in the logs:

```
$ kubectl logs -n heptio-sonobuoy sonobuoy -f
time="2018-07-31T23:04:26Z" level=info msg="Scanning plugins in ./plugins.d (pwd: /)"
time="2018-07-31T23:04:26Z" level=info msg="Scanning plugins in /etc/sonobuoy/plugins.d (pwd: /)"
time="2018-07-31T23:04:26Z" level=info msg="Directory (/etc/sonobuoy/plugins.d) does not exist"
time="2018-07-31T23:04:26Z" level=info msg="Scanning plugins in ~/sonobuoy/plugins.d (pwd: /)"
time="2018-07-31T23:04:26Z" level=info msg="Directory (~/sonobuoy/plugins.d) does not exist"
time="2018-07-31T23:04:26Z" level=info msg="Filtering namespaces based on the following regex:.*|heptio-sonobuoy"
time="2018-07-31T23:04:27Z" level=info msg="Namespace default Matched=true"
time="2018-07-31T23:04:27Z" level=info msg="Namespace heptio-sonobuoy Matched=true"
time="2018-07-31T23:04:27Z" level=info msg="Namespace kube-public Matched=true"
time="2018-07-31T23:04:27Z" level=info msg="Namespace kube-system Matched=true"
time="2018-07-31T23:04:27Z" level=info msg="Starting server Expected Results: [{fab10-compute-1 systemd_logs} {fab10-compute-2 systemd_logs} {fab10-compute-3 systemd_logs} {fab10-compute-4 systemd_logs} {fab10-compute-5 systemd_logs} { e2e}]"
time="2018-07-31T23:04:27Z" level=info msg="Starting annotation update routine"
time="2018-07-31T23:04:27Z" level=info msg="Starting aggregation server" address=0.0.0.0 port=8080
time="2018-07-31T23:04:27Z" level=info msg="Running plugin" plugin=systemd-logs
time="2018-07-31T23:04:27Z" level=info msg="Running plugin" plugin=e2e
time="2018-07-31T23:04:31Z" level=info msg="received aggregator request" client_cert=systemd-logs node=fab10-compute-2 plugin_name=systemd_logs
time="2018-07-31T23:04:31Z" level=info msg="received aggregator request" client_cert=systemd-logs node=fab10-compute-1 plugin_name=systemd_logs
time="2018-07-31T23:04:31Z" level=info msg="received aggregator request" client_cert=systemd-logs node=fab10-compute-5 plugin_name=systemd_logs
2018/07/31 23:04:31 http: TLS handshake error from 1.100.101.13:44756: remote error: tls: bad certificate
time="2018-07-31T23:04:31Z" level=info msg="received aggregator request" client_cert=systemd-logs node=fab10-compute-4 plugin_name=systemd_logs
2018/07/31 23:04:32 http: TLS handshake error from 1.100.101.13:44758: remote error: tls: bad certificate
2018/07/31 23:04:33 http: TLS handshake error from 1.100.101.13:44760: remote error: tls: bad certificate
time="2018-07-31T23:05:25Z" level=info msg="received aggregator request" client_cert=e2e plugin_name=e2e
time="2018-07-31T23:05:27Z" level=info msg="Gracefully shutting down plugins due to timeout."
```

(I shortened the timeout for this run so I would get a tarball without waiting.)

This cluster has NTP running and the clocks seem to be synched correctly, and these are not the x509 errors I'd expect from that.

**What did you expect to happen:**

No TLS errors.

**Environment:**

- Sonobuoy version: 0.11.6
- Kubernetes version: (use `kubectl version`): 1.10.5
- Kubernetes installer & version: kubespray
- Cloud provider or hardware configuration: bare metal
- OS (e.g. from `/etc/os-release`): Ubuntu 16.04
- Sonobuoy tarball (which contains * below)

[201807312304_sonobuoy_8d4c1c4b-ba7f-4576-bf86-82b688f30d9a.tar.gz](https://github.com/heptio/sonobuoy/files/2247471/201807312304_sonobuoy_8d4c1c4b-ba7f-4576-bf86-82b688f30d9a.tar.gz)

**Comment by timothysc** [comment]
This means your client's certificate is invalid because either:

The server doesn't trust the client's signing certificate authority 
The client doesn't trust the server's signing certificate authority
The certificate's DN doesn't match the hostname   

@ceridwen from your tarball, it looks like it's consistently failing on `1.100.101.13 or fab10-compute-3` tries to report it's systemd logs during this run.  

In running through the events for that node in the heptio-sonobuoy namespace it appears that the systemd container was run twice.  Sadly there is a ton of data there, but I don't have the logs for the systemd container when it finishes and tries to report back to the aggregator.  

We do have a general problem with daemonsets retarting, but typically we don't see this specific issue. 
/cc @liztio

**Comment by johnSchnake** [comment]
ping @ceridwen Closing due to age at this point. If you can repro still please let us know and provide any updated information you can.
