### ISSUE TITLE
Non-standard version names aren't verified

### ISSUE THREAD

**Issue by rbankston** [heptio/sonobuoy#522]
**What steps did you take and what happened:**

Using sonobuoy scanner with Kubernetes version v1.10.0-beta.0.1462+d74209880062ad-dirty the 1.11 tests are used and show as failures

**What did you expect to happen:**

Expected the 1.10 conformance test to be used.

**Anything else you would like to add:**

![screen shot 2018-07-19 at 5 25 42 pm](https://user-images.githubusercontent.com/130836/43844993-f60b37bc-9af8-11e8-99cb-ad91b01f9d18.png)

A sonobuoy run using kubernetes 1.10.5 produces a clean run using the correct sonobuoy version

https://scanner.heptio.com/32b8b760eff28ffabcb8f10ccd56ccc9/diagnostics/

**Comment by chuckha** [comment]
Scanner will use the kube-conformance:latest tag. I believe the 1.10.5 version is conformant with the 1.11 conformance tests whereas the 1.10.0-beta.0 is not actually passing the 1.11 conformance tests.

Conformance tests should be OK across two versions, so you could theoretically pass the 1.11 conformance tests with a 1.9 cluster.

I could be missing something though. I know sonobuoy the CLI auto-detects the version of conformance tests to run whereas scanner does not.

**Comment by rbankston** [comment]
Thanks for the explanation @chuckha marking this closed.
