### ISSUE TITLE
E2E [sig-network] test failure: forbidden: User "...sonobuoy-serviceaccount" cannot get path "/metrics"

### ISSUE THREAD

**Issue by smurfralf** [heptio/sonobuoy#526]
**What steps did you take and what happened:**
Running sonobuoy cli on kubernetes v1.10.4 for e2e tests with RBAC enabled results in a test failure as follows:

`[Fail] [sig-network] Networking [It] should provide unchanging, static URL paths for kubernetes api services`
`/workspace/anago-v1.10.5-beta.0.53+32ac1c9073b132/src/k8s.io/kubernetes/_output/dockersized/go/src/k8s.io/kubernetes/test/e2e/network/networking.go:82`
`forbidden: User "system:servicesaccount:heptio-sonobuoy:sonobuoy-serviceaccount" cannot get path "/metrics""Forbidden"`

**What did you expect to happen:**
The RBAC for sonobuoy-serviceaccount should give permission to get /metrics.
However the sonobuoy/pkg/templates/manifest.go (built into the client) is as follows

> The apiVersion: rbac.authorization.k8s.io/v1
> kind: ClusterRole
> metadata:
>   labels:
>     component: sonobuoy
>   name: sonobuoy-serviceaccount
> rules:
> - apiGroups:
>   - '*'
>   resources:
>   - '*'
>   verbs:
>   - '*'

Testing manually, we find that to get access to `/metrics` I must also include the nonResourceURLs clause, minimally as follows:

> rules:
> - nonResourceURLs: ["/metrics"]
>    verbs: ["get"]

**Anything else you would like to add:**
Its a mystery to me why this bug has not been reported already.

**Environment:**

- Sonobuoy version: 11.5
- Kubernetes version: (use `kubectl version`): 10.4
- Kubernetes installer & version: in-house based on kubeadm
- Cloud provider or hardware configuration:  
- OS (e.g. from `/etc/os-release`): 
- Sonobuoy tarball (which contains * below) sonobuoy_0.11.5_linux_amd64.tar.gz

**Comment by chuckha** [comment]
This hasn't been reported because generally folks are just running the conformance e2es, but this is really good 👍 thanks for the report.
