### ISSUE TITLE
Forwarder error: 413

### ISSUE THREAD

**Issue by jwierzbo** [heptio/sonobuoy#528]
**What steps did you take and what happened:**
I've run `Sonobuoy `and my `forwarder` container failed (`kube-sonobuoy` is completed correctly):
```
time="2018-08-28T04:01:00Z" level=info msg="forwarder information" Scanner ID=a142c83eb22e20cdee1fc92421a7a88d Scanner URL="https://scanner.heptio.com"
time="2018-08-28T04:01:01Z" level=info msg="waiting for a done file to appear..." looking for=/tmp/sonobuoy/done
time="2018-08-28T04:16:35Z" level=info msg="done file detected"
time="2018-08-28T04:16:36Z" level=info msg="processing the done file contents"
time="2018-08-28T04:16:36Z" level=info msg="processing result file" result file=/tmp/sonobuoy/201808280400_sonobuoy_454314a5-3738-4e1e-b6b3-66263c6e7edb.tar.gz
time="2018-08-28T04:16:37Z" level=info msg="failed to POST data" endpoint="http://127.0.0.1:9898/ingest/" error="non success response code: 413" result file=/tmp/sonobuoy/201808280400_sonobuoy_454314a5-3738-4e1e-b6b3-66263c6e7edb.tar.gz
```

`sonobuoy retrieve -v=9` returns: `error retrieving results: error: tmp/sonobuoy no such file or directory` and log:
```
curl -k -v -XPOST  -H "X-Stream-Protocol-Version: v4.channel.k8s.io" -H "X-Stream-Protocol-Version: v3.channel.k8s.io" -H "X-Stream-Protocol-Version: v2.channel.k8s.io" -H "X-Stream-Protocol-Version: channel.k8s.io" -H "Authorization: Basic YWRtaW46RVM1cjk2QnFZMUx1WWQ1OFdxRTFuTFd6ZWF1RjVLQkQ=" 'https://api.xxx/api/v1/namespaces/heptio-sonobuoy/pods/sonobuoy/exec?command=%2Fusr%2Fbin%2Fenv&command=bash&command=-c&command=tar+cf+-+%2Ftmp%2Fsonobuoy%2F%2A.tar.gz&container=kube-sonobuoy&container=kube-sonobuoy&stdout=true'
ERROR: logging before flag.Parse: I0828 11:04:44.680288    8896 round_trippers.go:405] POST https://api.tsttwo.cmp.barco.cloud/api/v1/namespaces/heptio-sonobuoy/pods/sonobuoy/exec?command=%2Fusr%2Fbin%2Fenv&command=bash&command=-c&command=tar+cf+-+%2Ftmp%2Fsonobuoy%2F%2A.tar.gz&container=kube-sonobuoy&container=kube-sonobuoy&stdout=true 500 Internal Server Error in 291 milliseconds
```

**What did you expect to happen:**
Forwarder sents logs to https://scanner.heptio.com
`sonobuoy retrieve` works if forwarder can not sent results and Pod still exist.

**Anything else you would like to add:**
I've found similar issue, where the log archieve had 76 MB: https://github.com/heptio/sonobuoy/issues/443

In my case is only 1.1 MB:
```
ls -lah /var/lib/kubelet/pods/f6f63358-aa76-11e8-b354-06d696853cca/volumes/kubernetes.io~empty-dir/sonobuoy-output/
-rw-r--r-- 1 root root 1.1M Aug 28 04:16 201808280400_sonobuoy_454314a5-3738-4e1e-b6b3-66263c6e7edb.tar.gz
-rw-r--r-- 1 root root   79 Aug 28 04:16 done
```

**Environment:**

- Sonobuoy version: v0.11.6
- Kubernetes version: v1.9.7
- Cloud provider or hardware configuration: AWS
- OS: Debian 9
- Sonobuoy tarball (which contains * below)

**Comment by chuckha** [comment]
Oh, this is a good one. The logs aren't helping me at all. @jwierzbo any chance you would be willing to share your tarball either privately or on this ticket?

**Comment by chuckha** [comment]
The behavior of retrieve makes sense. The last step in scanner's process is to clean up. After the forwarder failed, the namespace deleter removed your sonobuoy namespace so retrieve couldn't grab the tarball.

**Comment by johnSchnake** [comment]
I think this is probably just a result of #572 ; the issue being that there used to be a race between the aggregator reporting itself as completed even though the results were not really packaged up and ready.

Going to close this now; if you run into this again please let us know.
