### ISSUE TITLE
[quickstart] Support non-rbac clusters

### ISSUE THREAD

**Issue by chuckha** [heptio/sonobuoy#53]
Right now we only have an RBAC solution for the quickstart. We would like to support clusters that do not have RBAC.

Work involved: If #52 gets merged, then we can add an if statement in the ksonnet that doesn't generate the rbac objects if a particular flag is passed in. Then in the makefile we can add an environment variable to the `generate-examples`  target. Since the only dependency is docker for building the quickstart examples, we can then encourage non-rbac users to regenerate the examples with a particular flag or we could maintain a generated copy of that JSON.

**Comment by timothysc** [comment]
This is where the ksonnet/kcfg init comes in to auto-detect caps and cache vars used for generation. 

/cc @hausdorff

**Comment by hausdorff** [comment]
Not sure how I missed this, but we're actually pretty close to supporting this.

**Comment by abiogenesis-now** [comment]
Done with https://github.com/heptio/sonobuoy/pull/58
