### ISSUE TITLE
sonobuoy delete doesn't seem to cleanup properly

### ISSUE THREAD

**Issue by sercanacar** [heptio/sonobuoy#531]
**What steps did you take and what happened:**
**Ran a test with:**
sonobuoy run
**Deleted the test**
sonobuoy delete
**Ran another test**
sonobuoy run

**What did you expect to happen:**
Test results to be exact same, but there were 3 failures in the second test

```
Summarizing 3 Failures:

[Fail] [sig-scheduling] SchedulerPredicates [Serial] [BeforeEach] validates resource limits of pods that are allowed to run  [Conformance]
/workspace/anago-v1.10.5-beta.0.53+32ac1c9073b132/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduling/predicates.go:87

[Fail] [sig-scheduling] SchedulerPredicates [Serial] [BeforeEach] validates that NodeSelector is respected if matching  [Conformance]
/workspace/anago-v1.10.5-beta.0.53+32ac1c9073b132/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduling/predicates.go:87

[Fail] [sig-scheduling] SchedulerPredicates [Serial] [BeforeEach] validates that NodeSelector is respected if not matching  [Conformance]
/workspace/anago-v1.10.5-beta.0.53+32ac1c9073b132/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduling/predicates.go:87
```

```
  Expected error:
      <*errors.errorString | 0xc421b84e70>: {
          s: "Namespace e2e-tests-daemonsets-w5h8t is active",
      }
      Namespace e2e-tests-daemonsets-w5h8t is active
  not to have occurred
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Sonobuoy version: v0.11.6
- Kubernetes version: (use `kubectl version`):v1.10.5
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`): OL7
- Sonobuoy tarball (which contains * below)

**Comment by timothysc** [comment]
There are known issues with the upstream namespaces taking a while to cleanup.  We can/should fix some of the collision issues in the upstream tests.

**Comment by timothysc** [comment]
cc: @mauilion

**Comment by johnSchnake** [comment]
Those e2e/upstream problems aside, this will be resolved by the same `--wait` logic introduced by #568 .

**Comment by johnSchnake** [comment]
Closing this since it seems well covered by other issues/features:
 - `delete -all` flag does also delete the `e2e-` prefixed namespaces, the problem reported here seems to be about the speed with which that happens
 - the `--wait` logic that is already quested (mentioned above) will remedy the problem about trying to script around this and having to wait for the requested cleanup.
