### ISSUE TITLE
Allow SSH keys to be put into the plugin containers via CLI

### ISSUE THREAD

**Issue by johnSchnake** [heptio/sonobuoy#536]
**Motivation**
There are numerous e2e tests which require SSH keys to be present, otherwise they are skipped. There should be a way from the CLI to run those tests, given that you have the appropriate private key available.

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
`sonobuoy run --e2e-focus SSH --private-key=./path/to/private_key`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

This can currently be achieved manually but has a few downsides.
Process:
 -  Run `sonobuoy gen` with your focus/skip/etc options to generate a yaml file for deployment.
 - add a secret to the namespace which you have to manually base64 encode
      OR create the namespace and secret manually via kubectl first and remove the namespace from the yaml so you dont duplicate it.
 - add the volume and volume mount to the e2e pod

**Environment:**
I've done these steps manually on Mac and Linux; mainly against a cluster that was in Openstack but nothing is OS/platform/version specific. There is a tiny difference when creating the secret when you are base64 encoding if you are using the OS tools though since Mac/Linux have different default behavior/flags for newlines (see https://kubernetes.io/docs/concepts/configuration/secret/)

I am going to put up a PR to try and automate this but please let me know about agreement with this at a high level or if there are any nuances I need to be aware of.

**Comment by timothysc** [comment]
@johnSchnake - Do you have a list of tests that need ssh keys?  IMO we should fix them upstream, and try to avoid ssh-ing where possible and use the APIs for verification of behavior.

**Comment by johnSchnake** [comment]
That approach seems like a dead end since:
 - there is an entire test group titled "SSH", clearly needing SSH behavior
 - there are numerous other tests which need to be on the node to bring up/down services or test network state/volume data which can't be done without actually being on the node

I'm also not aware of any reason why the e2e suite _shouldn't_ be allowing e2e tests which use SSH so it seems like the downstream tool (sonobuoy) should support it.

If you search the repo for `framework.SkipUnlessSSHKeyPresent()` you can find the affected tests: https://github.com/kubernetes/kubernetes/search?q=SkipUnlessSSHKeyPresent%28%29&unscoped_q=SkipUnlessSSHKeyPresent%28%29 but its a little awkward to try and list them all since that function is in the `BeforeEach` of a few test groups.

**Comment by johnSchnake** [comment]
Is that a hard "no" on this feature (adding the `fixupstream` label)? Just trying to understand and plan accordingly on my side.

It still seems like this is a minor feature to add to the sonobuoy tool but on the k8s side it would require:
 - multiple PRs to change existing behavior
 - multiple sigs to approve those changes
 - all sigs to not reintroduce that behavior again

Again, I'm happy to do the work, I just wanted exactly this kind of feedback so that I didn't bother writing the code if there was a hard no from maintainers.

**Comment by timothysc** [comment]
@johnSchnake I'd be ok with an override right now and aim to fix upstream.

**Comment by ncdc** [comment]
@timothysc some of the verifications require checking things such as file system changes, which tend to require SSH because there are no API equivalents.

**Comment by timothysc** [comment]
@ncdc Why could you run a privileged validation pod to check the host?  

https://github.com/kubernetes/kubernetes/issues/69373

**Comment by ncdc** [comment]
@timothysc sounds like a good idea
