### ISSUE TITLE
ui button for "RBAC ENABLED" actually adds RBAC :)

### ISSUE THREAD

**Issue by jayunit100** [heptio/sonobuoy#537]
Whoops :), should be an easy fix .... when you click the "RBAC already enabled" button, i would assume it should remove the RBAC creation, but actualy the opposite happens.

My suggestion is just always have the rbac create step and kill the button ?  might be easier and is still idempotent i think.

![screen shot 2018-09-28 at 3 02 47 pm](https://user-images.githubusercontent.com/826111/46228334-bf96a400-c32f-11e8-9789-95afba77de46.png)

**Comment by jayunit100** [comment]
PS I love you sonobuoy

**Comment by jayunit100** [comment]
Bump ... lmk if I’m missing something , screen shot attached

**Comment by stevesloka** [comment]
Hey @jayunit100 looking at the latest version it seems this issue is resolved. When the page loads, RBAC is checked and it shows RBAC setup in the YAML, if you uncheck the box, then the RBAC configuration disappears. 

Please re-open if you are still not seeing the same! =)
