### ISSUE TITLE
Unable to deploy sonobuoy from master due to missing gcr images

### ISSUE THREAD

**Issue by Penson122** [heptio/sonobuoy#538]
**What steps did you take and what happened:**
`go get -u -v github.com/heptio/sonobuoy`
`make sonobuoy`
`sonobuoy run` to deploy sonobuoy against a kubenetes cluster
unable to deploy due to ImagePullBackOff for gcr.io/heptio-images/sonobuoy:v0.11.6-2-gc14a483
>Failed to pull image "gcr.io/heptio-images/sonobuoy:v0.11.6-2-gc14a483": rpc error: code = Unknown desc = Error response from daemon: manifest for gcr.io/heptio-images/sonobuoy:v0.11.6-2-gc14a483 not found

**What did you expect to happen:**
Expected to have added sonobuoy pods to kubernetes cluster

**Anything else you would like to add:**
Pulling the image locally also fails
`docker pull gcr.io/heptio-images/sonobuoy:v0.11.6-2-gc14a483`
>Error response from daemon: manifest for gcr.io/heptio-images/sonobuoy:v0.11.6-2-gc14a483 not found

**Environment:**

- Sonobuoy version: master
- Kubernetes version: (use `kubectl version`): 1.11
- Kubernetes installer & version:
- Cloud provider or hardware configuration: aws
- OS (e.g. from `/etc/os-release`): centos 7
- Sonobuoy tarball (which contains * below)

**Comment by timothysc** [comment]
This is known, we are currently working on a refresh for upstream 1.12 release and recommend https://github.com/heptio/sonobuoy/releases for stable releases.

**Comment by vryzhenkin** [comment]
@Penson122 You probably may want to use smith like this
`sonobuoy run --sonobuoy-image gcr.io/heptio-images/sonobuoy:v0.11.6`

**Comment by timothysc** [comment]
I'm going to close this later today as we should have an update later today.

**Comment by timothysc** [comment]
Closing v0.12.0 is released!
