### ISSUE TITLE
[docs] Improve end of README

### ISSUE THREAD

**Issue by abiogenesis-now** [heptio/sonobuoy#54]
Reword/clarify https://github.com/heptio/sonobuoy#2-run instructions
* s/unzip/extract (tarball)
* s/collection of tarballs/at least one tarball
* add extract command (hard to remember)

**Comment by timothysc** [comment]
Also out of date with regards to number of results, it should be only one.

**Comment by abiogenesis-now** [comment]
Mostly addressed by https://github.com/heptio/sonobuoy/pull/57---forgot to comment to add `tar xzvf <tarball>` before Ken merged ><

**Comment by abiogenesis-now** [comment]
^i'll get to that in a sec

**Comment by abiogenesis-now** [comment]
Also addressed by https://github.com/heptio/sonobuoy/pull/59, closing issue
