### ISSUE TITLE
Sonobuoy Version Documentation

### ISSUE THREAD

**Issue by rbankston** [heptio/sonobuoy#540]
**Describe the solution you'd like**
Would be helpful for there to be a matrix that lists version support of Kubernetes to tagged versions of the Sonobuoy scanner. This would  help people use an appropriate version as they work through upgrades to get to newer versions.

**Comment by rosskukulinski** [comment]
@emuetzel FYI request for Scanner

**Comment by johnSchnake** [comment]
Closing; the Scanner is no longer supported at this time. Thank you for your interest in that project. If you have other Sonobuoy questions or issues please feel free to reach out.
