### ISSUE TITLE
ipv6 support for the aggregator handler.

### ISSUE THREAD

**Issue by mauilion** [heptio/sonobuoy#542]
**What steps did you take and what happened:**
When running sonobuoy on a pure ipv6 cluster the systemd plugin doesn't work correctly we see errors like:
```
time="2018-10-12T21:17:47Z" level=error msg="error encountered dialing master at https://fd00:40::3:0:0:3:8080/api/v1/results/by-node/kube-node-2/systemd_logs: Put https://fd00:40::3:0:0:3:8080/api/v1/results/by-node/kube-node-2/systemd_logs: invalid URL port \"40::3:0:0:3:8080\""
```
where fd00:40::3:0:0:3 not in brackets like https://[fd00:40::3:0:0:3]:8080. 
Keeping the call from working.

**What did you expect to happen:**
That the code would bracket all ips so that this works. You can bracket ipv4 or ipv6 addresses and things work well. 
**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Sonobuoy version: 
- Kubernetes version: (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`): 
- Sonobuoy tarball (which contains * below)

**Comment by mauilion** [comment]
to test this you can use kubeadm-dind like:
```
wget https://cdn.rawgit.com/kubernetes-sigs/kubeadm-dind-cluster/master/fixed/dind-cluster-v1.11.sh
$ chmod +x dind-cluster-v1.11.sh
$ export IP_MODE=ipv6
$ ./dind-cluster-v1.11.sh up
## drink coffee waiting for cluster up to finish
$ sonobuoy run
```
cleanup is
```
./dind-cluster-v1.11.sh down
./dind-cluster-v1.11.sh clean
```

**Comment by mauilion** [comment]
pretty sure the bug is here:
https://github.com/heptio/sonobuoy/blob/master/pkg/plugin/aggregation/handler.go#L88-L123

path.host needs to be split into

Hostname and Port and hostname needs wrapped in [ ] if it's an ip.

**Comment by timothysc** [comment]
@liztio this seems like an easy patch to the client/dialer code, could you enqueue this one for this week?

**Comment by mauilion** [comment]
I'm wrong actually the baseurl needs to be bracketed before passing to the handler
