### ISSUE TITLE
Forwarder 500

### ISSUE THREAD

**Issue by weinong** [heptio/sonobuoy#543]
I have seen below error occasionally on my Azure Kubernetes Service cluster. Seems random.

```
time="2018-10-12T23:44:27Z" level=info msg="forwarder information" Scanner ID=29003d0e7ec754ce5ed6530d60a2b0ba Scanner URL="https://scanner.heptio.com"
time="2018-10-12T23:44:28Z" level=info msg="waiting for a done file to appear..." looking for=/tmp/sonobuoy/done
time="2018-10-13T01:20:33Z" level=info msg="done file detected"
time="2018-10-13T01:20:33Z" level=info msg="processing the done file contents"
time="2018-10-13T01:20:33Z" level=info msg="processing result file" result file=/tmp/sonobuoy/201810122344_sonobuoy_698ab9e5-872e-442d-b0b9-89b24413e34e.tar.gz
time="2018-10-13T01:20:33Z" level=info msg="failed to POST data" endpoint="http://127.0.0.1:9898/ingest/" error="non success response code: 500" result file=/tmp/sonobuoy/201810122344_sonobuoy_698ab9e5-872e-442d-b0b9-89b24413e34e.tar.gz
```

**Comment by timothysc** [comment]
@weinong If it eventually succeeds then this is a known issue that recovers.

**Comment by weinong** [comment]
@timothysc got it. is the known issue documented somewhere?

**Comment by timothysc** [comment]
@chuckha Do you know by chance if we have a bug log'd?  It's not really a bug, other then we could change the logline.

**Comment by chuckha** [comment]
we have exactly 1 issue logged and it is to add exponential backoff & retries.

**Comment by johnSchnake** [comment]
This is in the scanner-forwarder code and so the 500 coming from that server could have been any number of things. Need to look into the scanner servers themselves to see if we're seeing any server side errors on a regular basis.

**Comment by jwierzbo** [comment]
I've faced this issue since 17 April..

**Comment by johnSchnake** [comment]
There was another ticket #710 that is a current issue being resolved.

Going to close this at the current time due to the generic error not being much to go on after this much time. The other ticket mentioned, being newer, led to an actual fix since we could more easily repro/debug.
