### ISSUE TITLE
Unable to retrieve tar.gz file after using Sonobuoy retrieve . Command

### ISSUE THREAD

**Issue by bond007007** [heptio/sonobuoy#544]
**What steps did you take and what happened:**
After giving command i.e Sonobuoy retrieve . I am getting only directory folder, which contains two folder inside it i.e meta and plugins.

**What did you expect to happen:**
But instead of getting directory folder, it should give a tar.gz file.

**Anything else you would like to add:**
So I would like to Know the reason of not getting tar.gz file. Because I have debugged very well there is no issue with my Sonobuoy deployment. 
Is there is any new changes in Sonobuoy have been done in recent days from heptio side, or what may be the reason of not getting tar.gz file

**Environment:**
- Sonobuoy version: 0.11.6
- Kubernetes version: (use `kubectl version`): 1.10.4, 1.9.6
- Kubernetes installer & version: 1.10.4, 1.9.6
- Cloud provider or hardware configuration: bare metal
- OS (e.g. from `/etc/os-release`): 
- Sonobuoy tarball (which contains * below)

**Comment by bond007007** [comment]
Thanks for your info. Now the issue has been resolved.
But again i deleted all my Sonobuoy things. And tried freshly, with all the steps including installing golang and all.
Also cloned freshly Sonobuoy on my cluster.
Then when I m giving the command i.e Sonobuoy run, I m getting an error like "the command not found". 
So what may be the reason for this error. As far I checked I did all the steps correctly from installing golang to cloning the heptio-Sonobuoy.

**Comment by timothysc** [comment]
@bond007007 - If you're having different issues feel free to reach out on our slack channel - https://kubernetes.slack.com/messages/sonobuoy

Also, feel free to open a new issue.  Where possible, it helps to have the exact scenario described so we can reproduce the bug.

**Comment by bond007007** [comment]
Thanks @timothysc, I have resolved my issue.

**Comment by deepti-cloudibility** [comment]
@timothysc  How did you resolved it, it will be a help for others.
