### ISSUE TITLE
e2e conformance test results not getting

### ISSUE THREAD

**Issue by bond007007** [heptio/sonobuoy#548]
My e2e conformance testing is getting failed.

But other then that it is working fine( as I am able to get systemd logs and other work load information about cluster and nodes)

So can you please help me for the issue I am facing (for not getting results of e2e conformance testing).

**Comment by timothysc** [comment]
@bond007007 - do you have a tarball that we could inspect, or logs with your run?

**Comment by johnSchnake** [comment]
Closing due to age/activity; if you are still have problems feel free to open up another ticket or reach out to us on our slack channel.
