### ISSUE TITLE
Sonobuoy fails to download image from gcr.io

### ISSUE THREAD

**Issue by krishshenoy** [heptio/sonobuoy#556]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
1. Downloaded heptio sonobuoy 
go get -u -v github.com/heptio/sonobuoy
2. Run make to build the sonobuoy tool
3. Copy the binary sonobuoy to a linux docker container. 
4. Configure kubeconfig to point to my cluster
5.  Execute "sonobuoy run" against a  cluster. 
The sonobuoy pod fails with the following error
**What did you expect to happen:**
Sonobuoy run is successful

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
Sonobuoy is trying to fetch a specific image version with a git commit ID that is no longer available on the image registry. 

kubectl describe pod sonobuoy -n heptio-sonobuoy
 Type     Reason     Age                 From                                                  Message
  ----     ------     ----                ----                                                  -------
  Normal   Scheduled  32m                 default-scheduler                                     Successfully assigned heptio-sonobuoy/sonobuoy to worker-921aedc4-dec8-11e8-8721-068d2fdfd344
  Normal   Pulling    30m (x4 over 32m)   kubelet, worker-921aedc4-dec8-11e8-8721-068d2fdfd344  pulling image "gcr.io/heptio-images/sonobuoy:v0.12.1-2-g81ba7c5"
  Warning  Failed     30m (x4 over 32m)   kubelet, worker-921aedc4-dec8-11e8-8721-068d2fdfd344  Failed to pull image "gcr.io/heptio-images/sonobuoy:v0.12.1-2-g81ba7c5": rpc error: code = Unknown desc = Error response from daemon: manifest for gcr.io/heptio-images/sonobuoy:v0.12.1-2-g81ba7c5 not found
  Warning  Failed     30m (x4 over 32m)   kubelet, worker-921aedc4-dec8-11e8-8721-068d2fdfd344  Error: ErrImagePull
  Warning  Failed     7m (x109 over 32m)  kubelet, worker-921aedc4-dec8-11e8-8721-068d2fdfd344  Error: ImagePullBackOff
  Normal   BackOff    2m (x131 over 32m)  kubelet, worker-921aedc4-dec8-11e8-8721-068d2fdfd344  Back-off pulling image "gcr.io/heptio-images/sonobuoy:v0.12.1-2-g81ba7c5"

**Environment:**
- Sonobuoy version:  v0.12.1-2-g81ba7c5
- Kubernetes version: (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:22:21Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"archive", BuildDate:"2018-10-18T13:27:32Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

- Kubernetes installer & version:  Vmware VKE
- Cloud provider or hardware configuration: AWS
- OS (e.g. from `/etc/os-release`):   linux
- Sonobuoy tarball (which contains * below)

**Comment by stevesloka** [comment]
Hey @krishshenoy I know this has been idle for some time now, but are you still having issues running scans with the latest versions?

**Comment by stevesloka** [comment]
@krishshenoy I'm going to close this issue now as some time has passed and newer versions I don't think have the same issue you were describing. 

Please re-open this issue if that is not the case and we can jump in and take a look.

**Comment by gandazgul** [comment]
I'm having a similar issue with k8s v1.13 I get authentication required for downloading gcr.io/heptio-images/sonobuoy:0.13.0

**Comment by joaovitor** [comment]
I faced this issue running sonobuoy in a local minikube cluster today.

## Cluster setup:

```shell
minikube start
```

Run sonobuoy:

```shell
sonobuoy run --config sonobuoy-config.json --mode=quick --wait
```

## Verified the status

```shell
sonobuoy status
```
OUTPUT
```text
ERRO[0000] error attempting to run sonobuoy: pod has status "Pending"
```

## Get details about the error from logs

```shell
 kubectl logs pod/sonobuoy -n heptio-sonobuoy -f
```
OUTPUT
```text
Error from server (BadRequest): container "kube-sonobuoy" in pod "sonobuoy" is waiting to start: trying and failing to pull image
```

## Get details about the error from pod status

```shell
kubectl get pod/sonobuoy -n heptio-sonobuoy -o yaml | yq r - 'status.containerStatuses[*].state.waiting.message'
```
OUTPUT
```text
- Back-off pulling image "gcr.io/heptio-images/sonobuoy:0.14.2"
```

Verified the list of [sonobuoy images available at gcr](https://console.cloud.google.com/gcr/images/heptio-images/GLOBAL/sonobuoy?gcrImageListsize=30).

```shell
kubectl edit pod/sonobuoy -n heptio-sonobuoy -o yaml
```

## Solution

Changed the image from:

gcr.io/heptio-images/sonobuoy:0.14.2
to
gcr.io/heptio-images/sonobuoy:**v**0.14.2

Wait for completion and it **worked**.

**Comment by johnSchnake** [comment]
Thanks; will take a look at this right away.

**Comment by johnSchnake** [comment]
@joaovitor Can you confirm the version of Sonobuoy you are using? By the sound of it (not using the right registry/image for the run) that sounds like you may be using an out of date Sonobuoy version.

**Comment by joaovitor** [comment]
@johnSchnake I got my Sonobuoy from brew.
It is the most updated [version there](https://formulae.brew.sh/formula/sonobuoy#default) 0.14.2.
The problem can be on the brew formula it is showing version 0.14.2 there not v0.14.2 as it shows on gcr.io.

**Comment by johnSchnake** [comment]
@joaovitor Definitely a homebrew issue which I (curiously) dont have any context on. I didnt even know you could get sonobuoy through brew. I created https://github.com/heptio/sonobuoy/issues/715 to track this separately.

In the meantime, I recommend you just download the binary from our releases tab here: https://github.com/heptio/sonobuoy/releases/tag/v0.14.2
