### ISSUE TITLE
 Allow testing with DenyEscalatingExec admission plugin

### ISSUE THREAD

**Issue by andrewrynhard** [heptio/sonobuoy#558]
**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

I would like to run sonobuoy with `DenyEscalatingExec` admission plugin enabled. A few of the networking tests exec into a privileged container.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
The project I am working on will enable and enforce this on all clusters. To pass the conformance, I would have to run the tests under conditions that users of my project will not be under.

**Environment:**

- Sonobuoy version: `v0.12.0`
- Kubernetes version: (use `kubectl version`): `v1.13.0-alpha.3`
- Kubernetes installer & version: kubeadm `v1.13.0-alpha.3`
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`): https://github.com/autonomy/talos

**Comment by andrewrynhard** [comment]
@timothysc good to know. Do you happen to know how this might affect acceptance into https://github.com/cncf/k8s-conformance?

**Comment by timothysc** [comment]
So I'm going to close the issue here, b/c it's not the runner, but the tests themselves.
