### ISSUE TITLE
Failing to launch a plugin shouldn't exit the aggregator server

### ISSUE THREAD

**Issue by hev** [heptio/sonobuoy#559]
**What steps did you take and what happened:**
I tested sonobuoy on both a gke cluster and pks cluster. On PKS the tests never complete even after several hours. 

```
hev@Adams-MacBook-Pro-2 ~ $ sonobuoy status
PLUGIN		STATUS	COUNT
e2e		running	1
systemd_logs	running	3

Sonobuoy is still running. Runs can take up to 60 minutes.
hev@Adams-MacBook-Pro-2 ~ $ kubectl get pods -n heptio-sonobuoy
NAME       READY   STATUS    RESTARTS   AGE
sonobuoy   1/1     Running   0          16h
hev@Adams-MacBook-Pro-2 ~ $
```

**What did you expect to happen:**
On GKE after doing a `sonobuoy run` and waiting an hour so the e2e and systemd_logs tests were completed. 

**Anything else you would like to add:**
This is likely a change required in PKS but I am not sure what that is. Logs fro sonobuoy below.

```
time="2018-11-20T23:14:29Z" level=info msg="Scanning plugins in ./plugins.d (pwd: /)"
time="2018-11-20T23:14:29Z" level=info msg="Scanning plugins in /etc/sonobuoy/plugins.d (pwd: /)"
time="2018-11-20T23:14:29Z" level=info msg="Directory (/etc/sonobuoy/plugins.d) does not exist"
time="2018-11-20T23:14:29Z" level=info msg="Scanning plugins in ~/sonobuoy/plugins.d (pwd: /)"
time="2018-11-20T23:14:29Z" level=info msg="Directory (~/sonobuoy/plugins.d) does not exist"
time="2018-11-20T23:14:29Z" level=info msg="Filtering namespaces based on the following regex:.*|heptio-sonobuoy"
time="2018-11-20T23:14:29Z" level=info msg="Namespace default Matched=true"
time="2018-11-20T23:14:29Z" level=info msg="Namespace heptio-sonobuoy Matched=true"
time="2018-11-20T23:14:29Z" level=info msg="Namespace kube-public Matched=true"
time="2018-11-20T23:14:29Z" level=info msg="Namespace kube-system Matched=true"
time="2018-11-20T23:14:29Z" level=info msg="Namespace pks-system Matched=true"
time="2018-11-20T23:14:29Z" level=info msg="Starting server Expected Results: [{ e2e} {vm-2e6f9853-0e41-423a-6202-73805abaace9 systemd_logs} {vm-a27b4c0f-3d8e-46c2-6779-88e3f409d5b4 systemd_logs} {vm-c7bbf82b-e45b-489b-5d79-d1eecad49e0c systemd_logs}]"
time="2018-11-20T23:14:29Z" level=info msg="Starting annotation update routine"
time="2018-11-20T23:14:29Z" level=info msg="Running plugin" plugin=e2e
time="2018-11-20T23:14:29Z" level=info msg="Starting aggregation server" address=0.0.0.0 port=8080
time="2018-11-20T23:14:29Z" level=info msg="Running plugin" plugin=systemd-logs
time="2018-11-20T23:14:29Z" level=info msg="Last update to annotations on exit"
time="2018-11-20T23:14:29Z" level=error msg="error running plugins: error running plugin systemd-logs: could not create DaemonSet for daemonset plugin systemd-logs: DaemonSet.apps \"sonobuoy-systemd-logs-daemon-set-58f3dfbb6da94645\" is invalid: spec.template.spec.containers[0].securityContext.privileged: Forbidden: disallowed by cluster policy"
time="2018-11-20T23:14:29Z" level=info msg="Running non-ns query"
time="2018-11-20T23:14:29Z" level=error msg="error querying CustomResourceDefinitions: the server could not find the requested resource"
time="2018-11-20T23:14:29Z" level=info msg="Collecting Node Configuration and Health..."
time="2018-11-20T23:14:29Z" level=info msg="Creating host results for vm-2e6f9853-0e41-423a-6202-73805abaace9 under /tmp/sonobuoy/20346e1c-8383-4136-9591-f6acfed2a3df/hosts/vm-2e6f9853-0e41-423a-6202-73805abaace9\n"
time="2018-11-20T23:14:29Z" level=info msg="Creating host results for vm-a27b4c0f-3d8e-46c2-6779-88e3f409d5b4 under /tmp/sonobuoy/20346e1c-8383-4136-9591-f6acfed2a3df/hosts/vm-a27b4c0f-3d8e-46c2-6779-88e3f409d5b4\n"
time="2018-11-20T23:14:30Z" level=info msg="Creating host results for vm-c7bbf82b-e45b-489b-5d79-d1eecad49e0c under /tmp/sonobuoy/20346e1c-8383-4136-9591-f6acfed2a3df/hosts/vm-c7bbf82b-e45b-489b-5d79-d1eecad49e0c\n"
time="2018-11-20T23:14:31Z" level=info msg="Running ns query (default)"
time="2018-11-20T23:14:33Z" level=info msg="Running ns query (heptio-sonobuoy)"
time="2018-11-20T23:14:34Z" level=info msg="Collecting Pod Logs..."
time="2018-11-20T23:14:34Z" level=error msg="the server rejected our request for an unknown reason (get pods sonobuoy-e2e-job-f2f7a7acac314762)"
time="2018-11-20T23:14:35Z" level=info msg="Running ns query (kube-public)"
time="2018-11-20T23:14:37Z" level=info msg="Running ns query (kube-system)"
time="2018-11-20T23:14:40Z" level=info msg="Running ns query (pks-system)"
time="2018-11-20T23:14:42Z" level=info msg="Results available at /tmp/sonobuoy/201811202314_sonobuoy_20346e1c-8383-4136-9591-f6acfed2a3df.tar.gz"
time="2018-11-20T23:14:42Z" level=info msg="no-exit was specified, sonobuoy is now blocking"
```

**Environment:**

- Sonobuoy version: 0.12.1
- Kubernetes version: (use `kubectl version`): 1.12.2
- Kubernetes installer & version: PKS 1.2.2-build.3
- Cloud provider or hardware configuration: GCP
- OS (e.g. from `/etc/os-release`): 
- Sonobuoy tarball (which contains * below)

**Comment by timothysc** [comment]
@ahevenor - If you run `sonobuoy logs -f` on the PKS cluster you can detect where it is getting wedged.  
If there is a long hang/delay the tests have gotten into a wedged state and will eventually hit the default timeout and hard exit.

**Comment by ahevenor** [comment]
Hmm. Surprisingly it didn't timeout and panic even over the long weekend. I assume it's getting tripped up here:

```
time="2018-11-20T23:14:34Z" level=error msg="the server rejected our request for an unknown reason (get pods sonobuoy-e2e-job-f2f7a7acac314762)"
```

Interestingly the pod name I see in my cluster doesn't have that GUID which is not something I have seen before. 

```
kubectl get pods --all-namespaces
NAMESPACE         NAME                                    READY   STATUS    RESTARTS   AGE
heptio-sonobuoy   sonobuoy                                1/1     Running   0          5d
kube-system       heapster-6d5f964dbd-6kvj2               1/1     Running   0          5d
kube-system       kube-dns-6b697fcdbd-4h52x               3/3     Running   0          5d
kube-system       kubernetes-dashboard-785584f46b-s8qqj   1/1     Running   0          5d
kube-system       metrics-server-5f68584c5b-9lg5l         1/1     Running   0          5d
kube-system       monitoring-influxdb-54759946d4-xts57    1/1     Running   0          5d
kube-system       telemetry-agent-bc95dc6dc-gl86p         1/1     Running   0          5d
pks-system        fluent-bit-469sq                        1/1     Running   0          5d
pks-system        fluent-bit-4zgvk                        1/1     Running   0          5d
pks-system        fluent-bit-spgf6                        1/1     Running   0          5d
pks-system        sink-controller-7c85744bd6-rjnd5        1/1     Running   0          5d
```

**Comment by timothysc** [comment]
Can you retrieve and post the tarball for inspection?

**Comment by ahevenor** [comment]
Yeah. Here it is as zip from a fresh deploy 
[201811061615_sonobuoy_bee1af96-bfb8-427c-a566-e76011ffcf7c.zip](https://github.com/heptio/sonobuoy/files/2616868/201811061615_sonobuoy_bee1af96-bfb8-427c-a566-e76011ffcf7c.zip)

**Comment by timothysc** [comment]
@ahevenor - that tarball looks like a successful 1.10.7 scan of a gke cluster.  

Not a tarball from pks.

**Comment by ahevenor** [comment]
Oops. You are correct. I was fooled by finder. This one should be the failed run from PKS. 
[201811261827_sonobuoy_bb01a8cf-43bc-43ee-9b02-1b21fec97412.zip](https://github.com/heptio/sonobuoy/files/2630833/201811261827_sonobuoy_bb01a8cf-43bc-43ee-9b02-1b21fec97412.zip)

**Comment by timothysc** [comment]
@chuckha do you have some cycles to look at this?

**Comment by chuckha** [comment]
The logs indicate there is an issue with the systemd plugin. In particular, a cluster policy:

`time="2018-11-20T23:14:29Z" level=error msg="error running plugins: error running plugin systemd-logs: could not create DaemonSet for daemonset plugin systemd-logs: DaemonSet.apps \"sonobuoy-systemd-logs-daemon-set-58f3dfbb6da94645\" is invalid: spec.template.spec.containers[0].securityContext.privileged: Forbidden: disallowed by cluster policy"`

**Comment by ahevenor** [comment]
@chuckha The resolution for this on the PKS I expect is handled by the underlying [CFCR bosh release](https://github.com/cloudfoundry-incubator/kubo-release). It's probably easiest for me to dig into that side of the issue as we have new features and defaults coming out around security policies but I'd also be happy to give you a download on CFCR and PKS if that's helpful. 

On the sonobuoy side ideally I'd like to see the test fail out and report an improved error message of some sort. @timothysc had mentioned it should have panicked but in this case it didn't for some reason.

**Comment by phenixblue** [comment]
@ahevenor You need to enabled privileged containers in the plan for the PKS tile.

**Comment by johnSchnake** [comment]
Peeking at the code it does seem like there is a problem in how we report issues when starting a plugin; it interrupts the aggregator logic in an unusual way that may be cutting off the expected path of marking the plugin as failed. Seeing as how these issues point to problems in the cluster setup (at least as far as running tests are concerned) this should be remedied. More investigation is needed to look at the code path/repro though.
