### ISSUE TITLE
Update image registry default in k/k >=1.14

### ISSUE THREAD

**Issue by rdodev** [heptio/sonobuoy#564]
**Describe the solution you'd like**
As part of the sonobuoy build to match with k/k 1.14 change container image registry default to point to gcr.io 

/assign @timothysc

**Comment by johnSchnake** [comment]
This seems to be the case already? Are you talking about for the sonobuoy image? kube-conformance (which ours and upstream use gcr.io).

Can this be closed @rdodev or are you talking about a different value?

**Comment by rdodev** [comment]
@johnSchnake this was >2 months ago, which means it was purged from my memory. However, I opened this issue as per request from @timothysc so he might have a better answer.

**Comment by johnSchnake** [comment]
I'm going to close; I think that maybe this was referencing the desire to use the upstream conformance image #593 , or maybe (a stretch) to reference allowing users to modify the testing registries used (#160) Either way I think this is done.
