### ISSUE TITLE
Retrieve should be able to name or list the created file

### ISSUE THREAD

**Issue by johnSchnake** [heptio/sonobuoy#594]
**Describe the solution you'd like**
I'd like to be able to name the tar file that is created on my machine via `sonobuoy retrieve`. The reason is that it simplifies scripting:

```
sonobuoy retrieve results.tar.gz
tar -xvf results.tar.gz
```
Currently I have to do something more awkward to find the name of the most recently created tar.

**Anything else you would like to add:**
Alternative solution:

Make `sonobuoy retrieve` output the name of the file that is created to stdout so that I can do something like

```
file=$(sonobuoy retrieve)
tar -xzf $file
```

**Comment by johnSchnake** [comment]
This is a small item but will make it easier to script around and improve our readme about how to get started.

**Comment by stevesloka** [comment]
The first version seems like you're asking for the result file `results.tar.gz` vs the second version is just using the resulting name.

**Comment by johnSchnake** [comment]
Correct; it was an either/or solution. I think the 2nd solution is actually fine (and easy to implement). I went ahead and did that (about to put up PR) so that I can improve the readme.

The problem with the first (specifying the name) is that the tar logic is pretty generic and in theory could create multiple files on the local machine. If we just print the names out then it still enables the user but avoids awkward complications/ambiguities.
