### ISSUE TITLE
Add support for running scheduled e2e tests

### ISSUE THREAD

**Issue by alexbrand** [heptio/sonobuoy#600]
As a platform operator, I want to be able to run scheduled Sonobuoy runs to ensure that my cluster is in conformance throughout its lifetime. I want to be able to configure the cadence on which the conformance tests are run.

If the cluster is conformant, a new conformance test is scheduled to occur in the future. In the case that cluster is out of conformance, that is, one or more test failures occurred during the test, I would like to be alerted or notified.

Open questions:
- Is the conformance test "heavy" on the cluster? Will it disrupt running applications?

**Comment by timothysc** [comment]
Sonobuoy is a tool to be used by other tools, and execution of sonobuoy in a cron-ish fashion can be done in many ways, so is probably outside the scope of sonobuoy.
