### ISSUE TITLE
Show list of tests in upstream image

### ISSUE THREAD

**Issue by stevesloka** [heptio/sonobuoy#604]
**Describe the solution you'd like**
Would like a way to show a list of images that are used in the upstream e2e tests to have an understanding of what is required and it's current location. 

The command could look something like this:
```
$ sonobuoy e2e images --list
```

**Comment by stevesloka** [comment]
Hey @johnSchnake thoughts on the command above? I was also thinking maybe something like the following but is similar to the download and upload so didn't want to be more confusing.

```
$ sonobuoy list e2e
```

**Comment by johnSchnake** [comment]
I think that this and #605 are effectively the same command with different flags. One just being a dry-run/list version of the one that will actually go and do the work.

Perhaps
```
sonobuoy images e2e //implicit list; download=false
sonobuoy images e2e --download

// or we could have some sort of output option which would be more extensible
sonobuoy images e2e -o text
sonobuoy images e2e -o tar
sonobuoy images e2e -o json //etc
```

**Comment by stevesloka** [comment]
I like the `sonobuoy images e2e` route, but we'd need to wire up an interface to plugins to let them implement since it now inherently should be available to all plugins (which is the best long term design).
