### ISSUE TITLE
Wait should emit some output

### ISSUE THREAD

**Issue by johnSchnake** [heptio/sonobuoy#607]
**Describe the solution you'd like**
The `--wait` functionality of run/delete is great but run, since it can take so long, can really be difficult for a user to know if the process is still running as expected.

I think we should have a reasonable default that looks good to users sitting in front of the machine but allow an ovverride via a flag so that people in other situations/preferences can override for their use case.

Suggestion:
Default: A simple spinner that might also show the statement like "sonobuoy state is xyz, this command will return after it completes or errors"

Alternative options via flag:
 - just lazily output a stream of dots every few min so it doesnt read as a dead process. Can be ugly if its a long run but may really be the preference of some people who just want an 'alive' signal.

 - no output, just wait quietly as we do today

**Anything else you would like to add:**
The reason I say the default should be the good looking but (maybe) slightly less robust one is that people writing CI scripts or with strong preferences dont mind adding the flag. People typing quickly just getting it working will want/like the nicer output IMO.

**Comment by stevesloka** [comment]
Very similar to https://github.com/heptio/sonobuoy/issues/354

**Comment by johnSchnake** [comment]
I agree it is similar in that if you gave progress then you could output that while you wait. I think the way in which it is different is that the 'progress' ticket is pretty architectural and needs to have a lot of thought about how the system will work with all the plugins and such.

This is a much smaller scoped (as your tags imply) issue. I think that effectively we can implement this in the short term while we design/build the progress indicator stuff. Then once that is working and working well, it would become the default (rather than a spinner/general status) for instance.

**Comment by stevesloka** [comment]
Sure, not talking implementation time, just discussing features so it gets put into consideration.

**Comment by ekj1711** [comment]
I am interested. Can i try this @johnSchnake ? 
Can we use "github.com/briandowns/spinner" to show the progress? Is it required only for run/delete commands?

**Comment by johnSchnake** [comment]
@ekj1711 Awesome, thanks for another contribution :)
