### ISSUE TITLE
Improve UX for specifying additional plugins

### ISSUE THREAD

**Issue by stevesloka** [heptio/sonobuoy#633]
**Describe the solution you'd like**
Currently, Sonobuoy has 1st class support for two plugins (`e2e` and `systemd-logs`) when running `sonobuoy run` or `sonobuoy gen`.  

When users want to implement their own custom plugins or change how the current ones are implemented, it's a very manual process:

- Sonobuoy gen
- Edit the yaml/config
- Apply the yaml

**Comment by johnSchnake** [comment]
xref #405

**Comment by stevesloka** [comment]
Ahh I missed that, closing this one.
