### ISSUE TITLE
ARM should be removed

### ISSUE THREAD

**Issue by johnSchnake** [heptio/sonobuoy#636]
arm64 support is currently something that we do not test at all and dont really want to spend the cycles owning.

We should remove this and let the community fork/maintain an arm compatible version if it is of interest.

**Comment by stevesloka** [comment]
I was the driver of removing this, but thinking out loud if we should keep the Sonobuoy build, but take away the E2E testing ability (since it's broken upstream). 

We could fix the systemd_logs plugin to work, as well as allow other developers to still build their own plugins if desired.

**Comment by vielmetti** [comment]
attn @lubinsz

**Comment by johnSchnake** [comment]
>  take away the E2E testing ability (since it's broken upstream).

Is that 100% accurate? I think in the past you mentioned how the tests themselves use images which may not have ARM counterparts, but I'm assuming that some of the tests work? The conformance image itself is made for arm https://github.com/kubernetes/kubernetes/tree/9c5cf3ccf77225fd38772a5a9162d6dc7f818d20/cluster/images/conformance. And with the new ability to change the registry for images it seems like you could even be pointing them to a registry which has custom built arm versions.

My biggest concern about arm w.r.t. sonobuoy is that currently we are not really testing it and dont feel like we have a lot of signal on it if it were to be malfunctioning.

**Comment by johnSchnake** [comment]
I think it was mentioned today at a sig-arch meeting that arm actually is being test upstream but on testgrid there is just a stale listing: https://testgrid.k8s.io/conformance-arm#Summary

@dims I think you mentioned on the call that you know it was being used and could pass conformance, is that right? Should we be looking in another place?

**Comment by dims** [comment]
There's some sort of reporting problem we need to dig into @johnSchnake

**Comment by vielmetti** [comment]
I think there will be a quorum of interested and capable parties to look at this support assembling at next week's Linaro Connect in Bangkok. I will be certain to bring this up there as well as to report back any concrete results.

**Comment by johnSchnake** [comment]
From Slack (via @dims):

> fyi, CI for Kind on ARM64 - http://status.openlabtesting.org/builds?job_name=kind-integration-test-arm64 (cc @bentheelder) - courtesy of @Kevin_Zheng and team

So it seems to be running and capable of getting green. Not sure why the testgrid implementation wasn't fixed, but probably just had to do with who was doing the work and what options they personally had? I thought testgrid was the one, true CI we cared about? Maybe I'm just wrong on that front.

**Comment by BenTheElder** [comment]
> https://testgrid.k8s.io/conformance-arm#Summary

note that this is not exactly upstream, we receive some limited results on testgrid from some CI @lubinsz runs

**Comment by johnSchnake** [comment]
OK; at the end of the day it still just seems like ARM for sonobuoy should stick around. Closing.
