### ISSUE TITLE
Prevent Sonobuoy from being deployed in an existing namespace (or at least kube-system)

### ISSUE THREAD

**Issue by krisdock** [heptio/sonobuoy#677]
**Describe the solution you'd like**
Prevent using `sonobuoy run -n <namespace>` to deploy to an existing namespace (kube-system in particular). Doing so seems unnecessary (unless someone can think of a use case where it would be needed) and makes cleaning up Sonobuoy resources a pain. 

At the very least, maybe prevent it from ever being deployed in kube-system and print a warning with a y/n prompt if attempting to deploy into any other existing namespace.

**Anything else you would like to add:**

**Environment:**

- Sonobuoy version: 0.14.1
- Kubernetes version: (use `kubectl version`): 1.14
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Comment by johnSchnake** [comment]
I'm not sure of the use case where you really ever NEED to run in an existing namespace.

Currently, there is a preflight check that errors if there is a sonobuoy pod in the given namespace. This could be tightened to just err if the namespace already exists.

This makes sense to me for a few reasons:
 1) The existing preflight check ensures sonobuoy pod doesnt exist in that namespace; but that isnt' really a great check anyways (just one indicator) that a sonobuoy run had been executed. If you didn't have that preflight check the run would still fail when it tries to create a pod/service acct/etc with all the same details. So the preflight check doesn't accomplish a lot on its own.
 2) Like we agree on, cleaning up Sonobuoy could be an issue in an existing namespace which you don't want to blow up entirely afterward.
 3) Adding more complicated cleanup logic would be another solution, but it would be less trivial to implement and would complicate the maintenance of the code going forward and make it possible to have bugs where we leak other resources or delete things we didn't mean to.
 4) I dislike having to have a) add flags to skip the new logic and b) adding interactive flows to confirm the choice. In both of those cases we complicate the UX a bit (more flags that most people dont ever need and possible bugs in the interactive flow. Moving this into the preflight check means that most users never have to worry about it anyways, there are no new flags, and if the user _really_ wants to do this they can skip the preflight checks and we'd be able to say we warned them when things go wrong.

How does that sound to you @krisdock ? Tighten existing preflight check which means it will always error by default if they try this and if they want to do it anyways they can skip preflight checks. (No special logic for kube-system though)

**Comment by krisdock** [comment]
@johnSchnake that sounds great. Thank you.

**Comment by leodotcloud** [comment]
For anyone landing here looking to run sonobuoy in an existing namespace, you need to pass the below flag:

```
--skip-preflight=existingnamespace
```

Example:

```
sonobuoy run --namespace myns --skip-preflight=existingnamespace
```
