### ISSUE TITLE
Provide flags to disable non plugin related operations

### ISSUE THREAD

**Issue by leodotcloud** [heptio/sonobuoy#682]
**Describe the solution you'd like**
When using sonobuoy with a plugin, (https://github.com/heptio/sonobuoy/blob/master/pkg/discovery/discovery.go#L111) there is no need to run the other steps in this function. Like there is no need to run the queries in different namespaces. Having flags like `--disable-queries` might be useful to avoid breaking usage. 

If this is an acceptable thing, I can quickly make a PR with the changes.

**Comment by johnSchnake** [comment]
Hi @leodotcloud ,

A few thoughts:
 - I agree that disabling queries should be easier than it currently is in case you really don't want that data

> when using sonobuoy with a plugin ... there is no need to run the other steps...
 - I disagree on that point. Sometimes we are only curious in the plugin results itself, but often when the plugin may report an error it won't have enough message to diagnose the problem itself. It helps to have the extra data to describe the state of the cluster.

 - There a few tickets (#627 #630 #432  ) related to the queries but they just didn't make it into this milestone. It seems like you'd agree with the end goal: queries shouldn't be the job of sonobuoy directly. The eventual goal is to get queries into their own plugin. In order do that we also wanted to continue to ensure they were run at the _end_ of the run (it helps diagnose leaked resources from plugins for instance) so it is blocked by #627 

 - There are ways to drastically reduce what queries happen but they are _not_ clear to most users. Changing the namespace filter for the queries to a non-existent namespace would lead to no data (other than the heptio-sonobuoy one) or updating the `Resources` field of `config.json` to be empty would do the same thing. Though, in both of those cases, you still query the heptio-sonobuoy namespace.

All that being said we (1) want to make things easier for users and (2) even though we _intend_ for queries to go to their own plugin which could be skipped entirely I have no idea of how priorities will shift. I think that a flag/field for skipping the query logic would be appropriate.

Tag me in the PR and thanks for the contribution!

**Comment by johnSchnake** [comment]
I'm considering nixing this in light of some discussion about what functionality already exists. The idea is that we should be able to just stop the queries _almost_ completely by just setting `Resources` to the empty slice.

However I just found a bug that was causing this to not be the case. After that goes it, it seems like it is just about making it more well known how to tweak query options. I'm open to expanding that, but I don't think the flag is strictly necessary then.

Will update again once that goes in with a more clear example and caveats about it.

**Comment by johnSchnake** [comment]
With the fixes that went in this is fairly easy, just needing to provide the empty (non-nil) resources config setting. The only thing that is gathered are the logs for the namespace sonobuoy was in which is helpful for understanding many results anyways.

```
$ sonobuoy gen config|jq '.Resources=[]'|jq '.WorkerImage="gcr.io/heptio-images/sonobuoy:master"'>noquery.conf
$ sonobuoy run --mode=quick --config=noquery.conf --wait
```

Note: the worker image has to be set here because this is on master right now (and I just pushed a publish master image) but not on the last "released" version.

You could also use `echo` to create the config file:
```
echo '{"Resources":[], "WorkerImage":"gcr.io/heptio-images/sonobuoy:master"}' > noquery.conf
```

For now I'm going to close this since there is an existing workaround. If you feel strongly that you still want these log queries removed as well then we can continue the discussion.
