### ISSUE TITLE
Interesting situation with namespaces...

### ISSUE THREAD

**Issue by akara1189** [heptio/sonobuoy#695]
Heya folks. Forgive me if this has indeed been covered before but...I've not seen a way to handle our particular situation (Without a lot of regex and filtering on our log aggregator)...

If I wanted to keep the conformance tests running in a given Namespace, instead of spawning new ones for every test...is there a 'built-in' way to finagle that? We have a logging solution that literally generates AWS CloudWatch log groups based on the K8s Namespace the pods are running in. The Namespaces created at test time ARE cleaned up and it seems to do so cleanly...but of course, it leave a number of log groups sitting in CW. We have other methods to stale out old groups and so on but if there's an easier way to tweak that, that I just haven't seen, I'd love to know! 

Thanks everyone!

**Comment by johnSchnake** [comment]
Currently there isn’t another approach possible but I do think this has been mentioned before. Any details you can share about your workflow would be helpful to assess the need.

It would require upstream changes and I’m not sure how feasible it is, but I can bring it up in some of the upstream meetings.

**Comment by akara1189** [comment]
Understandable! Our situation may be RELATIVELY unique. I could post our fluentd config if that would help... I'd have to wait until Monday but if it's worth discussion I'd be more than happy to dig into it. :)

**Comment by akara1189** [comment]
Sorry this took me so long! I was horribly sick yesterday. Here's the Fluentd config file snippet I was referring to before: 

<filter kubernetes.**>
      @type record_transformer
      enable_ruby true
      <record>
        namespace "#{ENV['LOG_GROUP_NAME']}/${record.dig('kubernetes', 'namespace_name')}"
      </record>
      remove_keys [ "$.kubernetes.container_image", "$.kubernetes.container_image_id", "$.kubernetes.pod_id", "$.kubernetes.master_url", "$.kubernetes.namespace_id", "$.docker", "$.stream" ]
    </filter>
    <match kubernetes.**>
      @type cloudwatch_logs
      @id out_cloudwatch_logs
      log_group_name_key namespace
      auto_create_stream true
      use_tag_as_stream true
      remove_log_group_name_key true
    </match>

It pulls the namespace information from the API-server's response and creates a new field in the log entry before passing it to the Cloudwatch output plugin .The CW output plugin will, as is seen in the 'log_group_name_key' directive, create the log group based on that namespace field. As one could imagine, the usual process creates a large number of log groups based on those temporary namespaces :)

**Comment by akara1189** [comment]
As a side-notes, I was wondering (I'm sorry if this isn't a perfect forum for the question, so to speak... I figure the above discussion gives better context to the question) - It *used* to be that the test pods had 'e2e' slapped on the pod names and that allowed me to filter those... I don't know what I did, but recently the test pods have naming JUST based on the test type (statefulset-01, 02, etc...like that) and that makes filtering them in Fluent nigh-impossible. Is THAT something I can fix/adjust?...

**Comment by johnSchnake** [comment]
Each test in the k8s suite is creating pods on its own, though there are a few helpers that centralize some of the logic in a few cases. Typically the tests just come up with their own name for a test pod.

The main 'known' for filtering like that is that the test namespaces themselves have an `e2e` prefix (I thought this was true but am failing to find the reference) and they will have the label `e2e-framework`: https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/framework.go#L211-L215 Does that help?

**Comment by akara1189** [comment]
Hm. Actually, it does! I might be able to pull the label data and retag based on it... Worth a try anyway! Thanks John. You've been super helpful! :)
