### ISSUE TITLE
Status error if no plugins run

### ISSUE THREAD

**Issue by johnSchnake** [heptio/sonobuoy#696]
**What steps did you take and what happened:**
 - Run a config that will run _no_ plugins defined (this was actually on accident though)
 - used the `--wait` flag
 - Sonobuoy command hung forever, but when using `sonobuoy logs` I could see the aggregator ran and completed, but the status was not updated so `--wait` failed to think Sonobuoy was done.

**What did you expect to happen:**
 - Sonobuoy should realize the aggregator done and/or that it was no longer waiting for results.

**Anything else you would like to add:**
I know there are some checks to already update the status once the aggregator is done with getting results, so we need to check the error handling there.

From `sonobuoy logs`:
```
time="2019-04-29T13:12:14Z" level=error msg="error updating pod status: failed to get the existing status: missing status annotation \"sonobuoy.hept.io/status\""
time="2019-04-29T13:12:14Z" level=info msg="Results available at /tmp/sonobuoy/201904291312_sonobuoy_d87f1ed5-3a3a-48f0-ac69-587890a9657a.tar.gz"
time="2019-04-29T13:12:14Z" level=info msg="no-exit was specified, sonobuoy is now blocking"
```

From `sonobuoy status`:
```
sonobuoy status
ERRO[0000] error attempting to run sonobuoy: missing status annotation "sonobuoy.hept.io/status"
```

The issue is that in the `discovery.Run` it has logic to _update_ the pod status but will assume the logic in the aggregator will have already set a status. In an effort to not overwrite those results it errors out if it can't get the existing status.

The problem is that if you dont have plugins then you never write an initial status and then you err out when you try to write the final `done` status.

We should just make the logic permissive of `no status` type errors so it can write the initial one.

**Environment:**

- Sonobuoy version: 0.14.1

**Comment by johnSchnake** [comment]
`GetStatus` specifies (in the comments) that it is going to return an error if the annotation is missing but perhaps the best thing to do there is just return an empty status object. Either that or we need to provide either a specific error type/interface/etc that the user can be expected to interpret accordingly.

**Comment by blc1996** [comment]
Hi. It this fixed already? I still see this error message occasionally when I run Sonobuoy 1.18.3 and 1.19.0 with no plugins.
