### ISSUE TITLE
Fix race in logs gathering

### ISSUE THREAD

**Issue by johnSchnake** [heptio/sonobuoy#708]
**What steps did you take and what happened:**
`kubectl apply -f test.yaml && sonobuoy logs`

will hang every time because the pod isn't yet in the created phase leading to an error when creating the log streamer. The problem is that the error goes onto an unbuffered channel and needs to be read before the method returns. However, other logic exists that says to keep reading until the channel of messages is closed before grabbing the error from the error channel.

This results in deadlock since the closing of the channels doesnt happen until the `stream()` method is done, which is trying to put the error on the channel.

**What did you expect to happen:**
`sonobuoy logs` should just report the error and exit.

**Anything else you would like to add:**
In the kubectl example above, the test yaml can be any pod really; dealers choice. Using kubectl run is different though since it is waiting for certain events to be complete rather than just firing off the creation requests.

Sonobuoy version 0.14.2

**Comment by ashish-amarnath** [comment]
This will also leak goroutines.
