### ISSUE TITLE
Broken Link in [Conformance Testing Docs]: https://github.com/heptio/sonobuoy/blob/master/docs/conformance-testing.md

### ISSUE THREAD

**Issue by rajakshay** [heptio/sonobuoy#711]
This link is broken for [e2e Config]: https://github.com/heptio/sonobuoy/blob/master/examples/quickstart.yaml#L133
on the page: [Conformance Testing]: https://github.com/heptio/sonobuoy/blob/master/docs/conformance-testing.md

**Comment by johnSchnake** [comment]
Thanks for the issue @rajakshay ; will get that fixed up and take it as an opportunity to audit the other links too.
