### ISSUE TITLE
DNS tests assume "cluster.local"

### ISSUE THREAD

**Issue by shettich** [heptio/sonobuoy#733]
**What steps did you take and what happened:**
The DNS tests seems to all assume the cluster is setup with a dns domain of "cluster.local"

**What did you expect to happen:**
It should test against the configured domain name

**Environment:**

- Sonobuoy version: 0.14.2
- Kubernetes version: 1.14.1
- Kubernetes installer & version: kubespray

**Comment by johnSchnake** [comment]
Are you referring to the actual e2e tests? I don't believe Sonobuoy makes any sort of check that assumes `cluster.local`. Our preflight checks ensure that dns exists, but that is pretty much it. You can also skip those checks so it is completely non-blocking.

If you think the e2e test should be modified, you should create a ticket upstream at https://github.com/kubernetes/kubernetes/issues

Please clarify; if there is some uncertainty about where the check is done, please provide a snippet from the logs so that I can help triage.

**Comment by shettich** [comment]
Yes, e2e.  It (e2e) already has a flag for this, it just need to be plumbed through to sonobuoy somehow

**Comment by johnSchnake** [comment]
https://github.com/kubernetes/kubernetes/blob/master/cluster/images/conformance/run_e2e.sh is the script that runs the e2e tests and it is in the k/k repo.

I'll file an issue to update that image. If someone picks it up, sonobuoy can support it right away by utilizing the new flag for generic plugin env vars, e.g. `--plugin-env e2e.FOO=BAR`

There are lots of e2e flags which the e2e image doesnt surface to users. If you could think of a way to be more generic and allow callers to set their own flags that would be great. Maybe it just needs a generic `E2E_FLAGS` env var which gets appended to the call (and maybe another `GINKGO_FLAGS` as well which are put in a separate place when calling the tests)?

Open to ideas, but I'll close this and if you have comments please put them on https://github.com/kubernetes/kubernetes/issues/78599

**Comment by shettich** [comment]
Ok, thanks.  Another random question: would it be possible/reasonable for the e2e test to just figure out the correct domain to use on its own?

**Comment by johnSchnake** [comment]
I really don’t know; I don’t have much experience in the options there. You may need to seek contributors to sig networking. Sorry I can’t help on that front.

**Comment by royshouvik** [comment]
For someone reaching here through search engine (as I did), it worked after specifying the cluster domain like this
```
sonobuoy run --plugin-env e2e.E2E_EXTRA_ARGS="--dns-domain=<YOUR_CLUSTER_NAME>.local" --wait
```

**Comment by wrohandi** [comment]
> For someone reaching here through search engine (as I did), it worked after specifying the cluster domain like this
> 
> ```
> sonobuoy run --plugin-env e2e.E2E_EXTRA_ARGS="--dns-domain=<YOUR_CLUSTER_NAME>.local" --wait
> ```

This flag worked on my cluster. I got passed test.
Thanks @royshouvik
