### ISSUE TITLE
Error running sonobuoy

### ISSUE THREAD

**Issue by timyinshi** [heptio/sonobuoy#766]
**What steps did you take and what happened:**
Who knows why we reported a log error while running sonobuoy?
the error is：
time="2019-06-19T11:41:04Z" level=error msg="error querying pod logs under namespace heptio-sonobuoy: the server rejected our request for an unknown reason (get pods sonobuoy-e2e-job-7d478649056a4bc3)"
**What did you expect to happen:**

**Anything else you would like to add:**
When I ran the e2e use case for k8s, I found an error. Do you know why?
 [k8s.io] [sig-node] PreStop
/workspace/anago-v1.14.3-beta.0.37+5e53fd6bc17c0d/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:687
 should call prestop when killing a pod  [Conformance] [It]
 /workspace/anago-v1.14.3-beta.0.37+5e53fd6bc17c0d/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:692

 waiting for server pod to start
 Unexpected error:
     <*errors.errorString | 0xc0002befb0>: {
         s: "timed out waiting for the condition",
     }
     timed out waiting for the condition
 occurred

 Unexpected error:
     <*errors.errorString | 0xc0028d03f0>: {
         s: "expected pod \"pod-configmaps-b046b489-929e-11e9-af6f-4a925cca4061\" success: Gave up after waiting 5m0s for pod \"pod-configmaps-b046b489-929e-11e9-af6f-4a925cca4061\" to be \"success or failure\"",
     }
     expected pod "pod-configmaps-b046b489-929e-11e9-af6f-4a925cca4061" success: Gave up after waiting 5m0s for pod "pod-configmaps-b046b489-929e-11e9-af6f-4a925cca4061" to be "success or failure"
 occurred

**Environment:**
- Sonobuoy version: 0.14.3
- Kubernetes version: (use `kubectl version`):1.14.3
- OS (e.g. from `/etc/os-release`): 16.04.4 LTS (Xenial Xerus)

**Comment by timyinshi** [comment]
I thought I was in China and I couldn't access the gcr.io, so I solved the problem by downloading the corresponding image to the local place.
Does anyone have a better way to get a GCR mirror?

**Comment by johnSchnake** [comment]
https://github.com/kubernetes/kubernetes/issues/56038 seems to be about that type of problem with k8s in general. I'd checkout that thread and seek guidance in some of the k8s channels on slack.
