### ISSUE TITLE
New query options

### ISSUE THREAD

**Issue by johnSchnake** [heptio/sonobuoy#777]
**Describe the solution you'd like**
https://godoc.org/k8s.io/api/core/v1#PodLogOptions shows that there are lots of pod log options which users might want access to (other limit options, adding timestamps to the logs, etc)

These are trivial to add into the config object, _maybe_ we can even just embed the podlogoptions object directly (not sure if the metadata would mess up the serialization, but even that could be fixed/removed from the serialization). Just an idea.

**Anything else you would like to add:**
https://github.com/heptio/sonobuoy/blob/ee6ecc84a101343434290b029ea3949d6ac575bd/pkg/discovery/pods.go#L40 is where the options object gets created

You can see an example of how the config object holds those values here: https://github.com/heptio/sonobuoy/blob/ee6ecc84a101343434290b029ea3949d6ac575bd/pkg/discovery/pods.go#L62-L63

The CLI does _not_ need to be updated for this change; in fact I don't want it to be (too many options). Just add them to the config object which users load via `--config`: https://github.com/heptio/sonobuoy/blob/ee6ecc84a101343434290b029ea3949d6ac575bd/cmd/sonobuoy/app/gen.go#L37

**Comment by MengmengZHANG** [comment]
I plan to work on this feature, hope that I could finish it in one month.
