### ISSUE TITLE
Query selectors

### ISSUE THREAD

**Issue by johnSchnake** [heptio/sonobuoy#778]
**Describe the solution you'd like**
We currently allow a label selector and a list of namespaces to be used to specify which podlogs to gather.

It makes sense to also allow a fieldselector to give more flexibility.

**Anything else you would like to add:**
The logic for the log gathering is currently:
 - get a list of namespaces to query later https://github.com/heptio/sonobuoy/blob/d34e9cf1558766473e312526e887c0559915af0d/pkg/discovery/discovery.go#L102
 - create a listOptions object using the labelselector https://github.com/heptio/sonobuoy/blob/d34e9cf1558766473e312526e887c0559915af0d/pkg/discovery/queries.go#L275-L289
 - list those pods and get logs for every container with the given podlogoptions https://github.com/heptio/sonobuoy/blob/ee6ecc84a101343434290b029ea3949d6ac575bd/pkg/discovery/pods.go#L56

This new fieldSelector would just enable power users to do more, but I don't want the design to complicate things if a user doesn't want to use it.

**Comment by MengmengZHANG** [comment]
I plan to work on this feature, hope that I could finish it in one month.

**Comment by MengmengZHANG** [comment]
If use the same field selector as K8s core, the supported fields are very limited:
- "metadata.name",
- "metadata.namespace",
- "spec.nodeName",
- "spec.restartPolicy",
- "spec.schedulerName",
- "spec.serviceAccountName",
- "status.phase",
- "status.podIP",
- "status.nominatedNodeName":

https://github.com/kubernetes/kubernetes/blob/a574bd63ed84ed6a9315d6fddebc7feb7b3242bd/pkg/apis/core/v1/conversion.go#L61-L69
https://kubernetes.io/docs/concepts/overview/working-with-objects/field-selectors/

**Comment by johnSchnake** [comment]
@MengmengZHANG That shouldn't matter to you; the selectors are just strings that we'll pass along. If upstream changes what they support it'll still work. I don't plan on adding extra validation on the Sonobuoy side for this.

**Comment by johnSchnake** [comment]
The open question here, for those playing along at home, is how resource queries are related to pod logs gathering.

Do we want to use the same filters for both? If you want pod logs from one set of objects does that mean you only want metadata for that set?

I argue that is clearly not the case since we currently hardcode the special case that we _always_ want podlogs from the heptio sonobuoy namespace.

I currently think that the best approach would be to add a few more fields so that we can explicitly select what _resources_ we want to gather and, separately, what _pod logs_ we want to gather.

This would mean adding the fields `namespaces`, `labelselector`, and `fieldselector` into a new section of the config.

For example, currently we have:
```
"Filters": {
    "Namespaces": ".*",
    "LabelSelector": ""
  },
```
and I think that the most accurate/clear thing would be to change this to:
```
"Filters": {
    "Namespaces": ".*",
    "LabelSelector": ""
    "FieldSelector": "" 
  },
"PodLogFilters": {
    "Namespaces": "heptio-sonobuoy",
    "LabelSelector": ""
    "FieldSelector": "" 
  },
```
The one problem I see there is that we are duplicating the `namespace` field (so if you are running in a different namespace we have to update both values to get the same behavior). So maybe for the new options something like
```
"PodLogFilters": {
    "SonobuoyNamespace": true,
    "Namespaces": "",
    "LabelSelector": "",
    "FieldSelector": "" 
  },
```
So that we don't duplicate that string and get out of sync. Then they can add other namespaces if they want or add separate field/label selectors.

Just like when adding the field selector to the existing config, we have to consider how to deal with input if the users set fieldselectors AND Namespaces (which are really backed by fieldselectors). To avoid ambiguity, I think that the simplest thing to do is simply say that:
 - if you set field selectors, the namespaces field is ignored
 - if you set field selectors AND the 'SonobuoyNamespace' field is true, then we will do two queries (one with your field selector and a separate one for just our namespace, i.e. the field selector `metadata.namespace=<namespace>`)
 - if you set namespaces and not field selectors then the namespace regexp is run to find the list of namespaces to query (like it is currently done)

Thoughts?

This means that the "namespaces" field is just an "easy button" for forming your own "fieldselector" that would match every namespace.

**Comment by MengmengZHANG** [comment]
1) I agree that we could have two separate filters: "Filters" for collecting resources and the "PodLogFilters" for collecting podlogs. It's easy to implement if "Filters" and "PodLogFilters" are independent fields, which don't have parent-child relationship.

2) For the filter structure, I'm thinking of:
- removing the "Namespaces" filter, since "FieldSelector" supports filtering by namespace.
- support a list of FiledSelectors, which is chained by "OR" operator

By default, to get resources from all namespaces, and get logs from heptio-sonobuoy:

```json
"Filters": {
    "LabelSelector": "",
    "FieldSelectors": [ ] 
  },
"PodLogFilters": {
    "SonobuoyNamespace": true,
    "LabelSelector": "",
    "FieldSelectors": [ ] 
  },
```
To get resources from a set of namespaces, and get logs from a set of pods:

```json
"Filters": {
    "LabelSelector": "",
    "FieldSelectors": [
      "metadata.namespace=heptio-sonobuoy",
      "metadata.namespace=olympus" 
    ]  
  },
"PodLogFilters": {
    "SonobuoyNamespace": false,
    "LabelSelector": "",
    "FieldSelectors": [
      "metadata.namespace=default,metadata.name=nginx",
      "metadata.namespace=kube-system,metadata.name=kube-controller" 
    ]  
  },
```

If both SonobuoyNamespace and LabelSelector/FieldSelectors are set, then then we will do two queries (one with your field/label selector and a separate one for just our heptio-sonobuoy namespace)

```json
"Filters": {
    "LabelSelector": "",
    "FieldSelectors": [ ]  
  },
"PodLogFilters": {
    "SonobuoyNamespace": true,
    "LabelSelector": "",
    "FieldSelectors": [
      "metadata.namespace=default,metadata.name=nginx",
      "metadata.namespace=kube-system,metadata.name=kube-controller" 
    ]  
  },
```

**Comment by MengmengZHANG** [comment]
I have just found one difficulties of implementing FieldSelector at Generic Level. For different types of resources, the supported fields are different. 

1) according to [k8s doc](https://kubernetes.io/docs/concepts/overview/working-with-objects/field-selectors/#supported-fields), all resource types support the metadata.name and metadata.namespace fields. And these two for me are the most frequently used ones.

2) Actually the doc is not totally correct. For non-namespaced resources, like "nodes" / "namespaces", query with fieldSelector [metadata.namespace=xxx] will return error:

>  field label not supported: metadata.namespace". 

For our current design, the global filter applies to both cluster resources and clustered resources, the following config will cause error when query for non-namespaced resources.
```json
"Filters": {
    "LabelSelector": "",
    "FieldSelectors": [
      "metadata.namespace=heptio-sonobuoy",
      "metadata.namespace=olympus" 
    ]  
  }
```

3) I'm wondering if the global FieldSelector makes sense, seems that the only field that all resources support is metadata.name. It's better to not touch the global filters, and only add FieldSelector for a specified resource, maybe at the Limits fields. For example:
```json
"Filters": {
    "Namespaces": ".*",
    "LabelSelector": ""
},
"Limits": {
    "PodLogs": {
        "SonobuoyNamespace": true,
        "LabelSelector": "",
        "FieldSelectors": [
            "metadata.namespace=default,metadata.name=nginx",
            "metadata.namespace=kube-system,metadata.name=kube-controller" 
        ],
        "Previous": false,
        "SinceSeconds": null,
        "SinceTime": null,
        "Timestamps": false,
        "TailLines": null,
        "LimitBytes": null,
        "LimitSize": "",
        "LimitTime": ""
    }
},
```

**Comment by johnSchnake** [comment]
👍 Sounds like a great path forward.

Still gets the magic logic out of code and lets users customize it if they want and allows more flexibility if you want all resources but a finite set of podlogs.

**Comment by MengmengZHANG** [comment]
Great~~~

1)  a small change to the structure, move SonobuoyNamespace from Limits->PodLogs to global Filters. When its set to true, all resources and logs from heptio namespace will be candidates to be collected. The current hard-coded logic is exactly the same as Filters->SonobuoyNamespace = true.

```json
"Filters": {
    "SonobuoyNamespace": true,
    "Namespaces": ".*",
    "LabelSelector": ""
},
"Limits": {
    "PodLogs": {
        "LabelSelector": "",
        "FieldSelectors": [
            "metadata.namespace=default,metadata.name=nginx",
            "metadata.namespace=kube-system,metadata.name=kube-controller" 
        ],
        "Previous": false,
        "SinceSeconds": null,
        "SinceTime": null,
        "Timestamps": false,
        "TailLines": null,
        "LimitBytes": null,
        "LimitSize": "",
        "LimitTime": ""
    }
},
```

2) About the relationship/priority between Filters and Limits->PodLogs:
- Filters will limit the namespaces of scan, for both resources and podlogs
- Filters.LabelSelector will limit the scope of scan, for both resources and podlogs
- Limits.PodLogs.LabelSelector, if provided, will override the Filters.LabelSelector when collecting logs
- Limits.PodLogs.otherParameters will further limit the scope when collecting logs

**Comment by johnSchnake** [comment]
Documenting our conversation for visibility:

Going with the design @MengmengZHANG had proposed just above this one:
```
"Filters": {
    "Namespaces": ".*",
    "LabelSelector": ""
},
"Limits": {
    "PodLogs": {
        "SonobuoyNamespace": true,
        "LabelSelector": "",
        "FieldSelectors": [
            "metadata.namespace=default,metadata.name=nginx",
            "metadata.namespace=kube-system,metadata.name=kube-controller" 
        ],
        "Previous": false,
        "SinceSeconds": null,
        "SinceTime": null,
        ...
```

Has the benefits of separating out the query/filters for resources vs podlogs. They are separate things and if a user wants to change both, I am OK with them having to make two separate changes to the config.

In general though, since the `Filters.Namespaces` defaults to `.*`, if the user just wants to get podlogs from another namespace they just add the single filter:
```
Limits.Podlogs.FieldSelectors = ["metadata.namespace=otherNS"]
```

The `SonobuoyNamespace` field then is just a way for the end user to continue to get podlogs from the Sonobuoy namespace without requiring both a change to the top level `Namespace` field (for which one to use) and the `FieldSelector` to also get logs from there. It is just an easy button for adding that fieldselector.

**Comment by MengmengZHANG** [comment]
Thanks @johnSchnake, so with the final design, Limits.Podlogs.LabelSelectors(limit getting logs) have nothing to do with Filters.LabelSectors (limit getting resources).

Here I provide two common use cases:
1) Default config => get resources from all namespaces, get logs from heptio-sonobuoy namespace
```json
"Filters": {
    "Namespaces": ".*",
    "LabelSelector": ""
},
"Limits": {
    "PodLogs": {
        "SonobuoyNamespace": true,
        "LabelSelector": "",
        "FieldSelectors": [] / null,
        "Previous": false,
        "SinceSeconds": null,
        "SinceTime": null,
        "Timestamps": false,
        "TailLines": null,
        "LimitBytes": null,
        "LimitSize": "",
        "LimitTime": ""
    }
},
```
2) Get resources from all namespaces, and get logs from all namespaces
```json
"Filters": {
    "Namespaces": ".*",
    "LabelSelector": ""
},
"Limits": {
    "PodLogs": {
        "SonobuoyNamespace": true,
        "LabelSelector": "",
        "FieldSelectors": [
            "metadata.namespace=default",
            "metadata.namespace=kube-system",
            "metadata.namespace=xxx",
            ...
        ],
        "Previous": false,
        "SinceSeconds": null,
        "SinceTime": null,
        "Timestamps": false,
        "TailLines": null,
        "LimitBytes": null,
        "LimitSize": "",
        "LimitTime": ""
    }
},
```

**Comment by johnSchnake** [comment]
Hm, thanks for enumertaing use cases with examples.  w.r.t. (2) that does make "get pod logs from all namespaces" difficult: you have to know ahead of time what they are to add the field selectors, which is why I'm sure Sonobuoy added the regexp in the first place. Apparently k8s has been asked about supporting wildcards there and the answer is 'no' for now. (See [here](https://github.com/kubernetes/kubernetes/issues/72196))

What if we were to also add a namespaces field there too? Again, it would be decoupled from the "resource gathering namespaces". Then we could fall back to the somewhat simple logic I prosed earlier (in a slightly different context):


What would make the most sense there?

**Comment by MengmengZHANG** [comment]
I'm thinking of the user's use case to get logs from all namespaces. After all, the major benefit of sonobuoy is running the plugins, and pod logs are just for purposes like debugging. In this case, since by default we gather logs from namespace heptio-sonobuoy, it should be enough.

I'm ok with both solutions. As you mentioned, the drawback of adding Limits.Podlogs.Namespaces is, the combination of namespaces field and FieldSelector can be conflicting/overlapping. And it's a bit weird that:
-  If you set field selectors, the namespaces field is ignored
-  If you set label selectors, the namespaces field is still taken into account

**Comment by MengmengZHANG** [comment]
And I'm thinking of the case that FieldSelectors = null, the k8s core treats it as no limitation at all, and return all pod logs. 

So for the following config, will it/does it make sense to return all the podlogs for all namespaces?
```json
"Limits": {
    "PodLogs": {
        "SonobuoyNamespace": false,
        "LabelSelector": "",
        "FieldSelectors": [] / null,
}
```

**Comment by johnSchnake** [comment]
I talked with @zubron about this and we came to a different conclusion that I think we're both a bit more happy with, let me know what you think.

Add `Namespaces`, `LabelSelectors`, and `FieldSelectors` to the `PodLogs` object as I had suggested but without the 'one takes precedence over the other' logic.

Instead `Namespaces` are just a shorthand for adding other fieldselectors which allows you to use regexp.

So if the user wants the default:
```
"SonobuoyNamespace":true
```

If the user wants all namespace logs:
```
"SonobuoyNamespace":true . //<-doesnt really matter
"Namespace": ".*"
```

if the user wants a specific selector (and still the default):
```
"SonobuoyNamespace": true
"FieldSelectors": ["foo1","foo2"]
```

If the user wants kube-system, the default namespace, and any other pod that might be running:
```
"SonobuoyNamespace": true
"FieldSelectors": ["metadata.phase=running"]
"Namespace":"kube-system"
```

So instead of being competing fields, they are all just additive. We'll run one query after the other and allow them to choose different types of queries to run if they want (default NS, NS based on regexp, explicit field selectors).

I think that makes a really useful structure for the user that is flexible and a little more intuitive.

The only implementation detail (which we've touched on before) is the need to not duplicate gathering logs since that may be more intensive than other, more basic/small API calls.

Thoughts? Follow up with @zubron about this as I am on PTO for the next few days.

**Comment by MengmengZHANG** [comment]
As a summary, we first define the targeted list of pods by:
`(Namespaces OR SonobuoyNamespace OR FieldSelectors) AND LabelSelector` 

Then for each pod, we could further define the format and size of the logs by other fields
`i.e. SinceSeconds, LimitBytes`
