### ISSUE TITLE
Error run sonobuoy with empty plugin list

### ISSUE THREAD

**Issue by MengmengZHANG** [heptio/sonobuoy#784]
**What steps did you take and what happened:**

I tried to run sonobuoy with an empty plugin list, in order to just collect podlogs. 
```
sonobuoy gen config|jq '.Plugins=[]' > noplugins.conf
sonobuoy run --config noplugins.conf
```
The sonobuoy master docker is stuck in creating:
```
NAME       READY   STATUS              RESTARTS   AGE
sonobuoy   0/1     ContainerCreating   0          2m1
2s
```
And the reason is
```
Events:
  Type     Reason       Age                From               Message
  ----     ------       ----               ----               -------
  Normal   Scheduled    51s                default-scheduler  Successfully assigned heptio-sonobuoy/sonobuoy to minikube
  Warning  FailedMount  19s (x7 over 51s)  kubelet, minikube  MountVolume.SetUp failed for volume "sonobuoy-plugins-volume" : configmap "sonobuoy-plugins-cm" not found
```

**What did you expect to happen:**
Sonobuoy master docker is running. And podlogs are gathered in tarball.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Sonobuoy version: v0.15.0
- Kubernetes version: (use `kubectl version`): 1.14.0
- Kubernetes installer & version: 
- Cloud provider or hardware configuration: local minikube
- OS (e.g. from `/etc/os-release`): macos
- Sonobuoy tarball (which contains * below)

**Comment by johnSchnake** [comment]
This seems like it should have a pretty simple cause; the plugins normally go in the configmap and then they're mounted into the aggregator. In this situation we have no plugins so I guess the plugin config map fails (surprised that doesnt cause some sort of error though in the cm phase).

The template shows:
```
---
{{- if .Plugins }}
apiVersion: v1
data:{{- range $i, $v := .Plugins }}
  plugin-{{- $i -}}.yaml: |
    {{ indent 4 $v }}
{{- end }}
kind: ConfigMap
metadata:
  labels:
    component: sonobuoy
  name: sonobuoy-plugins-cm
  namespace: {{.Namespace}}
{{- end }}
---
```
and that just needs tweaked so that the config map is always valid/created and just the data is added as necessary.
