### ISSUE TITLE
sonobuoy e2e --rerun-failed command runs the entire test suite

### ISSUE THREAD

**Issue by alexbrand** [heptio/sonobuoy#797]
**What steps did you take and what happened:**
1. Ran a sonobuoy test that resulted in some failures.
2. Downloaded the results tarball using `sonobuoy retrieve`
3. Deleted the heptio-sonobuoy namespace
4. Used the following command to re-run the failed tests: `sonobuoy e2e 201907031649_sonobuoy_85d03238-77c9-4c5e-8df7-6bf91e8d6a58.tar.gz --rerun-failed`

This resulted in a new deployment of sonobuoy running all the conformance tests:

```sh
# k logs sonobuoy-e2e-job-7a7439fae526457d e2e
+ set +x
+ /usr/local/bin/ginkgo '--focus=\[Conformance\]' '--skip=Alpha|\[(Disruptive|Feature:[^\]]+|Flaky)\]' --noColor=true /usr/local/bin/e2e.test -- --disable-log-dump --repo-root=/kubernetes --provider=local --report-dir=/tmp/results --kubeconfig=
+ tee /tmp/results/e2e.log
I0703 18:57:36.596085      20 test_context.go:406] Using a temporary kubeconfig file from in-cluster config : /tmp/kubeconfig-979058637
I0703 18:57:36.596399      20 e2e.go:241] Starting e2e run "bb773da5-079d-4f0b-b354-c6083908bb43" on Ginkgo node 1
Running Suite: Kubernetes e2e suite
===================================
Random Seed: 1562180254 - Will randomize all specs
Will run 215 of 4411 specs
```

**What did you expect to happen:**
Sonobuoy should only run the tests that failed.

**Comment by johnSchnake** [comment]
Seems to have been broken quite a while: https://github.com/heptio/sonobuoy/pull/315/files

Personally, I've never used this command, sorry for the problem. Should be an easy fix (we just need to set the skip/focus and there is a helper method for that already).

**Comment by spinfooser** [comment]
I also noticed this behavior as well. It'd be great if it could be fixed!
