### ISSUE TITLE
Add support for Mips64 architecture

### ISSUE THREAD

**Issue by packyzbq** [heptio/sonobuoy#802]
**Describe the solution you'd like**
Hi. I wonder if  the mips64 architecture will be supported in the future. 

By the way, I tried compile the heptio-e2e by myself, but it seems that heptio-e2e  contains a binary file which is not support for mips64. The base image of sonobuoy image does not support mips64 as well.

**Environment:**

- Sonobuoy version: v0.15
- Kubernetes version: (use `kubectl version`): 1.14.1
- OS (e.g. from `/etc/os-release`): NeoKylin 7.0

**Comment by johnSchnake** [comment]
I have not heard of any plan/intent to support that architecture.

If you share your use case it might help motivate that though. From my perspective, the biggest issue is just ensuring we have a signal about whether or not it really works on that architecture. The amd64 gets used most and we've had a few discussions which make it clear that a number of people utilize the arm64 version: so if it breaks in a way we aren't testing for they can tell us.

If there were enough people using mips64 and k8s was being built for it, then I think it would be reasonable to build for it.

Also, to try and build on a different architecture you just need to modify the makefile to swap out the base image/build commands as necessary.

> heptio-e2e contains a binary file which is not supported for mips64

I'm not sure what you're referring to here exactly; do you mean when building the Sonobuoy binary itself? What file is causing a problem?

**Comment by johnSchnake** [comment]
At this time my expectation is that we would move towards being able to support OS/archs that K8s supports. I dont see documentation that k8s supports MIPS, if I'm wrong let me know and happy to discuss this further.
