### ISSUE TITLE
Error when running on arm64

### ISSUE THREAD

**Issue by packyzbq** [heptio/sonobuoy#817]
**What steps did you take and what happened:**
Hi, I encountered a problem when running sonobuoy on a node of arm64 architecture. Pod cannot be created in the step named "KubeletManagedEtcHosts".It seems that the `quay.io/coreos/etcd:v3.2.26` image needs to set an environment variable. When I run `docker run quay.io/coreos/etcd:v3.2.26` , the result is as follows:

```
etcdmain: etcd on unsupported platform without ETCD_UNSUPPORTED_ARCH=arm64 set
```
So, I think it is necessary to add this parameter in the arm64 architecture to make the program run normally.

**Environment:**

- Sonobuoy version: v0.15
- Kubernetes version: (use `kubectl version`): v1.14.1
- OS (e.g. from `/etc/os-release`):  Kylin 4.2.0 / aarch64
- Sonobuoy tarball (which contains * below)

**Comment by johnSchnake** [comment]
It sounds like you're referring to a specific Kubernetes test, not something in Sonobuoy itself.

For this, you'd need to create an issue with the upstream repo https://github.com/kubernetes/kubernetes/issues

I'm sure someone more familiar with the arm64 setup can either fix the issue or provide information/context about it. I don't have personal experience but was under the impression that the tests were currently passing on arm.
