### ISSUE TITLE
The master should be setting the metadata.OwnerReference for all the pods that it creates

### ISSUE THREAD

**Issue by parikhamol** [heptio/sonobuoy#818]
**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

The sonobuoy master / aggregator will be creating pods / daemonsets for the plugins to runs. However if the master pods gets deleted , the plugin pods could potentially remain orphaned. 
To solve this scenario, the plugin pods should have their metadata.ownerReference set to the master pod. In such a scenario, as soon as the master gets deleted, all resource that have the ownerReference set to the master will also be cleaned up.

This is particularly useful in cases where the scan needs to be terminated preemptively . 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Sonobuoy version: sha256:0f67f88d2626e35f0d0351803eb1812975ec57f7ba45cdb842b42c39c3f74adf
- Kubernetes version: (use `kubectl version`): 14
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Comment by johnSchnake** [comment]
Seems like the right thing to do. I've had a number of people mention how they do/want to run Sonobuoy as a Job or ReplicaSet, in which case this needs to be set to ever delete things properly. Currently, the `sonobuoy delete` only works because it blows up the entire namespace.

**Comment by johnSchnake** [comment]
Stretch for this next release; will be probably rolled into some other work that @zubron is doing related to swapping out our templates for objects.
