### ISSUE TITLE
Result information should go into PluginStatus

### ISSUE THREAD

**Issue by johnSchnake** [heptio/sonobuoy#819]
**Describe the solution you'd like**
Once we have the capability to know if tests actually passed/failed (instead of just if a plugin ran or not) we should be updating our `status` metadata with that information. This way you can see whether or not a conformance run (or other plugin) was a success or not without even downloading the tarball.

I propose adding a new field to the `PluginStatus` object:
```
type PluginStatus struct {
	Plugin string `json:"plugin"`
	Node   string `json:"node"`
	Status string `json:"status"`

	// Propose new field below
	ResultStatus   string `json:"resultStatus"`
}
```

This value would be a string which would default to `unknown`. Once a we do post-processing on plugins, we should update the status on the aggregator pod to show the top level result (pass/failed/etc).

I am unsure if we should also walk the entire tree of data and also add the aggregate data (# passed/failed/etc).  If we want to do that we should add another field, something like:
```
ResultStatusDetails string
```
The problem/question about that is how we decide to format that so it is human-readable but also machine consumable. Maybe better would be something like:
```
ResultStatusDetails map[string]int
```
So it would look like `{"passed":5,"failed":1}`. This would be more machine consumable/scriptable but not necessarily bad for a human to read either.

**Anything else you would like to add:**
Prereq: https://github.com/heptio/sonobuoy/pull/813

I consider this a relatively high priority since, even though the PR above does all this aggregation, we aren't really utilizing it as much as we can. By adding this new status information, we make it so that users don't even have to download the tarball in order to get high-level result information. That can fundamentally change some user flows to be faster/easier.

**Comment by johnSchnake** [comment]
I wish this was able to have made it into v0.15.1 but we already were adding a few tweaks to the code before the release. I think that maybe this one will take a little bit of time to ensure we do it right.

The general goal is that users should be able to get the information they need about the plugin results without downloading the entire plugin.

With the idea I proposed on the initial issue, the logic would be like this:
 - ResultStatus = Status of the top level item in the results object (passed/failed/etc)
 - ResultStatusDetails = aggregate data of pass/fail/skipped

Is there something else that someone would need as metadata? The result of this is that after a run you could ping the sonobuoy status, take the json, and save it as a metadata object that would be able to inform you about a tarball (rather than the tarball is a black box you have to open to investigate)

**Comment by bhatth05** [comment]
The proposal looks good. For ResultStatusDetails, map[string]string might be more useful as it is more generic and may be useful for other plug-ins

**Comment by johnSchnake** [comment]
It would be useful to also add a SHA and size for the resulting tarball. Those wouldn't go in at the plugin level, but at the overall status layer. This way you could reconcile the tarball with that data to ensure you (1) have the tarball you intended to get (2) can check on size before downloading/saving to a location
