### ISSUE TITLE
New results data doesnt include stdout

### ISSUE THREAD

**Issue by johnSchnake** [heptio/sonobuoy#827]
**Describe the solution you'd like**
A common use case is not only wanting to know about the failures but to also drill down into the logs they output.

We should, in some capacity, be capturing that data as well.

It is so long that I don't think it is necessarily the best thing to always print it, but I have to ideas for now:
 1. Dont copy the actual logs, but instead add another metadata entry about the file/byteoffset so that we could read it if we wanted.
 2. Add another output mode, something like, `detailedLog` (? just an idea) that would also print that information. It is _very_ long so printing it by default, even in the `detailed` mode is a bit overkill.

**Comment by johnSchnake** [comment]
Outstanding question then is where to put it into the actual data struct:

```
type Item struct {
	Name     string            `json:"name" yaml:"name"`
	Status   string            `json:"status" yaml:"status"`
	Metadata map[string]string `json:"meta,omitempty" yaml:"meta,omitempty"`
	Items    []Item            `json:"items,omitempty" yaml:"items,omitempty"`
}
```

I could, right now, just save the `failure` and `system-out` strings in the `Metadata` map.

Is that the best thing to do right now? These are very `junit` specific so I don't want to make the `Item` specific to that format by adding something like a new `SystemOut` or `Failure`.

Would it make more sense to add a new, generic field `Details map[string]string` which would be similar to the metadata but be more appropriately named? `Metadata` for metadata (what file it came from, test duration, etc) vs details (some extra log output, <something else I cant imagine right now>)...

Thoughts @zubron ?

**Comment by zubron** [comment]
My preference would be for a more generic structure like you described with `Details` to avoid making specific to `junit`. Consumers of these reports might not be interested in having specific details and they can choose to ignore the field, or the type of item should be known based on the plugin/file data and they can process the data accordingly.
