### ISSUE TITLE
Need to be able to run a singe test.

### ISSUE THREAD

**Issue by vadbluedata** [heptio/sonobuoy#860]
I have the following failed test cases:

[root@mip-bd-vm39 ~]#  sonobuoy e2e --show=failed 201908271719_sonobuoy_e0c09e5c-033d-480b-9cc6-655e7301cfa5.tar.gz
failed tests: 13
[k8s.io] Container Lifecycle Hook when create a pod with lifecycle hook should execute prestop exec hook properly [NodeConformance] [Conformance]
[k8s.io] [sig-node] PreStop should call prestop when killing a pod  [Conformance]
[sig-api-machinery] Aggregator Should be able to support the 1.10 Sample API Server using the current Aggregator [Conformance]
[sig-apps] ReplicaSet should serve a basic image on each replica with a public image  [Conformance]
[sig-apps] ReplicationController should serve a basic image on each replica with a public image  [Conformance]
[sig-cli] Kubectl client [k8s.io] Guestbook application should create and stop a working application  [Conformance]
[sig-cli] Kubectl client [k8s.io] Kubectl logs should be able to retrieve and filter logs  [Conformance]
[sig-cli] Kubectl client [k8s.io] Update Demo should scale a replication controller  [Conformance]
[sig-network] DNS should provide /etc/hosts entries for the cluster [LinuxOnly] [Conformance]
[sig-network] DNS should provide DNS for services  [Conformance]
[sig-network] DNS should provide DNS for the cluster  [Conformance]
[sig-network] Networking Granular Checks: Pods should function for intra-pod communication: udp [LinuxOnly] [NodeConformance] [Conformance]
[sig-network] Networking Granular Checks: Pods should function for node-pod communication: udp [LinuxOnly] [NodeConformance] [Conformance]

I would like to run them individually with higher log levels to investigate further. How would i do that?

**Comment by zubron** [comment]
Thanks for your question. Apologies for taking so long to get back to you on this!

To run an individual test, you can use the flag `--e2e-focus`. This provides a regex when [running the e2e tests](https://github.com/kubernetes/kubernetes/blob/master/cluster/images/conformance/run_e2e.sh#L63-L70) to focus and run only the tests which match that regex. Note that as this is a regex, any special characters that are in the test name need to be escaped.

For example, to re-run the first test in your list, you would run Sonobuoy as follows:
```
sonobuoy run --e2e-focus "\[k8s.io\] Container Lifecycle Hook when create a pod with lifecycle hook should execute prestop exec hook properly \[NodeConformance\] \[Conformance\]"
```

(It's possible that you may be able to omit the prefixes and suffixes in `[]` and just supply the inner test name with no special characters and have the regex still match your specific test. You would need to try this and verify that it still only runs your desired test.)

To increase the verbosity level, the e2e test image provides an environment variable [`E2E_VERBOSITY`](https://github.com/kubernetes/kubernetes/blob/master/cluster/images/conformance/Dockerfile#L29) which is passed through to test executable to determine which log level verbosity to use. The default value is 4. You can provide a different value by making use of the `--plugin-env` flag which takes an argument in the following format `plugin_name.envvar_name=value`. This feature was introduced in Sonobuoy v0.15.0 so you will need to be using at least this version to be able to use this feature.

To increase the log level verbosity to 5, you would run Sonobuoy as follows:
```
sonobuoy run --plugin-env e2e.E2E_VERBOSITY=5
```

You can combine these two flags to specify the exact test you wish to run and the required verbosity.

Hopefully this answers your question! I'm going to close this issue, but if you have any problems with the instructions provided, or need further help, please feel free to re-open.
