### ISSUE TITLE
Running all tests from a sig

### ISSUE THREAD

**Issue by eddytruyen** [heptio/sonobuoy#880]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

When I run a custom sonobuoy yaml file, e.g.
```
     - name: E2E_FOCUS
       value: \[sig-storage]\ 
     - name: E2E_SKIP
       value: \[Flaky\]
```
I get the following log message in the beginning:
```
Random Seed: 1568462912 - Will randomize all specs
Will run 1332 of 1946 specs
```
and the following at the end

```
Ran 94 of 394 Specs in 10778.319 seconds
FAIL! -- 76 Passed | 17 Failed | 0 Pending | 300 Skipped
Ginkgo ran 1 suite in 2h59m39.106542796s
```

**What did you expect to happen:**
I would expect that at the end of the log the same amount of performeted tests has been reported as in the beginning of the log.

Moreover, I would have expected that all sig-storage tests have an entry in the e2e-logs. This is not the case:

E.g. All skipped "Dynamic Provisioning" tests in junit.xml:
```
 $ grep 'classname=\"Kubernetes e2e suite\" time=\"0\">' $filename | grep "Dynamic Provisioning"; done | sort -u
      <testcase name="[sig-storage] Dynamic Provisioning DynamicProvisioner allowedTopologies should create persistent volume in the zone specified in allowedTopologies of storageclass" classname="Kubernetes e2e suite" time="0">
      <testcase name="[sig-storage] Dynamic Provisioning DynamicProvisioner Default should be disabled by changing the default annotation [Serial] [Disruptive]" classname="Kubernetes e2e suite" time="0">
      <testcase name="[sig-storage] Dynamic Provisioning DynamicProvisioner Default should be disabled by removing the default annotation [Serial] [Disruptive]" classname="Kubernetes e2e suite" time="0">
      <testcase name="[sig-storage] Dynamic Provisioning DynamicProvisioner Default should create and delete default persistent volumes [Slow]" classname="Kubernetes e2e suite" time="0">
      <testcase name="[sig-storage] Dynamic Provisioning DynamicProvisioner delayed binding [Slow] should create persistent volumes in the same zone as node after a pod mounting the claims is started" classname="Kubernetes e2e suite" time="0">
      <testcase name="[sig-storage] Dynamic Provisioning DynamicProvisioner delayed binding with allowedTopologies [Slow] should create persistent volumes in the same zone as specified in allowedTopologies after a pod mounting the claims is started" classname="Kubernetes e2e suite" time="0">
      <testcase name="[sig-storage] Dynamic Provisioning DynamicProvisioner External should let an external dynamic provisioner create and delete persistent volumes [Slow]" classname="Kubernetes e2e suite" time="0">
      <testcase name="[sig-storage] Dynamic Provisioning DynamicProvisioner [Slow] deletion should be idempotent" classname="Kubernetes e2e suite" time="0">
      <testcase name="[sig-storage] Dynamic Provisioning DynamicProvisioner [Slow] should not provision a volume in an unmanaged GCE zone." classname="Kubernetes e2e suite" time="0">
      <testcase name="[sig-storage] Dynamic Provisioning DynamicProvisioner [Slow] should provision storage with different parameters" classname="Kubernetes e2e suite" time="0">
      <testcase name="[sig-storage] Dynamic Provisioning DynamicProvisioner [Slow] should provision storage with non-default reclaim policy Retain" classname="Kubernetes e2e suite" time="0">
      <testcase name="[sig-storage] Dynamic Provisioning DynamicProvisioner [Slow] should test that deleting a claim before the volume is provisioned deletes the volume." classname="Kubernetes e2e suite" time="0">
      <testcase name="[sig-storage] Dynamic Provisioning Invalid AWS KMS key should report an error and create no PV" classname="Kubernetes e2e suite" time="0">
      <testcase name="[sig-storage] Dynamic Provisioning [k8s.io] GlusterDynamicProvisioner should create and delete persistent volumes [fast]" classname="Kubernetes e2e suite" time="0">
```

Searching for these tests in the e2e log, showed only 1 test has been started and skipped.
```
grep  '\[sig-storage\] Dynamic Provisioning '  gke-1.13_sig-storage_sonobuoy_3e8c70f8-dd68-4469-a25d-21299aa4f735.log
[sig-storage] Dynamic Provisioning DynamicProvisioner Default
```
**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Sonobuoy version: v0.14.3 
- Kubernetes version: (use `kubectl version`): default GKE cluster for version K8s v1.13  (Kubernetes cluster deleted in the mean time)
- Kubernetes installer & version: GKE
- Cloud provider or hardware configuration: GKE -- four standard.4 machines 
- OS (e.g. from `/etc/os-release`): 
- Sonobuoy tarball (which contains * below)
[gke-1.13_sig-storage_sonobuoy_3e8c70f8-dd68-4469-a25d-21299aa4f735.tar.gz](https://github.com/heptio/sonobuoy/files/3613624/gke-1.13_sig-storage_sonobuoy_3e8c70f8-dd68-4469-a25d-21299aa4f735.tar.gz)

**Comment by johnSchnake** [comment]
Let me take a look at your tarball more in-depth tomorrow when I have a chance. On the surface, this appears to just be a confusion with how ginkgo reports pass/fail/skip but I will give a more detailed answer tomorrow.

**Comment by johnSchnake** [comment]
I've had a chance to look at your results; thank you so much for submitting the tarball.

It was indeed a confusing result set at first but it didn't take me long to realize I'd seen that sort of issue before: it is just a timeout.

Because you were running so many tests, the test run can go long and Sonobuoy will give up waiting for your plugins and try and kill them.

You can see in the middle of the Sonobuoy logs
```
time="2019-09-14T15:07:30Z" level=info msg="Gracefully shutting down plugins due to timeout."
```

and in the middle of the e2e logs:
```
sending TERM to 17

---------------------------------------------------------
Received interrupt.  Running AfterSuite...
^C again to terminate immediately
```

So, first of all, the quick workaround for you is to extend the timeout for Sonobuoy. Use the timeout flag (value is in seconds) to extend this. For 24h you'd use:
```
sonobuoy run --timeout=86400
```

Secondly, I wanted to say that I completely understand why you'd be confused by that output and I've created a new issue (#883) to improve the output from Sonobuoy during these situations. As it stands, all the timeout information is buried in the logs due to the follow-up/cleanup actions that take place (both in the e2e logs and in the sonobuoy logs).

My intent would be to ensure that the error state becomes more clear. I've actually had this happen to me where _all_ the tests are passing but ginkgo reports a failure: e.g. `FAIL! 10 passed - 0 failed - 0 skipped`. This can all be very confusing if you dont find those timeout lines.

Let me know if you have further questions.
