### ISSUE TITLE
Automatic detection of cloud provider by sonobuoy so provider-specific tests are ran

### ISSUE THREAD

**Issue by eddytruyen** [heptio/sonobuoy#881]
**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

Many tests in GKE are skipped with the message that tests are only for the gke provider and not local.
I would have expected however, that as sonobuoy automatically detects the K8s version of the cluster, it could also detect the cloud provider.
This seems not the case

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
Is there a workaround or an option to pass a cloud provider flag to sonobuoy? 
Is it possible to customize the sonobuoy generated yaml file with such flag? 

**Environment:**

- Sonobuoy version: v0.14.3
- Kubernetes version: (use `kubectl version`): 1.13
- Kubernetes installer & version: GKE
- Cloud provider or hardware configuration: GKE
- OS (e.g. from `/etc/os-release`): 4 standard standard.4 machines

**Comment by johnSchnake** [comment]
I am not exactly sure that there is a canonical way to always detect the cloud provider, though if you know of such a standard I think that would be a good addition.

The conformance e2e image provides an `E2E_PROVIDER` env var which you can use to specify this value though. (see the code [here](https://github.com/kubernetes/kubernetes/blob/master/cluster/images/conformance/run_e2e.sh#L70) )

For example:
```
sonobuoy run --plugin-env e2e. E2E_PROVIDER=gke
```

I think this answers your question so, for now, I'll close this. If you want to further discuss the auto-detection of the provider, please open another ticket to iterate on the idea.

**Comment by eddytruyen** [comment]
Thank you for the advice!

At first, the example code worked for me on GKE (although there is a space too much in your example) for dynamic provisioning. But thereafter it stopped working on GKE.

The test is immediately completed and the e2e.log gives the following unexpected zone error:
```
Sep 17 19:30:16.791: INFO: Failed to setup provider config: error parsing GCE/GKE region from zone "": unexpected zone:
panic:
Your test failed.
Ginkgo panics to prevent subsequent assertions from running.
Normally Ginkgo rescues this panic so you shouldn't see it.

But, if you make an assertion in a goroutine, Ginkgo can't capture the panic.
To circumvent this, you should call

        defer GinkgoRecover()

at the top of the goroutine that caused this panic
```
I have tried to migitate the issue by trying another version of sonobuoy and deploying the kubernetes cluster in another zone, but the same error occurs. I guess something has gone havoc with my Google Cloud project after the first run with sonobuoy. In attachment you find the first run and the havoc run. 

[gke-1.13_provider-1.13_Dynamic-Provisioning_DynamicProvisioner_sonobuoy_d2cd9afc-4aed-4877-881f-3f9ca129a325.tar.gz](https://github.com/heptio/sonobuoy/files/3623129/gke-1.13_provider-1.13_Dynamic-Provisioning_DynamicProvisioner_sonobuoy_d2cd9afc-4aed-4877-881f-3f9ca129a325.tar.gz)
[201909171930_sonobuoy_8e89c636-003c-4210-afc8-52a326660243.tar.gz](https://github.com/heptio/sonobuoy/files/3623130/201909171930_sonobuoy_8e89c636-003c-4210-afc8-52a326660243.tar.gz)
