### ISSUE TITLE
Cloud provider specific tests for Azure require config file

### ISSUE THREAD

**Issue by eddytruyen** [heptio/sonobuoy#901]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

I executed `sonobuoy run --env-plugin e2e.PROVIDER=azure` with a custom FOCUS variable

The conformance image exited with the following error
```
test_context.go:358] Using a temporary kubeconfig file from in-cluster config : /tmp/kubeconfig-878746082
Sep 24 18:09:15.074: INFO: Failed to setup provider config: config-file must be specified for Azure
```
The configfile can be specified in the e2e conformance image via the `KUBECONFIG` environment variable. 
However, the `.kube/config` file of my kubernetes cluster must be also be mounted into conformance container as a secret.  To do this, I performed the following steps with a regular conformance  image

  1. extend the e2e conformance yaml file with

```
env:
    - name: KUBECONFIG
      value: "/root/.kube"
```
```
    volumeMounts:
    - name: kubeconfig
      mountPath: "/root/.kube"
      readOnly: true
```
```
      volumes:
      - name: kubeconfig
        secret:
          secretName: kubeconfig
```` 
  2. create the secret.

```
mkdir operations
cd operations
cp ~/.kube/config .
kubectl create ns heptio-sonobuoy 
kubectl create secret generic kubeconfig --from-file . --namespace=conformance
````
When deploying this container image, the follow error is reported however:
```
/usr/local/bin/ginkgo --focus=[...] --skip=[...] --noColor=true /usr/local/bin/e2e.test -- --disable-log-dump --repo-root=/kubernetes --provider="azure" --report-dir="/tmp/results" --kubeconfig="/root/.kube"
Sep 24 19:20:48.341: INFO: Failed to setup provider config: config-file must be specified for Azure

[...]

The the top of the goroutine that caused this panic.

goroutine 1 [running]:
k8s.io/kubernetes/test/e2e/framework/ginkgowrapper.Fail.func1(0xc0000a0f00, 0x5d, 0x76e088a, 0x93, 0x17a, 0xc0010522c0, 0x153)
        /workspace/anago-v1.13.0-rc.2.1+ddf47ac13c1a94/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/ginkgowrapper/wrapper.go:63 +0xa1
panic(0x398d2c0, 0x4a84b10)
        /usr/local/go/src/runtime/panic.go:513 +0x1b9
k8s.io/kubernetes/vendor/github.com/onsi/ginkgo.Fail(0xc0000a0f00, 0x5d, 0xc001aabc80, 0x1, 0x1)
        /workspace/anago-v1.13.0-rc.2.1+ddf47ac13c1a94/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/ginkgo_dsl.go:255 +0xc8
k8s.io/kubernetes/test/e2e/framework/ginkgowrapper.Fail(0xc0000a0f00, 0x5d, 0xc001aabd28, 0x1, 0x1)
        /workspace/anago-v1.13.0-rc.2.1+ddf47ac13c1a94/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/ginkgowrapper/wrapper.go:67 +0x19b
k8s.io/kubernetes/test/e2e/framework.FailfWithOffset(0x1, 0x4518f69, 0x23, 0xc001aabe48, 0x1, 0x1)
        /workspace/anago-v1.13.0-rc.2.1+ddf47ac13c1a94/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/util.go:286 +0x143
k8s.io/kubernetes/test/e2e/framework.Failf(0x4518f69, 0x23, 0xc001aabe48, 0x1, 0x1)
        /workspace/anago-v1.13.0-rc.2.1+ddf47ac13c1a94/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/util.go:278 +0x5c
k8s.io/kubernetes/test/e2e/framework.AfterReadingAllFlags(0x7b35ae0)
        /workspace/anago-v1.13.0-rc.2.1+ddf47ac13c1a94/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/test_context.go:378 +0x2ca
k8s.io/kubernetes/test/e2e.init.0()
        _output/dockerized/go/src/k8s.io/kubernetes/test/e2e/e2e_test.go:58 +0xed
```
**What did you expect to happen:**
I thought from the first error report that adding the kube-config file is a resolution, but it's not. A specific Azure configuration file is necessary.
**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
Even without the config file mounted as a secret, conformance tests still are able to run correctly since the sonobuoy service account has the right roles for accessing the API of the Kubernetes cluster. 

**Environment:**

- Sonobuoy version: 0.14.4
- Kubernetes version: (use `kubectl version`): 1.13
- Kubernetes installer & version: Azure Kubernetes Service (AKS)
- Cloud provider or hardware configuration: Azure virtual machines
- OS (e.g. from `/etc/os-release`): 
- Sonobuoy tarball (which contains * below)

**Comment by johnSchnake** [comment]
@eddytruyen Great question.

So there seem to be two issues really.

1. The wording in the error messages seems to be misleading you because of the overloaded term `config`. There is no need to specify a kubeconfig file, deal with a secret and mounting it, etc. If a workload is running in the cluster, client-go figures out how to talk to the cluster without an explicitly specified kubeconfig. That first log one `Using a temporary kubeconfig file from in-cluster config` is actually a good, normal situation.

2. The `config` that is causing the problem is the config for the azure provider info. There are so many options available in the test framework that you can use a lot of CLI flags _or_ a config file to specify them.  Especially when you want to specify a certain provider, the framework needs to know more information about how to interact with that provider.

You can see there is a special `cloud-config-file` just for azure: https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/test_context.go#L338

This specifies the file for this cloudConfig type: https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/test_context.go#L216-L235

Unfortunately, this CLI value isn't settable via the default E2E test image (only a few env vars are supported) but there are a few approaches which I outline a bit in https://github.com/heptio/sonobuoy/issues/888#issuecomment-532388512. I've seen this come up a handful of times and so I am even elaborating on those options in an upcoming blog post.

Any updates the upstream E2E image (such as adding these flags) would only be available for newer clusters so 'fixing the upstream' isn't a viable option for you. And, going forward, there is a go-runner (discussed more in the linked comment) which allows you to specify any flags you want so it doesn't make sense to keep adding them to the bash script.

Let me know if you have further questions about this.

**Comment by eddytruyen** [comment]
Thank you for the quick reply!
I wonder if you could provide an example of the cloudconfig input file. Or some general instructions for formating.

**Comment by johnSchnake** [comment]
You can see the code that loads it for azure here: https://github.com/kubernetes/kubernetes/blob/411caaf4695dd3d0d97ca07b9abd24f82218407d/test/e2e/framework/providers/azure/azure.go#L37-L49

That seems to be tied to this function which will load it and expect it in the YAML format: https://github.com/kubernetes/kubernetes/blob/103e926604de6f79161b78af3e792d0ed282bc06/staging/src/k8s.io/legacy-cloud-providers/azure/azure.go#L516-L536

**Comment by eddytruyen** [comment]
I don't seem to get a working CloudConfig.yaml file, which is currently, 
```
ApiEndpoint: "management.azure.com"
ProjectID: "<hidden>"
Zone: "eastus"
Region: "eastus"
MultiZone: false
MultiMaster: false
Cluster: "test-12"
MasterName: ""
NodeInstanceGroup: "agentpool-availabilitySet-19250280"
numNodes: 3
ClusterIPRange: "10.0.0.0/8"
ClusterTag: ""
Network: "aks-vnet-19250280"
ConfigFile: "/root/azure-config/azure.yaml" # retrieved from kubernetes worker node
NodeTag: ""
MasterTag: ""
```
I get however the following error:
```
/usr/local/bin/ginkgo --focus=Services.*LoadBalancer --skip=Alpha|\[Flaky\] --noColor=true /usr/local/bin/e2e.test -- --disable-log-dump --repo-root=/kubernetes --provider="azure" --cloud-config-file="/root/azure-config/CloudConfig.yaml" --report-dir="/tmp/results" --kubeconfig=""
I0926 14:50:05.955328     114 test_context.go:358] Using a temporary kubeconfig file from in-cluster config : /tmp/kubeconfig-659938543
panic: interface conversion: cloudprovider.Interface is nil, not *azure.Cloud

goroutine 1 [running]:
k8s.io/kubernetes/test/e2e/framework/providers/azure.NewProvider(0x0, 0x0, 0x0, 0x0)
        /workspace/anago-v1.13.0-rc.2.1+ddf47ac13c1a94/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/providers/azure/azure.go:45 +0x2b0
k8s.io/kubernetes/test/e2e/framework.SetupProviderConfig(0x7ffe1c021d09, 0x5, 0x0, 0x0, 0x0, 0x0)
        /workspace/anago-v1.13.0-rc.2.1+ddf47ac13c1a94/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/provider.go:74 +0xba
k8s.io/kubernetes/test/e2e/framework.AfterReadingAllFlags(0x7b35ae0)
        /workspace/anago-v1.13.0-rc.2.1+ddf47ac13c1a94/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/test_context.go:373 +0x9e
k8s.io/kubernetes/test/e2e.init.0()
        _output/dockerized/go/src/k8s.io/kubernetes/test/e2e/e2e_test.go:58 +0xed

Ginkgo ran 1 suite in 593.614678ms
Test Suite Failed
```
The function for creating a new instance of ProviderInterface ([func NewCloud(configReader io.Reader) (cloudprovider.Interface, error](https://github.com/kubernetes/kubernetes/blob/103e926604de6f79161b78af3e792d0ed282bc06/staging/src/k8s.io/legacy-cloud-providers/azure/azure.go#L282)) does seem to reject the `\root\azure-config\azure. yaml` file, that is specified in the above YAML file. 

The following is maybe another issue, but is there another way to increase the verbosity of the error trace as to understand what is going on in  ([func NewCloud(configReader io.Reader) (cloudprovider.Interface, error](https://github.com/kubernetes/kubernetes/blob/103e926604de6f79161b78af3e792d0ed282bc06/staging/src/k8s.io/legacy-cloud-providers/azure/azure.go#L282))?
I have tried to pass the `--v=4` flag to the e2e.test binary of the container image but no more verbosity.

**Comment by eddytruyen** [comment]
Dear John,
There is again a confusion in terminology that cost me two days of needless debugging Kubernetes code
 * [test_context.CloudConfig ](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/test_context.go#L216-L235 ) is basically a general struct for holding the values of flags passed to the e2e testing suite. It is **not** parsed by [azure.parseConfig](https://github.com/kubernetes/kubernetes/blob/release-1.13/pkg/cloudprovider/providers/azure/azure.go#L516-L536)
 *[azure.Config](https://github.com/kubernetes/kubernetes/blob/release-1.13/pkg/cloudprovider/providers/azure/azure.go#L83-L153) is the actual Azure-specific cloud_config_file that needs to be passed via the `--cloud-config-file` flag of the e2e testing suite. This file is the one that is parsed by the above parseConfig file. The specification for this file can be found [here](https://github.com/kubernetes/cloud-provider-azure/blob/master/docs/cloud-provider-config.md). For AKS, the file is stored on every worker node under '/etc/kubernetes/azure.json'.

**Comment by eddytruyen** [comment]
Success:
```
root@e2e-conformance-test:/usr/local/bin# /run_e2e.sh
/usr/local/bin/ginkgo --focus=Services.*LoadBalancer --skip=Alpha|\[Flaky\] --noColor=true /usr/local/bin/e2e.test -- --disable-log-dump --repo-root=/kubernetes --provider="azure" --cloud-config-file="/root/azure_config/azure.yaml" --report-dir="/tmp/results" --kubeconfig=""
I0927 11:53:15.628391      22 test_context.go:362] Using a temporary kubeconfig file from in-cluster config : /tmp/kubeconfig-038917729
I0927 11:53:15.629170      22 azure_auth.go:81] azure: using client_id+client_secret to retrieve access token
I0927 11:53:15.629204      22 azure.go:282] Azure cloudprovider (read ops) using rate limit config: QPS=10, bucket=100
I0927 11:53:15.629212      22 azure.go:286] Azure cloudprovider (write ops) using rate limit config: QPS=1, bucket=5
I0927 11:53:15.629420      22 azure.go:359] Azure cloudprovider using try backoff: retries=6, exponent=1.500000, duration=5, jitter=1.000000
I0927 11:53:15.629518      22 e2e.go:224] Starting e2e run "637c1878-e11d-11e9-84cc-720bf88f3e5d" on Ginkgo node 1
Running Suite: Kubernetes e2e suite
===================================
Random Seed: 1569585195 - Will randomize all specs
Will run 4 of 2164 specs
[....]
Ran 4 of 2164 Specs in 610.320 seconds
SUCCESS! -- 4 Passed | 0 Failed | 0 Pending | 2160 Skipped PASS

Ginkgo ran 1 suite in 10m11.105565425s
Test Suite Passed
