### ISSUE TITLE
Sonobuoy CLI should allow specifying a directory of plugins

### ISSUE THREAD

**Issue by johnSchnake** [heptio/sonobuoy#906]
**Describe the solution you'd like**
We currently allow `sonobuoy run --plugin` but if you have numerous plugins this can get tedious and is more frustrating to script around.

I'd like to be able to specify something like `sonobuoy run --plugin-dir` or `--plugins` which may take a directory.

I think this would just be a shortcut for adding all those plugins one-by-one and wouldn't require much effort.

**Anything else you would like to add:**
I don't think this has to be overthought or have complex interaction with the existing `--plugin` flag. I think it is reasonable to allow both to be set and they are all just additive (i.e. it would be valid to say `--plugins lotsOfPluginsInThisDir --plugin alsoAddThisOne.yaml`

I am hitting this because of the integration suite we are putting together and I am currently creating lots of yaml plugin definitions and want to run them all.

**Comment by zubron** [comment]
I have a slight preference here for `--plugin-dir`, just because of how similar `--plugin` and `--plugins` are.

**Comment by johnSchnake** [comment]
I don't think it would be hard to just change the flag handling to even let `--plugin` just handle files _or_ directories. If it is a directory it will just load all the *.yaml files it finds in that directory.

It will prevent a new flag from being needed and just expands the use of that flag in a pretty resaonable way IMO.
